# 1 Introduction {#introduction}

The Centre for Longitudinal Studies (CLS) manages several world-leading cohort studies, including the 1958 National Child Development Study (NCDS), the 1970 British Cohort Study (BCS70), Next Steps (formerly known as the Longitudinal Study of Young People in England), and the Millennium Cohort Study (MCS). These studies have offered researchers a unique window into social change in Britain over the past 68 years (Ferri et al., 2003; Pearson, 2016) -- for instance, in the realms of physical and mental health, education, social mobility, and the labour market (Anders & Dorsett, 2017; Erikson & Goldthorpe, 2010; Gondek, Bann, Patalay, et al., 2021; Johnson et al., 2015). Beyond documenting these trends, the astonishing richness of the cohorts -- each contains several thousands of variables from many thousands of participants -- has enabled researchers to answer important causal questions across a range of research domains -- from the effects of breastfeeding on child development (Fitzsimons & Vera-Hernández, 2022) to the impact of laws promoting flexible working practices on workers' wellbeing (Avendano & Panico, 2018).

Making plausible causal inferences with observational data is not straightforward. Correlations between study variables may not reflect causal effects due to the variables sharing common causes (i.e., confounding), biases in the sample of individuals available for analysis (i.e., selection bias), and difficulties obtaining accurate measurements (i.e., information bias). As reviewed in the Appendix, there are many examples in which findings from observational studies have failed to be confirmed in randomised controlled trials (RCTs).

Nevertheless, many successes have been achieved; most famously, the discovery of tobacco smoking's deleterious impact on health, major ballast for which comprised evidence from observational studies (Cornfield et al., 1959). Decades of methodological development within econometrics, epidemiology, statistics and computer science has formalised the conditions under which causal inferences can be made with observational data and identified several methods that can -- when applied appropriately -- help researchers make valid causal inferences. Further, increasingly adopted frameworks and cognitive tooling -- notably, the Potential Outcomes Framework and Causal Directed Acyclic Graphs (DAGs) -- have made it far easier to understand and communicate sources of bias in observational studies and to determine appropriate analyses for estimating causal effects with data at hand.

The aim of this document is to review efforts towards making causal inferences using CLS's cohorts and to highlight what, to us, appear to be promising opportunities for causal inference that warrant further exploration with our data. To this end, we provide background on the problem of causal inference using cohort data ([Section 2](02-problem.qmd)), outline three overarching philosophies for making causal inferences ([Section 3](03-approaches.qmd)), describe the features of CLS's data that can (circumstances permitting) enable causal effect estimation ([Section 4](04-attributes.qmd)), and review specific methods especially suited to our data, including describing existing applications of these methods and discussing further opportunities for the methods' use ([Section 5](05-methods.qmd)). For each method, we provide key references for readers to further explore. We close by arguing that evidence from cohort studies should be considered within an overall strategy of 'triangulation' ([Section 6](06-discussion.qmd)), combining results from multiple, complementary research designs and taking 'varied views of a single object' (Rosenbaum, 2023) -- submitting a claim's assorted premises and predictions to empirical testing, in order to increase the robustness of causal inferences.

This guide assumes familiarity with regression. Otherwise, it is relatively introductory: the focus is on intuition -- equations are used only where necessary or enlightening and mathematical complexity is kept to a minimum. **Sections are relatively standalone and include clickable cross-references to other sections where necessary. Readers new to causal inference should begin with [Section 2](02-problem.qmd). The subsections in [Section 5](05-methods.qmd) can be read selectively.** [Sections 5.12](05-12-g-methods-for-time-varying-exposures.qmd)-5.13 address causal effect estimation for time-varying exposures and for mediation. [Sections 5.15](05-15-negative-control-outcomes-and-exposures.qmd)-5.20 discuss sensitivity to bias and ways to investigate alternative explanations to causal effects. These sections should be read alongside [Section 3.3](03-approaches.qmd#elaborate-theories) on *elaborate theories,* at least. For readers with a background in causal inference, [Section 3.3](03-approaches.qmd#elaborate-theories) and [Sections 5.15](05-15-negative-control-outcomes-and-exposures.qmd)-5.20 may be most novel as they describe an arguably underappreciated perspective on the task of causal inference.
