# 3 Three Approaches to Causal Inference {#three-approaches-to-causal-inference}

With the basis gained from [Section 2](02-problem.qmd), we now outline three approaches for attempting to make causal inferences with cohort data: model-based approaches, design-based approaches and *elaborate theories*. These approaches are not mutually exclusive and the boundaries between them are not sharp. They do not, for instance, map onto a set of non-overlapping methods -- a particular study may use a combination of approaches, as the assumptions of one may only be correct when using another, or alternatively could use multiple approaches to examine whether each, having separate biases, triangulate upon the same answer. For example, an instrumental variable (IV) study may also use model-based statistical control for known confounders to improve the plausibility of the IV assumptions (Brumpton et al., 2020). Regardless, delineating and describing the three approaches helps clarify the virtues and limitations of each, and provides a useful organising schema for the specific causal inference methods detailed in [Section 5](05-methods.qmd).

## 3.1 Model-Based Approaches {#model-based-approaches}

The model-based approach is the most frequently used in quantitative research. In this approach, the researcher develops a statistical model -- or uses other related algorithms, such as matching -- to account for the influence of factors that bias the relationship between exposure and outcome in the available data. The model developed reflects the researcher's beliefs about the underlying data-generating process: accounting for biasing influences is *post hoc*. The purpose of the model is to remove the influence of biasing factors in the exposure or outcome -- to "attempt to compare people who are not directly comparable" (Rosenbaum, 2020). The model-based approach is often referred to as the non-equivalent group design (Reichardt, 2019), which highlights the fundamental problem.

The most popular model-based method is multivariable regression, where variables other than the exposure are added as covariates and their influence on the outcome modelled. Stratification -- where associations are calculated within sub-strata of the data (e.g., males and females, separately) and then pooled -- can also be considered a model-based approach, though it does not involve modelling the influence of the stratifying variables directly; within strata, exposure assignment is assumed to be as-if random (potentially after adjustment for additional variables, as described above).

Model-based approaches can be more principled or less. With correct knowledge of the data-generating process (e.g., how individuals are assigned to the exposure), accurate measurement of all relevant factors, and an appropriate understanding of how to incorporate the data into a model (e.g., with the correct functional form and sensible choice of adjustment set), the model-based approach would recover a causal effect, sampling variation notwithstanding. However, this is not how the model-based approach is typically used. Perhaps more frequent are 'Causal Salad' approaches (McElreath, 2020) where an array of covariates is haphazardly thrown into a statistical model, with only a vague sense of how these will ameliorate bias as the researcher has not systematically considered the causal network within which these covariates sit; as shown in [Section 2.2.3](02-problem.qmd#confounding-bias), unaware, a researcher can increase bias by conditioning on certain variables.

Though researchers using model-based approaches may note (usually in a Limitations section) the possibility of bias remaining, the ambition is to have obtained a causal estimate. The caveat is regularly vague or noncommittal and the researcher may write the rest of the paper as if a causal estimate had been obtained, though it had not. Because the model-based approach relies upon recapitulating the data-generating process, and in many circumstances this is unknown, it is easy for analyses to obtain biased estimates of causal effects and for researchers to fool themselves into believing this is not the case.

## 3.2 Design-Based Approaches {#design-based-approaches}

The design-based approach differs from the model-based approach in that the researcher uses knowledge about treatment assignment to identify *a priori* circumstances where treatment assignment should be as-if random. Data are analysed to exploit this 'exogenous' (originating outside the system) variation to obtain a causal effect. Examples of this approach include studies that use natural experiments or quasi-experimental approaches such as regression discontinuity or instrumental variable designs, where for some set of individuals, exposure is proposed to be unrelated to factors that confound the relationship of interest more generally.

As with the RCT, randomness of the assignment mechanism can guarantee exchangeability, even without detailed understanding of what potential confounders may be. For instance, who wins a prize among lottery players is a fully random process (that is, unless the game is rigged), which is why lottery wins have been used to study the causal effect of wealth on health (Cesarini et al., 2016). However, not all design-based approaches may exploit straightforwardly random processes. Assignment may be for fully legible, predictable reasons, but still be exploitable in a design-based approach if it can be argued that assignment is not related to (potential) outcomes, except through its effect on exposure. This is the basis of many instrumental variable studies. For instance, in a classic paper in political economy, Acemoglu et al. (2001) use early European settler mortality rates as an instrument for whether a colonising country set up extractive institutions in a colonised country in order to assess the effect of institutional quality on long-term economic development. Their argument is that countries where tropical disease made mortality high would be less attractive for individuals from the colonising nation to settle in, thereby incentivising the development of institutions oriented to short-term resource extraction. Identifying this variation and successfully making the argument it meets the conditions for a valid instrumental variable ([Section 5.9](05-09-instrumental-variables.qmd)) requires deep domain-specific knowledge.

Additionally, some design-based methods are not able to account for all sources of bias but instead use knowledge about assignment to account for distinct classes of confounder. For instance, sibling designs account for shared familial factors by comparing outcomes among siblings discordant on an exposure, without knowing exactly what these shared familial factors are (Donovan & Susser, 2011): factors that are shared do not contribute to the outcome variance within sibling sets and so cannot confound the association between exposure and outcome, though factors that aren't shared still have the potential to confound associations. The sibling design and other related methods are examples of *isolation*, where a smaller set of comparisons is exploited that are expected to be less biased than the wider set of comparisons that could be made (Zubizarreta et al., 2018).

## 3.3 Elaborate Theories {#elaborate-theories}

The model- and design-based approaches are concerned with causal effect estimation. The Elaborate Theories approach follows a different tack and focuses more broadly on strengthening causal inference (which, according to Shadish & Cook, 1999, is 'more a matter of logic than statistics'). Instead of being occupied with identifying random variation, it takes theories seriously and asks what specific predictions a theory makes about the world. Instances where these predictions differ from those of competing theories are where causal inferences can be made. Two variables, X and Y, being associated because X *causes* Y is a theory, but X and Y being associated because they are confounded by U is a theory, too. Both theories may entail a larger set of (more specific) predictions -- a *pattern* of anticipated empirical observations (Trochim, 1985, 1989) -- that may not fully overlap; the places of non-overlap are where useful information can be gleaned.

An historical example may make this more concrete. In the mid-19th century, London was beset by outbreaks of cholera; one such outbreak in August 1854 centred around Soho's Broad Street pump (Adhikari et al., 2024; Coleman, 2019). The prevailing theory of the time was that cholera was transmitted via *miasmas* -- bad airs. A prediction of this theory was that individuals living close together would succumb to the illness as they breathed the same air. The physician John Snow had another theory, however -- that cholera was caused by contaminated water. This theory was supported by several observations that were inconsistent with miasma causing the disease, including: no deaths among workers at the nearby Lion Brewery, who did not take water from the Broad Street pump (instead drinking the beer they produced); and the case of Mrs Eley, a deceased resident of Hampstead, who had water from the Broad Street pump delivered to her house as she liked the taste, an unfortunate preference, given a cesspit containing sewage from cholera victims had been leaking into the well the pump drew from. At one level, both the miasma and contaminated water theories made the same prediction -- clustering of cases in certain areas -- but at a more specific level, the predictions varied, and this allowed John Snow to provide compelling evidence, even with purely observational data, of how cholera was caused.

Exceptions to theories like the inebriated employees of Lion Brewery are rarely so vivid, but the Elaborate Theory approach can still prove insightful when arguments are more dry. For instance, Elaborate Theory-style reasoning has been used to appraise explanations of the well-established association between socioeconomic position (SEP) and health. One such explanation is that associations are explained by confounding by cognitive ability (Gottfredson, 2004), rather than a causal effect of SEP as more commonly claimed (Link & Phelan, 1995; Marmot, 2015, 2016). One corollary of the former theory is that correlations between SEP and health should be stronger for measures of SEP that are more closely related to cognitive ability (education \> socioeconomic class \> income) as confounding would be stronger, a prediction not necessarily entailed by *causal* explanations of the association (e.g., associations driven by the causal effect of differences in financial resources). The empirical observation that associations are not stronger for measures of SEP more closely related to cognitive ability is therefore evidence against cognitive ability being sufficient to explain the social gradient in health (Singh-Manoux et al., 2005) and refocuses attention on other possible confounders.

The Elaborate Theories approach had its first expression in Sir Ronald Fisher's gnomic reply to a question from William Cochran on how to move from correlation to causation in observational data ('Make your theories elaborate'; quoted in Cochran, 1965). Cochran concurred with this assessment ("this multi-phasic attack is one of the most potent weapons in observational studies") and the approach has since been staunchly and eloquently advocated by, among others, the statistician Paul Rosenbaum, including in his superlative book *Observation and Experiment* (Rosenbaum, 2019), which we highly recommend. See also Rosenbaum (2023), Reichardt (2019), Shadish & Cook (1999), Shadish et al. (2002), and Trochim (1985, 1989).[^13]

How does one make a theory elaborate in practice? Several methods exploit the logic of Elaborate Theories and are particularly suited to cohort data. Generally, these exploit situations where an important hypothesised mechanism of action (either for the main causal effect of interest or for competing explanations) is expected to be absent or else stronger or weaker than otherwise. Above, confounding was expected to act more strongly for some measures of SEP than others. The following examples give additional strategies.

- **Variation in active ingredient:** Observational studies attempting to ascertain whether cannabis has a causal impact on schizophrenia risk may exploit the expectation that correlations between cannabis use and schizophrenia should be stronger where concentrations of THC (the supposed schizophrenia-inducing compound) are greater (Gage et al., 2016).

- **Variation in confounding structures:** Observational studies that want to ascertain the effect of breastfeeding on child development may compare associations in settings where the social patterning of breastfeeding (a major hypothesised confounder) is entirely opposite (Brion et al., 2011).

- **Specificity of association:** Observational studies attempting to ascertain the carcinogenic effect of tobacco use could determine whether the profile of specific cancers is consistent with how the tobacco is used -- for instance, an excess of throat cancers among cigarette smokers (who inhale smoke) and mouth cancers among cigar smokers (who do not) (Cornfield et al., 1959).

- **Timing of effects:** The legalisation of abortion may reduce aggregate crime rates by disproportionately leading to terminations of pregnancies that would have yielded children at higher risk of going on to commit crimes (Donohue & Levitt, 2001). This effect should only be observed as the cohorts affected by such legalisation grow to an age where they are more likely to commit crime (i.e., adolescence and early adulthood). Similarly, flu vaccination should only have effects on mortality at times of the year when influenza is prevalent (L. A. Jackson et al., 2006).

- **Absence of hypothesised mechanism:**

  - *In a subgroup*: Observational studies that want to ascertain the effect of alcohol on cardiovascular disease may surmise that genes related to alcohol use (such as the ALDH2 gene that determines the comfort with which one can metabolise alcohol) should also be related to cardiovascular disease but only among populations where alcohol is used (L. Chen et al., 2008).

  - *In a historical period*: Observational studies that seek to understand the effect of socioeconomic position on a health outcome and posit access to health information and technologies as a key mediator may examine changes in inequalities in health before and after relevant medical knowledge is discovered or publicised (Clouston et al., 2016).

  - *In a geographic area*: Observational studies attempting to ascertain whether policies to reduce teenage pregnancies were effective may investigate whether reductions in teenage pregnancy rates were confined to countries in which policies were implemented (Baxter et al., 2021).

A concept related to Elaborate Theories is the *quasi-experiment device*. Studies using quasi-experimental devices utilise additional data to disambiguate an observation that would otherwise be ambiguous -- e.g., to judge whether an association reflects a causal effect of interest or that of a competing theory (Rosenbaum, 2019). For instance, to assess whether the English Teenage Pregnancy Strategy achieved its aims, a quasi-experimental device would be to use comparator data from Scotland and Wales (Baxter et al., 2021).

[^13]: The Elaborate Theories approach has alternatively been referred to as "pattern matching" (Reichardt, 2019; Trochim, 1985, 1989). Expressed by Shadish et al. (2002; quoted in Reichardt, 2019): "The more complex pattern that is successfully predicted, the less likely it is that alternative explanations could generate the same pattern, and so the more likely it is that the treatment had a real effect".
