# 4 Attributes of CLS's Cohort Studies That Support Causal Inference {#attributes-of-clss-cohort-studies-that-support-causal-inference}

Our thesis in this document is that the richness of the data in CLS's cohort studies can support researchers in making causal inferences. In this section, we highlight several features of these data that are especially useful -- specifically, the breadth and depth of the data, the ability to perform data linkage, the longitudinal nature of the studies, the extended timespan they collectively comprise, their large sample sizes, and their capacity for harmonisation with other cohort studies.

## 4.1 Breadth and Depth {#breadth-and-depth}

Collectively, CLS's cohort studies include several tens of thousands of variables available by standard "Safeguard data" End User Licence on the UK Data Service. These variables are largely derived from survey questionnaires -- the ability to link with other data increases this number dramatically. Combined, these data represent a profound insight into participants, their lives and the milieus in which they are situated. Data collections span birth (or, in the case of Next Steps, adolescence) to the current day. Within a survey sweep, data are collected on a range of participant characteristics -- for instance, batteries of questions on mental and physical health, psychosocial development, socioeconomic circumstances and the home environment. This includes frequently analysed factors, such as employment status, but also relatively niche information, such as participants' use of suncream, which was asked at the Age 42/44 year Biomedical Sweep of the NCDS. (In [Section 5](05-methods.qmd), we will argue that seemingly unimportant information like this can be used to support causal inference -- for instance, as falsification tests.) The range of data available also makes assumptions of no unobserved confounding (in standard regression) or missingness at random (in multiple imputation) more plausible (Mostafa et al., 2021). Extensive data are also available on cohort members' parents, partners, children and siblings. This can enable several causally informed research designs, such as sibling comparison and parental comparison designs and within-family-based Mendelian Randomisation.

## 4.2 Extensive Data Linkages {#extensive-data-linkages}

Data linkage only increases the size and variety of information available, mechanistically increasing the possibilities for causal inference (e.g., increasing sample representativeness; Rajah et al., 2023). Nevertheless, some data linkages represent opportunities that are specific to the type of data being linked. Some of this data linkage may be qualitative and contextual; for instance, linkages that are possible from knowing significant dates (e.g., interview dates or dates of birth). Fitzsimons & Vera-Hernández (2022) use information on whether MCS participants were born at the weekend as an instrument for maternal breastfeeding (due to lower staffing on maternity wards, new mothers are less likely to be offered breastfeeding support on weekends). Other examples of this contextual linkage include the effects of news and current events on mental health and other outcomes using interview date as a determinant of exposure to the information (Muñoz et al., 2020).

CLS's cohorts are increasingly linked to administrative and geographical data and each cohort has also now been genotyped, allowing for genetic data to be linked with survey responses. Administrative data and geographic linkages provide many opportunities for utilising quasi-experiments -- events or episodes in which exposures are allocated as-if randomly. For instance, studies exploiting arbitrary thresholds that are used to decide eligibility for programmes or interventions (e.g., thresholds for determining low birth weight, grading schemes in education that determine a pass or a fail, or geographic boundaries that determine the government policies one is subject to). Genetic data enable a specific form of instrumental variable analysis -- Mendelian Randomisation -- that exploits random assortment of parental genes during meiosis.

## 4.3 Longitudinal Assessment {#longitudinal-assessment}

The longitudinal nature of the studies means that the same or similar measures are asked across time. For instance, in the MCS, there are questions on several dimensions of mental health asked across childhood to late adolescence and now into early adulthood. Longitudinal data have four properties that aid causal inference. First, prospective data collection and repetition can enable more accurate measurement of study variables. Second, longitudinal assessment allows researchers to specify the correct temporal ordering (causes should precede consequences) with variables measured at different sweeps. Third, repeated measurement allows researchers to control for prior exposures and outcomes. Controlling for prior exposure allows for the 'treatment' to be more specifically defined (e.g., unemployment at age 33y among those who have not yet been unemployed), and controlling for prior exposure and/or outcomes can absorb some of the confounding bias that may otherwise exist as well as account for reverse causality processes (VanderWeele et al., 2020). Fourth, one can use within-person variation, rather than rely solely on between-person differences. Using within-person variation enables researchers to, e.g., account for time-invariant confounding factors by design, rather than through statistical control ([Section 5.5](05-05-longitudinal-fixed-effects.qmd)).

## 4.4 Extended Timespan {#extended-timespan}

Mainstage data collections in CLS's cohorts collectively span the 68 years from 1958 to the present day. This period can be increased when combined with other cohort studies, such as the National Survey of Health and Development (NSHD; the 1946 British Birth Cohort Study; Kuh et al., 2011). Several profound societal-level changes have occurred over this period, including the obesity epidemic, the expansion of further and higher education, and the greater participation of women in the labour market (Anders & Dorsett, 2017; Erikson & Goldthorpe, 2010; Gondek, Bann, Patalay, et al., 2021; Johnson et al., 2015). As will be expanded upon in [Section 5](05-methods.qmd), these societal-level changes offer several opportunities for causal inference. Briefly: confounding structures for some exposure-outcome relationships may have changed across time or causal effects may be confined to some periods or may vary across time in predictable ways (e.g., stronger in some periods rather than others). Elucidating each of these possibilities is one way in which theories can be made *elaborate* and causal arguments can be developed.

## 4.5 Large Sample Sizes {#large-sample-sizes}

The large sample size of CLS's cohorts is important in its own right for precise statistical estimation -- some causal inference methods, such as instrumental variables, are power hungry -- but it also means that important subgroups can be identified. For instance, where an exposure is confined to a local geographic area (e.g., the London smog), a large overall sample size can mean sufficient numbers appear in the exposed group. There may also be circumstances where a research design is more plausible within a subgroup; for instance, Rosenbaum (2020) argues that a frequently used instrumental variable, time to nearest hospital, can be made more plausible by focusing on individuals outside large cities who have less choice over the hospital they use. Further, some subgroups possess particular properties that make them useful for analyses. This includes groups that are frequently used in family-based designs. Each of CLS's cohorts contains a number of twins and data are sometimes collected from other (older or younger) siblings, too; for instance, MCS contains two sweeps of information from an older sibling. NCDS also contains a number of adopted children -- again, useful in particular family-based study designs. Some of these subgroups may be small, but as the next section notes, CLS's cohorts may be harmonised and analysed alongside other cohort data, so the subgroups within CLS's cohorts can contribute to a larger analytic sample.

## 4.6 Ability to Harmonise Data {#ability-to-harmonise-data}

Harmonising data with other cohorts can expand the time span of studies or the geographic area covered. This again enables studies that test elaborate theories: confounding structures may differ across space as well as time, and causal effects may be present, weaker or stronger in some areas than others. For instance, Brion et al. (2011) use a UK and Brazilian cohort to assess the effect of breastfeeding on development -- the (confounding) association between SEP and breastfeeding is strong in the UK, but not in Brazil. Various efforts have been made to collate and harmonise data across different cohorts.

CLOSER (2023) has released several projects harmonising data from CLS's cohorts on, among other things, socioeconomic status (see also Centre for Longitudinal Studies, 2026). Also useful are the Atlas of Longitudinal Datasets (2024) and the Catalogue of Mental Health Measures (2026), whose names are self-explanatory, and Harmony (2023), an online tool that uses natural language processing to identify survey items that are similar semantically across different studies (including non-CLS studies).
