# 5.8 Natural Experiments {#natural-experiments}

## 5.8.1 Method {#method}

In RCTs, researchers intentionally use a procedure to assign people to treatment groups at random. The outcome of the procedure is -- in expectation -- not systematically related to factors, besides the treatment it determines (and consequences thereof), that may affect subsequent outcomes of interest, both known and unknown. In so far as the randomisation procedure can be said to affect outcomes, it is via the intervention that membership of a particular treatment group entails. For example, in sufficiently large RCTs that use the results of a fair coin toss to determine assignment, the results of coin tosses should not be correlated with participants' sex, age or other characteristics, other than through chance, but could still be related to outcomes through the treatment group the coin tosses determine. This bears repeating: the coin toss can have a causal effect on outcomes, but it is only through its effect on treatment group.

Analogous processes sometimes occur without a researcher's input. Most clearly, this occurs where randomisation is adopted for reasons other than sating academic interest -- for instance, to allocate a resource. During the Vietnam War, the US Government used a lottery to draft soldiers. Besides being a politically palatable method of conscription, the draft has also been a valuable tool for understanding the effects of military service on various life outcomes [see, e.g., @ref456]. Games of pure chance, such as roulette and national lotteries, provide players with an endorphin rush, but also help researchers study the effects of wealth shocks on, e.g., health [@ref6390]. Note, in each of these, randomisation occurs only among people who are entered into the lottery. In the Vietnam draft, this was healthy males of conscription age. In gambling lotteries, it is individuals who have bought a ticket ([Figure 5.9](#figure-5-9)). Comparing draftees or prize winners with everybody else, entrant or not, would not recover a causal effect.

::: {#figure-5-9}

![**Figure 5.9:** DAG representing a study using lottery wins to examine the effect of wealth on health. In observational data, the association between wealth and health may be biased by a host of confounders U (e.g., education level). Lottery wins represent a source of random variation in wealth, though only among lottery players -- the decision to enter a lottery may be influenced by factors that also influence health (e.g., education level), but which player wins is a random process (unless rigged). More accurately, the total number of lottery tickets bought determines the expected win amount, so an ideal lottery study would condition upon number of tickets bought.](images/image26.png){width="42%"}

:::

The Vietnam draft and national lotteries are examples of *natural experiments* and have the same properties that justify RCTs -- assignment (a) influences exposure, (b) only has an effect on outcomes via its effect on exposure, (c) is not determined by other causes of the outcome, and (d) individuals (or other relevant observational units) subject to the natural experiment had a non-zero chance of both exposure and control. As with RCTs, these properties arise because of the explicit use of a randomisation procedure. But it is these properties that are of value, not randomisation itself.

There are many other cases where random processes are used to allocate resources. Sometimes this is an intentional feature of the process, as with lotteries. Other times it is a byproduct of other concerns. In social housing, individuals at the top of a waitlist may be offered whatever accommodation comes available first [@ref257]. In health, being born on a weekday rather than the weekend influences staff availability and thus the breastfeeding advice a new mother and her baby receive [@ref649]. Processes like these are not random in the sense that exposure occurred for no predictable reason; housing becomes available when someone leaves a property and hospitals lower costs by reducing staff levels on weekends. Rather, the reasons for exposure are unrelated to potential outcomes: expectant mothers have little control over whether they go into labour on a Friday or a Saturday, and people on a housing waitlist do not control which houses become vacated as they move to the top of the list. Assignment mechanisms like these are said to be "as-if random" and have the properties that justify RCTs -- assignment only has an effect on outcomes via the effect on exposure and assignment is not determined by other causes of the outcome.

Many natural experiments appear in survey data due to as-if random assignment to interview dates. The Unexpected Event During Survey Design [UESD\; @ref453] exploits large-scale events, such as major sporting competitions (e.g., the Olympics or the World Cup), political incidents, natural disasters, and terrorist atrocities occurring at some point during survey fieldwork and which bifurcate the sample into those surveyed before the event and those surveyed during or after. On the assumption that interview timing is unrelated to potential outcomes, comparing groups surveyed before and after the event can be used to determine the event's causal effects, such as its effect on measures of psychological wellbeing, behaviour and political and social attitudes.

Assessing whether the assumption of as-if random interview timing is plausible in a given application requires detailed knowledge of the survey being utilised, its design and how it was conducted. The assumption may be violated if, for example, participants with the lowest chance of response are allocated to be interviewed first, so that further contact attempts could be made before the end of fieldwork, if necessary. In many surveys, participants are allocated to fieldwork 'waves' based upon shared characteristics -- random assignment to interview date *within* these groups may be plausible, but between groups, not. The assumption of random timing can also be violated if the event itself affects survey design (e.g., delaying fieldwork) or a participant's likelihood of responding. Another way the assumption can be violated is if there are pre-existing time trends that would have produced different average outcomes before or after the date of the event had it not actually occurred (e.g., if there is seasonality in recorded wellbeing). Further, the assumption can be violated if there are other events occurring simultaneously or there are collateral events, in which case the effect of the event itself cannot be identified or generalised to similar events that do not produce the same sequelae. Events like these are examples of 'fat-handed interventions' [@ref49] that involve a bundle of possible causes of an outcome, making it difficult to determine which aspects are operative.

Another usual assumption of the UESD is that the participants surveyed after the event were in fact exposed to the event (i.e., aware of it). There are several ways of assessing this, including indirectly: in the absence of a specific survey item on the event, analysts can use data sources such as Google Trends, contemporaneous polling, or news headline aggregators to assess the likelihood a person knew about the event. If exposure is less than 100%, any 'causal' estimate will be downward biased in inverse proportion to the extent of exposure. (This is equivalent to an *Intention to Treat* analysis, discussed further in [Section 5.9](05-09-instrumental-variables.qmd).) In practice, differences in awareness can be beneficial as an elaborate theory would predict weaker or non-existent associations in groups less likely to be exposed -- for instance, among those who do not read a newspaper or own a television [see @ref608, for an example in this vein].

The UESD design does not map onto a single statistical method, though it has clear similarities with the strict Regression Discontinuity Design (discussed further in [Section 5.10](05-10-regression-discontinuity-designs.qmd)). UESD analyses can proceed cross-sectionally, with responses compared in groups recorded before and after the event (potentially in subgroups for whom the assumption of random timing is more plausible, as discussed above). The longitudinal nature of CLS cohorts can also be exploited -- for instance, by performing fixed effects analysis to account for time-invariant confounders ([Section 5.5](05-05-longitudinal-fixed-effects.qmd)) or matching upon prior measurements of the outcome ([Section 5.2](05-02-matching.qmd)) to strengthen the plausibility that interview timing is independent of potential outcomes. Note, assumptions about random event timing can also be tested in part by (a) assessing covariate balance either side of the event and (b) assessing trends in the outcome variable in the period prior to the event occurring (i.e., to examine whether there were pre-existing time trends).

There are other natural experiments contained in CLS's cohort data, including those related to the timing of birth (e.g., influencing relative age in school year and the minimum age of school leaving), the rollout of public policies, and the nature of how systems distribute resources. There likely exist others that are as yet unidentified as uncovering these requires detailed knowledge of relevant policy areas (e.g., awareness about how social housing is allocated). Several natural experiments are analysed in Instrumental Variables or Regression Discontinuity Design (RDD) frameworks, for reasons that will be discussed in [Sections 5.9](05-09-instrumental-variables.qmd) and [5.10](05-10-regression-discontinuity-designs.qmd). It is worth noting, though, that some events may at first glance appear random but in fact are not. For instance, one may expect dying by murder or from accidents to reflect happenstance, but smokers have a higher chance of the former [@ref2051] and women using HRT have lower odds of the latter [@ref476].

## 5.8.2 Applications {#applications}

The UESD is relatively underutilised in CLS's cohorts. Two studies have used data from Next Steps to examine the effect of the 07 July 2005 London Bombings, which were followed by rises in reported hate crimes committed against Muslims [@ref220; @ref221]. Hole & Ratcliffe [-@ref221] show a specific decline in happiness (though not an increase in depression) among Muslim girls in the period after 07 July, as well as an increase in their expectation of discrimination in the labour market. Supporting a causal interpretation, the authors also show the effect is specific to Sweep 2 of Next Steps, during which the event happened, rather than also present in Sweep 4, when measures of mental health were again collected. Astorga-Rojas [-@ref220] uses a similar set-up and shows lower reported expectation to remain in full-time education after compulsory schooling among Muslim cohort members post 07 July.

Multiple papers have used data from individuals in social housing, exploiting the quasi-random nature of housing offers for those at the top of waiting lists at various times in the UK in the 20^th^ and 21^st^ centuries [@ref223; @ref222; @ref257]. For instance, Fumagalli & Fumagalli [-@ref223] use data from Next Steps and find lower social participation (operationalised as 'hanging around') in areas with greater ethnic diversity (which housing offers produce exogenous variation in). Note, a key issue with this design is that, although allocation to neighbourhood may be random, neighbourhoods vary on many different dimensions simultaneously. Though neighbourhood of residence may not be related to individual (baseline) characteristics among social housing tenants, it is not clear what aspect of neighbourhoods may be driving effects.

Several papers have used month of birth as a potentially exogenous determinant of relative age in one's school year -- in the UK, people born in September are the oldest in their class, whereas those born in August are usually the youngest, but parents have limited control over the time of year they conceive. Month of birth is often analysed in an RDD framework ([Section 5.10](05-10-regression-discontinuity-designs.qmd)) with data from multiple year groups pooled (e.g., comparing students born August or September in a given calendar year), but due to the design of CLS's cohorts, comparing individuals within a school year is the only feasible approach, and only for MCS and Next Steps (which roughly span one school year), rather than NCDS and BCS70 (which only span a single week).[^29] Crawford et al. [-@ref234] examine month of birth effects on multiple developmental outcomes in MCS and Next Steps cohort members, and show that, among other factors, cohort members born early in the school year have greater educational attainment and higher scores on cognitive tests than those born late in the school year.

## 5.8.3 Opportunities {#opportunities}

As noted, the UESD is relatively underutilised in CLS's cohorts, especially given the cumulative timespan of data collection represented. Several cohorts also contain data on accidents, though as discussed, the occurrence of accidents can be related to participant characteristics. Data on income and wealth shocks may also be available. We recommend reading the original UESD paper [@ref453] as it is filled with practical advice and may spark ideas. A research-enabling project would be to produce databases of (a) policies and headlines detailing important events that have occurred during CLS survey fieldwork and (b) interview date ranges and (sub)samples where interview timing is plausibly exogenous (identified, e.g., by assessing sample balance around an index date). Note, however, exogeneity of interview timing only needs to be met with respect to potential outcomes of interest -- there may be systematic reasons why individuals were interviewed on given dates, but if unrelated to potential outcomes, the assumption of (conditional) exchangeability would not be violated.

[^29]: Though cohort member's parents, siblings, and children have greater variation in dates of birth.
