# 5.5 (Longitudinal) Fixed Effects {#longitudinal-fixed-effects}

## 5.5.1 Method {#method}

Each of CLS's cohorts benefits from the tracking of the same individuals over the life course. [Section 4.3](04-attributes.qmd#longitudinal-assessment) described four advantages of longitudinal data for estimating causal effects: more accurate measurement, ability to establish temporal ordering, availability of baseline and lagged measures of exposures and outcomes, and the ability to use within- rather than between-person variation. This section focuses on methods that exploit within-unit variation.

Some confounders vary over time; others are time-invariant. Income, sex and country of birth may confound an association of interest, but income varies throughout life, while sex and birth country are fixed attributes of an individual. Utilising within-person variation fixes time-invariant confounders, accounting for their contribution to outcomes *by design* (Huntington-Klein, 2022); see [Figure 5.6](#figure-5-6) for a DAG. This is the idea behind the longitudinal *fixed effects* method. The approach can be understood as a form of matching ([Section 5.2](05-02-matching.qmd)), in which each observation is matched not to an observation from a similar individual but to other observations from the *same* individual, so that time-invariant characteristics are balanced exactly, whether or not they have been measured.

::: {#figure-5-6}

![**Figure 5.6:** DAG representing the fixed effect method with longitudinal data. X and Y are measured at two time points and their contemporaneous association is confounded by a time-variant factor, C~t=x~, and a time-invariant factor, U. Using within-variation effectively controls for person, which implicitly conditions on all time-invariant factors having constant effects.](images/image23.png){width="44%"}

:::

The equations below show the typical fixed effects set-up when used with longitudinal data. *i* and *t* index individuals and time periods, respectively. The outcome, $Y_{it}$, is related to an exposure of interest ($D_{it}$), time-variant confounders ($X_{it}$), and time-invariant confounders that can be aggregated into a single person-specific *fixed effect*, $u_{i}$. Person-specific means for each variable are indicated with the 'bar' accent (e.g., $\overline{Y_{i}} = \ \sum_{t = 1}^{T}Y_{it}$).

$$Y_{it} = \beta_{0} + \beta_{1} \cdot D_{it} + \beta_{K} \cdot X_{it} + u_{i} + \varepsilon_{it}\qquad \left[\varepsilon_{it}\ \sim\ N\left( 0,{\ \sigma}^{2} \right)\right]$$

$$\overline{Y_{i}} = \beta_{0} + \beta_{1} \cdot {\overline{D}}_{i} + \beta_{K} \cdot \overline{X_{i}} + \overline{\mu_{i}}\qquad \left[{\overline{\overline{u}}}_{i} = u_{i};{\overline{\overline{\varepsilon}}}_{i} = 0\right]$$

$$Y_{it} - \overline{Y_{i}} = \beta_{1} \cdot (D_{it} - \ {\overline{D}}_{i}) + \beta_{K} \cdot (X_{it} - \ \overline{X_{i}})\  + \varepsilon_{it}\qquad \left[\beta_{0} - \beta_{0} = 0;\overline{\mu_{i}} - u_{i} = 0\right]$$

In the usual implementation (performed automatically by statistical software), time-invariant confounding is accounted for by calculating person-specific means for each variable and subtracting these from observed values (the 'within' transformation). As time-invariant confounders are (by definition) fixed, the average is the same as the individual data points. Subtracting person-specific means therefore has the effect of implicitly removing the influence of these time-invariant factors (i.e., as $u_{i} - \overline{\mu_{i}} = 0$).[^21]

The advantage of the fixed effects method is that time-invariant confounders are accounted for without needing to measure them or even know what they are. It is not without limitations, however. Importantly, fixed effects do not account for time-varying confounding or reverse causality, which may be important sources of bias in a specific application. Fixed effects also do not account for the time-varying effects of time-invariant factors -- fixed characteristics like sex and birth country may not differ across life, but their importance can vary considerably over development. For instance, sex could have larger effects on outcomes post-puberty.[^22] This is less of an issue where the time span used is small, but CLS's cohorts extend decades, typically with several years between survey sweeps. The large gap can also mean few observations per individual, so person-specific averages can be overfitted.

Because it uses only within-person variation, the fixed effect method also cannot be used to assess the (time-invariant) effects of time-invariant variables, which may be of substantive interest. Additionally, only individuals whose exposure does in fact vary contribute to the estimated outcome-exposure association. Where treatment effects are heterogeneous, this can raise interpretational issues. Specifically, fixed effects estimates the change in an outcome accompanying a change in exposure between measurement occasions, averaged over individuals whose exposure changes during follow-up, and weighted towards those whose exposure varies most. For instance, fixed effects has been frequently used to examine the effect of unemployment on health (see, e.g., Schmitz, 2011) but this implicitly utilises data from people whose employment status changes (frequently), rather than those with unbroken (un)employment episodes. Moreover, where classical measurement error is an issue, focusing on within-variation makes the problem worse as a larger proportion of within-variation compared with between-variation will reflect noise rather than signal.

There are several other methods that address some of these limitations, which readers can delve into further by following the references. Random effects models capture person-specific time-invariant effects as random variables, but assume the random effects are independent of covariates, which may be unrealistic in practice (and is in fact a reason to use the fixed effects model in the first place). However, specific parameterisations of the random effects model (e.g., the within-between \[REWB\] model; Bell et al., 2019; Bell & Jones, 2015) can get round this limitation. Methods also exist to account for reverse causality and for serial correlation in the outcome variable (note, the absence of an arrow between Y~t=1~ and Y~t=2~ in [Figure 5.6](#figure-5-6)) -- specifically, dynamic panel data methods (Wooldridge, 2010) and the random intercept cross-lagged panel model (RI-CLPM; Hamaker et al., 2015) and its extensions (Mulder & Hamaker, 2021; Zyphur et al., 2019, 2020).

Longitudinal data are a type of hierarchical data -- observations are nested within individuals. The fixed effects method can be applied to other types of hierarchical data, too. For instance, Next Steps recruited multiple students from participating schools -- using variation within schools allows one to account for school-level confounders (see, e.g., Madia et al., 2022). Another important type of hierarchical data used frequently in the causal inference literature is sibships (Sjölander et al., 2022). Using sibling fixed effects controls for family-level confounders by design (discussed further in [Section 5.14](05-14-family-designs.qmd)). Note, fixing effects at one level also fixes characteristics at higher levels the units are nested within -- e.g., looking within schools also controls for local educational authority; looking within neighbourhoods also controls for town, region, and so on (Abdellaoui et al., 2022).

To best make use of fixed effects, researchers should consider at which level confounding is expected to occur. To give an (admittedly niche) example, Cinelli & Hazlett (2020), in their analysis of the causal effect on political beliefs of being a victim of violence during the Darfur war, note that once an army had reached a village, violence was likely largely indiscriminate and thus using data from multiple individuals within a village could achieve unconfoundedness. Similarly, Evans (1986) studies the effect of seatbelts on car crash fatalities using data from crashes where one occupant was belted and the other unbelted. This design controls for many pertinent shared factors (e.g., the speed the car was travelling at the time of crash, the road conditions, etc.), producing estimates that are likely less biased than comparing belted and unbelted individuals overall (Rosenbaum, 2019). The fixed effect design is an expression of what Zubizarreta et al. (2018, p. 16) term 'isolation': "Within a large but biased data system, isolation means constructing or finding a smaller set of comparisons that are likely to be much less biased". Nevertheless, this is situation specific, and it is also possible that within-unit variation is more confounded, not less, than the between-person variation, producing problems akin to Z-bias (discussed in [Section 5.1](05-01-control-via-regression-adjustment.qmd)).

## 5.5.2 Applications {#applications}

Scott (2022) uses BCS70 data to estimate the causal effect of university education upon political attitudes measured on multiple occasions between ages 16y and 42y. Using two-way fixed effects ([Section 5.6](05-06-difference-in-differences.qmd)) and REWB estimators he shows substantial within-person change in attitudes after graduation (compared to prior to enrolment). A key strength of the study is an explicit statement on the estimand and its causal aim.

Fitzsimons & Pongiglione (2019) use MCS to assess the effect of maternal employment on child BMI, showing children have higher BMI in periods in which their mothers are employed. Interestingly, no such within-person change is observed for paternal employment, though as the authors note, in the MCS sample, fathers' employment is more stable -- thus a different sample contributes to the estimated causal effect. Speyer et al. (2022) use RI-CLPM models to assess the effect of parenting behaviours on children's socioemotional development (as assessed by the Strengths and Difficulties Questionnaire) across early to mid-childhood (3y, 5y, and 7y), allowing for reverse causality. They show that harsh parenting practices (e.g., hitting) are followed by worse SDQ scores, and vice versa. The authors also perform Quantitative Bias Analysis to assess sensitivity to unobserved confounding.

## 5.5.3 Opportunities {#opportunities}

Given the extent of repeat measurement in CLS's cohorts, there are potentially many opportunities to use fixed effects methodology with the data. As discussed, a key issue, however, is the gap in age between data collections: time-invariant confounders may not have time-invariant effects over these periods. This can also be the case even when data collection is more frequent if this occurs over periods of substantial developmental change (e.g., MCS has five data collections to age 11y, but this spans early to mid-childhood and even initiation of puberty). Further, where one is using (e.g.) RI-CLPM and similar models to assess lagged effects, the gap in age may be implausible for the causal effect under study. For instance, one study that used MCS data to assess the effect of social media upon mental health relied upon 3-year gaps between data collections (Kelly et al., 2022). This would not capture effects that were more temporary.

[^21]: This is known as the within-estimator. It is also possible to account for $u_{i}$ by adding person-specific fixed effects (i.e., person dummies) to the regression model.

[^22]: Within person differencing does, however, account for the average effect of these time-invariant confounders.
