# 5.9 Instrumental Variables {#instrumental-variables}

## 5.9.1 Method {#method}

One issue with RCTs is that not everyone may comply with the intervention to which they have been assigned -- in a medical trial, some of the 'treated' may stop taking the drug they have been given, and some of the 'control' may find the drug through other means, instead of remaining on placebo. Analogously, in natural experiments not everyone may receive or follow their expected intervention. For instance:

1.  In the UESD, some people may be unaware of the event occurring, in extreme cases like the [reclusive Lykov family](https://www.smithsonianmag.com/history/this-russian-family-lived-alone-in-the-siberian-wilderness-for-40-years-unaware-of-world-war-ii-or-the-moon-landing-7354256/) or [Hiroo Onoda and other Japanese holdouts](https://www.bbc.co.uk/culture/article/20220413-onoda-the-man-who-hid-in-the-jungle-for-30-years), who were unaware of the end of World War II.

2.  In the Vietnam lottery, some draftees absconded, while some non-draftees signed up to serve.

3.  In maternity wards, some mothers breastfeed or don't regardless of whether advice from a midwife is received or not [@ref649].

Simply comparing outcomes by assignment (known as an *Intention to Treat* \[ITT\] analysis), while often useful in policy terms, will not necessarily identify the causal effect of the treatment itself. Individuals are typically only randomised to receive *encouragement* to follow a certain treatment, rather than to adopt the treatment, per se -- for instance, they are provided a box of medication and given instructions to take it, rather than administered it through force. To identify the causal effect of treatment, we instead need to look at those who *comply*.

This is not as simple as comparing outcomes among those who used the treatment because it is [not]{.underline} *use* of treatment that is randomised. For instance, if we compare, among those entered into the Vietnam lottery, those who served and those who didn't, we would compare on the one hand those who (1) served *because* they were drafted (*compliers*), (2) served because they would serve regardless of being drafted (*always takers*), or (3) served because they were *not* drafted (*non-compliers*) with, on the other hand, those who (a) did not serve *because* they weren't drafted (*compliers*), (b) did not serve despite being drafted (*never takers*), or (c) did not serve because they *were* drafted (*non-compliers*). These are not equivalent groups and they are not necessarily identical according to their potential outcomes. See [Table 5.5](#table-5-5), which continues this worked example.

::: {#table-5-5}

+-----------------------------------------+-------------------------------------------------------------------------------------+
| Group                                   | Activity                                                                            |
|                                         |                                                                                     |
| (X^Drafted^, X^Not\ Drafted^)           |                                                                                     |
|                                         +------------------------------------------+------------------------------------------+
|                                         | Serve                                    | Don't Serve                              |
|                                         +-------------------+----------------------+-------------------+----------------------+
|                                         | Potential Outcome | \# Enacting Activity | Potential Outcome | \# Enacting Activity |
+========================================:+:=================:+:====================:+:=================:+:====================:+
| Serve, Serve                            | 9                 | N                    | 7                 | 0                    |
|                                         |                   |                      |                   |                      |
| (Always Takers)                         |                   |                      |                   |                      |
+-----------------------------------------+-------------------+----------------------+-------------------+----------------------+
| Serve, Don't Serve (Compliers)          | 10                | N/2                  | 8                 | N/2                  |
+-----------------------------------------+-------------------+----------------------+-------------------+----------------------+
| Don't Serve, Don't Serve (Never Takers) | 5                 | 0                    | 3                 | N                    |
+-----------------------------------------+-------------------+----------------------+-------------------+----------------------+
| Don't Serve, Serve                      | 6                 | N/2                  | 4                 | N/2                  |
|                                         |                   |                      |                   |                      |
| (Non-compliers)                         |                   |                      |                   |                      |
+-----------------------------------------+-------------------+----------------------+-------------------+----------------------+
| E(Y \| X = x)                           | = (9⋅N + 10⋅N/2 + 5⋅0+6⋅N/2) / 2⋅N       | = (7⋅0 + 8⋅N/2 + 3⋅N+4⋅N/2) / 2⋅N        |
|                                         |                                          |                                          |
|                                         | = 8.5                                    | = 4.5                                    |
+-----------------------------------------+------------------------------------------+------------------------------------------+
| E(Y \| X = Serve) -- E(Y \| X = Don't Serve)                                       | = 8.5 -- 4.5 = 4                         |
+------------------------------------------------------------------------------------+------------------------------------------+

: **Table 5.5:** Numerical example showing that even with random assignment of treatment **encouragement**, comparing outcomes by treatment **used** can yield a biased estimate of the causal effect if there is non-compliance (i.e., not all individuals use the treatment they were assigned to). The example uses the Vietnam draft lottery where people either serve or don't serve (treatment used), depending on whether they are drafted or not drafted (encouragement assigned). People can be split into four groups depending on how they behave based on treatment assignment. For simplicity we assume that people are equally split across these four groups to make the arithmetic simpler to follow. For each group, the causal effect of serving is 2 (to verify, compare 'Potential Outcome' columns). However, people who choose to serve when drafted have higher potential outcomes than those who do not. The difference in observed outcomes among those who serve and those who don't is 4 (final two rows) rather than 2, a biased estimate.

:::

Accounting for non-compliance in the estimation of causal effects can instead be achieved using the Instrumental Variable (IV) design ([Figure 5.10a](#figure-5-10)). This design utilises variables that create -- or are associated with [@ref21021] -- exogenous variation in treatment, nudging subjects to a particular level of the exposure, rather than another, analogous to the role of a coin in an RCT. For instance, being picked in the Vietnam draft raised the probability a person would serve, but did not make it inevitable, while giving birth on a weekday makes it more likely, but by no means certain, that a mother will breastfeed.

::: {#figure-5-10}

![**Figure 5.10:** DAG representing the instrumental variable design. The instrument Z is an exogenous cause of variation in the exposure, X, and can thus be used to determine the effect of X upon Y (at least, for the variation induced in X by Z). The instrument meets three criteria: relevance (Z → X), exclusion restriction (Z → X → Y is the only directed path from Z to Y), and (conditional) independence -- i.e., no open backdoor path from Z to Y. In (b), conditional exchangeability is achieved by controlling for the confounder U~1~.](images/image27.png){width="68%"}

:::

In addition to meeting the assumptions of positivity, consistency and no interference, to be valid, an instrumental variable must have four properties [@ref21021]. First, it must be associated with exposure (*relevance*; Z → X in [Figure 5.10a](#figure-5-10)). Second, it must be unrelated to any unmeasured confounders of the exposure-outcome relationship (*independence*; no Z ← U → Y). Third, it must be independent of the outcome conditional on the treatment and unmeasured confounders (*exclusion restriction*; Z → X → Y, the only directed path from Z to Y), unless these are conditioned upon ([Figure 5.10b](#figure-5-10)); the lottery used in the Vietnam War draft is an instrumental variable but only among males eligible to serve.[^30] Fourth, the size of the treatment effect must be independent of the instrument (*homogeneity*) *or*, where there is effect heterogeneity, there cannot be both compliers (people who use treatment only when encouraged) and defiers (people who use treatment only when *discouraged*) within the same study population (*monotonicity*).[^31]

Under these assumptions, it is possible to use estimates of the association between the instrument and the exposure and the instrument and the outcome (in [Figure 5.10](#figure-5-10), paths Z → X and Z → X → Y, respectively) to obtain an estimate of the causal effect of the exposure upon the outcome (X → Y); in effect, exploiting exogenous variation in the exposure related to the IV (Z → X). Several IV estimators exist. The most commonly used, two-stage least squares regression (IV-2SLS), uses the instrument to predict the exposure variable, and then uses these predicted values to estimate associations with the outcome variable. Unlike ITT analysis, this procedure provides an estimate of the change in the outcome per unit change in the exposure. Similarly, the widely used Wald estimator scales the association between the instrument and the outcome by the instrument's association with the exposure.

Where there is treatment effect heterogeneity and the monotonicity assumption is met, IV methods estimate a specific quantity termed the Local Average Treatment Effect (LATE). This is the average effect of the exposure within the variation induced by the instrumental variable, i.e., among *compliers* -- people whose level of the exposure is sensitive to (changes according to) the level of the instrument (for instance, those who served in the Vietnam War only because they were drafted). The LATE, which is sometimes referred to as the Complier Average Causal Effect (CACE), can differ from a global average treatment effect because causal effects may be heterogeneous according to why someone was exposed. For instance, the effect of military service on income among those who only served due to the draft could be different to those who served voluntarily (especially if the latter did so in expectation of serving's beneficial effect on their outcomes).

Discrepancies between observational associations and IV estimates may therefore arise not just because of bias in the observational association, but also because a different quantity is being estimated. It is generally not possible to identify which individuals are compliers because the 'fundamental problem of causal inference' [@ref284] reappears: we cannot see both states of the world, where a person receives the instrument and doesn't. However, characteristics of the population of compliers can be observed (assuming monotonicity) by comparing the attributes of the exposed among those with the instrument and those without. Nevertheless, this population may not be of particular scientific or policy interest; we may wish to know the effect of military service on recruits in general, for example. The price of internal validity is potentially lower external validity.

Where treatment effects are heterogeneous, monotonicity is required because, otherwise, the total effect of the instrument on the exposure becomes a net combination of opposite responses, making the resulting instrumental variable estimate difficult to interpret [for worked examples demonstrating this, see @ref451; @ref452]. IV methods can exploit multiple IVs, which can increase statistical power and precision, but make interpretation more challenging where treatment effects are heterogeneous as the estimated treatment effect is then an average across different groups. Additionally, where the exposure is continuous, rather than binary, the LATE is a weighted average where compliers are weighted in proportion to how affected they are by the IV (i.e., those whose exposure changes the most are weighted more highly), again making interpretation challenging.

Many instruments have been proposed and used in the empirical literature, particularly in economics. Examples include [@ref21022; @ref451; @ref826; @ref452; @ref219]:

- Having a girl as a first birth (due to a preference for boys, a first-born girl means a family is more likely to have further children)

- Measures of access (e.g., distance to hospitals, as travel time provides an incentive to use the nearest service, regardless of its quality)

- Preferences (e.g., the judge fixed effects design relies on random allocation to judges who have different predilections to handing out long prison sentences)

- Weather (e.g., extreme weather events can mean, among other things, planned events are disbanded)

- Calendar time (e.g., the roll-out of cable networks in the US)

- Offspring traits [e.g., direct effects of genes that are shared between parents and offspring lead to correlation in parent-offspring pairs, and the offspring trait may be less confounded than the parent trait\; @ref21071]

However, the popularity of these IVs can itself be a cause for concern [@ref218; @ref219]. For instance, weather has been linked with over 190 treatment variables, such as income and food prices, through which it may plausibly affect outcomes [@ref219]. Such disparate effects suggest exclusion restrictions do not hold, though Mellon [-@ref219] discusses conditions under which this may not be the case (e.g., the exclusion restriction holds for the specific population under study), as well as outlining a procedure for determining whether this matters for a planned IV study.

Note, IV estimates can be especially sensitive to violations of assumptions [@ref826], in particular where the instruments are 'weak' [have small associations with the exposure\; @ref21065]. Baiocchi et al. [-@ref21022] and Cinelli & Hazlett [-@ref20907] describe quantitative bias analysis methods for IV designs.

Another class of IVs that are routinely used are genetic variants -- i.e., as in Mendelian Randomisation (MR) analysis. (Almost) every human trait is heritable [@ref685; @ref1238]. Mendelian inheritance means parents pass on a random half of their genomes to their children, and thus, conditional on parents' genomes, a child's genes potentially represent a source of exogenous variation in a trait. For instance, variants of the ALDH2 gene are related to the comfort with which one metabolises alcohol and have thus been used to instrument alcohol consumption and determine its effect upon health [@ref136], a canonical example of a difficult question to answer with standard observational data. An advantage of using genetic variants as instruments is that they are inherited at conception and so are not subject to reverse causality. However, this also comes with the disadvantage that genes are carried across life and so it is difficult to determine or isolate specific timing of exposure [though, see @ref5409].

Due to data unavailability, MR analyses are generally undertaken without genetic data from multiple family members and therefore cannot condition on family and so do not necessarily have the characteristics motivating MR. (MR with family-level data is discussed further in [Section 5.14](05-14-family-designs.qmd).) Genetic variants are not randomly distributed around the population [@ref39; @ref812], and population-level MR analysis can be biased by (population) genetic phenomena, including population stratification and assortative mating, as well as genetic nurture (effects of parental genes on offspring via parental behaviour) and other indirect genetic effects. Population stratification refers to differences in particular genes across groups, which can lead to (non-causal) association between genes and environments -- famously, genes that are more prevalent among individuals of East Asian ancestry will be associated with chopstick use, despite this having a cultural explanation [@ref424]. Assortative mating refers to the phenomenon of individuals not mating randomly, which can lead to associations between phenotypes (and thus the genetic variants they are influenced by) without one phenotype having a causal effect upon another. For instance, if highly educated people are more likely to mate with taller individuals, then genes that influence either will become correlated and a population MR analysis would suggest education influences height (or vice versa) when this is not the case. Both population stratification and assortative mating represent violations of the *independence* assumption.

An additional issue with MR analyses (including those using family-level data) is *horizontal pleiotropy,* where a genetic variant has an effect on multiple phenotypes, not due to the main trait of interest having an effect on the others (*vertical* pleiotropy): many genes have effects on multiple phenotypes, a necessary consequence of the limited number of protein-coding genes (\~20,000) in the human genome. Horizontal pleiotropy represents a potential violation of the exclusion restriction assumption. Horizontal pleiotropy can also arise through *linkage disequilibrium* (LD), whereby variants located close together on a chromosome are correlated because recombination of DNA during meiosis (formation of sex cells, gametes) rarely separates nearby loci, so DNA is inherited in blocks. Thus, a genetic variant which has a causal effect on one trait may be in LD with a variant that has an effect on another trait, creating a correlation between the two traits.

The risk of horizontal pleiotropy is heightened when polygenic scores (PGS) are used as instruments. PGS aggregate the effect of many genes (e.g., hundreds or more) into a single weighted summary variable, with the individual weights determined from Genome-Wide Association Studies, which use a hypothesis-free approach. Unlike with single genetic variants like ALDH2, the pathways linking PGS to a trait may thus be poorly understood. This is a particular concern when studying complex traits, such as education, that are genetically influenced through multiple other traits (e.g., cognitive ability, conscientiousness, and physical health), which may themselves have independent effects on outcomes. As individual genes often have only weak effects, there is a trade-off between using genetic instruments that most plausibly satisfy the exclusion restriction (and independence) assumptions and using instruments that are well-powered. Researchers often strike a balance by using PGS created from the top 'hits' in a GWAS (e.g., variants exceeding the genome-wide significance, p \<= 5x10^-08^, level). Multivariable MR, in which PGS for related traits are also used [@ref1130], may also reduce bias in this situation. PGS also raise difficulty for meeting the *consistency* assumption.

Note, however, whether population stratification, assortative mating, or horizontal pleiotropy matter in a particular MR application is an empirical question -- some traits are not subject to assortative mating, nor do some genes vary in prevalence in important ways across populations, and horizontal pleiotropy may not be relevant in a specific situation. Further, as discussed in [Section 5.16](05-16-cross-context-analysis.qmd), clever cross-context designs may be used to elaborate the theory that the gene has an exogenous effect on the exposure and provide compelling causal evidence.

## 5.9.2 Applications {#applications}

Fitzsimons & Vera-Hernández [-@ref649] use data from the MCS to assess the effects of breastfeeding on various measures of child development using time of birth and day of birth as instruments for the likelihood that someone received breastfeeding support in hospital. Major strengths of their study are their ability to demonstrate that day of birth was not related to mothers', babies' and pregnancy characteristics and that associations were confined to low-SES individuals for whom breastfeeding support was particularly likely to have an effect on breastfeeding rates. Further, the authors augment their analysis using an external dataset containing detailed data on postnatal care to demonstrate that the relevance assumption is plausible (e.g., that day of birth is related to receiving advice and active support with breastfeeding).

Hyppönen et al. [-@ref21073] use data from parents in the NCDS to assess the effect of BMI upon mortality using cohort members' (i.e., offspring) BMI as an instrumental variable; the authors' argument is that offspring BMI is unlikely to be confounded by underlying disease, a major confounder of the BMI-mortality association in observational studies [i.e., reverse causality\; @ref21071]. The authors find that associations between BMI and mortality are stronger when using the IV. However, they find evidence that offspring BMI is confounded by socioeconomic position [confounding bias can be amplified when using IVs\; @ref21065]. It is also possible the exclusion restriction is violated if, e.g., offspring socioeconomic position (which could have a causal effect on offspring BMI) affects parental mortality. Further, because the instrument captures the stable familial component of BMI, the analysis disregards temporary variation in parental BMI, and so estimates target the effect of long-run -- rather than contemporaneous -- adiposity.

## 5.9.3 Opportunities {#opportunities}

The temporal and geographical range of the CLS cohorts, as well as linkage with admin data, potentially opens up many opportunities for novel instrumental variable analyses. However, the discovery of plausible IVs depends on deep domain-specific knowledge. Given the wide range of data that are available in the cohorts, there may be a case for extending previous successful IV applications -- e.g., to extend the Fitzsimons & Vera-Hernández [-@ref649] work to outcomes captured later in life (e.g., educational attainment) or other domains (e.g., to personality traits); though whether IV assumptions are met for these additional outcomes would need to be examined. Data on offspring and/or parents are available in each cohort and can enable IV analyses using family members' traits. However, again, whether the IV assumptions are met will need to be assessed for the exposure and outcome under study. Finally, PGS for a wide range of traits are now available in each cohort [@ref217] and could be used in MR analyses. For researchers wishing to exploit single genetic variants, raw genetic data can be accessed via application to CLS.

[^30]: Typically, and as displayed in [Figure 5.10](#figure-5-10), the three IV assumptions are stated referring to causal effects rather than (conditional) associations. For instance, relevance is defined as the IV having a causal effect on the exposure and exclusion restriction as the IV not having causal effects on outcomes except via the exposure, X. In the causal framing, not conditioning on U~1~ in [Figure 5.10b](#figure-5-10) may be classified as a violation of independence (i.e., presence of open back-door paths) rather than exclusion restriction as above. In the causal framing, selection paths (e.g., adding Z → S ← Y to [Figure 5.10b](#figure-5-10)) do not fall easily under any assumption's definition, whereas they sit straightforwardly under exclusion restriction as the assumptions are defined above.

[^31]: There are various (relatively technical) versions of the homogeneity assumption. See Goetghebeur et al. [-@ref21021] and Hernán & Robins [-@ref826] for more detail.
