# 5.1 Control via Regression Adjustment {#control-via-regression-adjustment}

## 5.1.1 Method {#method}

The most common method for accounting for confounding bias is by taking a model-based approach and controlling for confounders or other nuisance factors via regression adjustment -- for example, by adding covariates to an ordinary least squares (OLS) regression model. The data-generating process is modelled mathematically, with elements of the model (e.g., regression coefficients) learned from the data itself (Rosenbaum & Rubin, 1983). Statistical adjustment models the effect of relevant differences between treatment and comparison groups to block backdoor or other nuisance paths between exposure and outcomes, isolating variation in the exposure and outcome unrelated to these (observed) confounders.

This description is not just poetically true but reflects the underlying mechanics. The Frisch-Waugh-Lovell theorem demonstrates that the coefficient obtained by multivariable regression of an outcome upon an exposure plus covariates is equivalent to (1) obtaining residuals from regressions of (a) the exposure on covariates and (b) the outcome on covariates and then (2) regressing the residuals from (b) upon (a). In other words, statistical control winnows, and then utilises, residual variation. Readers can confirm this in R or Stata using the below code.

\# Stata Code

sysuse auto, clear

regress price mpg length foreign // full model

regress mpg length foreign

predict mpg_resid, residuals

regress price length foreign

predict price_resid, residuals

regress price_resid mpg_resid

\# R Code

data(iris)

lm(Sepal.Length \~ Sepal.Width + Petal.Length + Species, iris) \# full model

width_mod \<- lm(Sepal.Width \~ Petal.Length + Species, iris)

length_mod \<- lm(Sepal.Length \~ Petal.Length + Species, iris)

lm(residuals(length_mod) \~ residuals(width_mod))

Statistical control is an example of a 'non-equivalent groups design': the analyst starts with groups expected to differ systematically but attempts to model the effect of these differences on the outcome in order to remove them. Nick Huntington-Klein (2022, p. 469) evocatively likens methods like this to creating a statue by taking a large block of marble and chipping away until the desired form is revealed underneath. Where successful -- i.e., using a suitably accurate model, possibly reflecting an appropriate DAG -- a valid causal estimate can be obtained. However, validity cannot be ascertained directly. Unlike a sculptor, the data analyst cannot say whether the finished product looks quite right. They do not know if they are left with Michelangelo's *David* or [Emanuel Santos' bust of Cristiano Ronaldo](https://web.archive.org/web/20180618225849/https:/www.bbc.com/sport/football/44518595).

Not including a sufficient adjustment set in the statistical model leaves open backdoor or other biasing paths between exposure and outcome variables and will generate a biased estimate of the causal effect. The size of the bias will equal the (aggregate) strength of the biasing paths. For confounding paths, it will reflect the strength of the associations between the confounders and the exposure and between the confounders and the outcome. Adding too many covariates -- the Causal Salad 'approach' (McElreath, 2020) -- can also bias estimates where covariates serve as colliders or mediators of the effect of the exposure upon the outcome (the latter where an estimate of the total causal effect is sought). The statistical adjustment approach will also obtain a biased estimate if confounders are not modelled appropriately or measured accurately. Simple models with variables incorporated as linear terms without interactions or other non-linearities (e.g., absence of required polynomial terms) may not reveal suitable residual variation.

Theory may not be sufficiently strong to clarify the correct functional form *a priori*, which limits standard regression algorithms like OLS, where the functional form requires explicit parameterisation. On the other hand, machine-learning and deep-learning algorithms, such as the random forest and neural networks, are capable of modelling non-linearities without their express inclusion in a model. The Frisch-Waugh-Lovell theorem has motivated the development of other methods, notably the double machine learning method (Chernozhukov et al., 2018), where machine-learning algorithms are used to obtain residuals for exposures and outcomes, increasing the plausibility that data-generating processes have been modelled correctly. Still, ever more complicated algorithms cannot use data that aren't there; bias via backdoor paths (and incorrectly closed front-door paths or conditioned colliders) is still a fundamental issue regardless of the method used for statistical control.

::: {#figure-5-1}

![**Figure 5.1:** DAGs showing situations where controlling for a variable may increase or decrease bias. In (a), conditioning on Z closes the path X ← U~1~ → Z → Y but opens the path X ← U~1~ → Z ← U~2~ → Y (Source: Cinelli, Forney, et al., 2024). (b) represents a situation where there are mode effects and mode selection (Section 2.2.5). Conditioning on M (mode) closes the path X → M → Y\* representing differential measurement but opens the path X → M ← Y → Y\*. Tomova et al. (2026b) use simulations to explore the conditions in which this would increase bias.](images/image18.png){width="69%"}

:::

Though non-parametric in nature, DAGs can help identify control variables that are sufficient to identify causal effects: the software DAGitty (2025) can be used to programmatically identify minimal sufficient adjustment sets or biasing pathways, while Cinelli et al. (2024) provide a "crash course" with example DAGs showing where adjustment would reduce, increase or leave bias unchanged.[^14] There are also situations where controlling for a variable could go either way; [Figure 5.1](#figure-5-1) shows two DAGs where control closes one path but opens another due to the variable operating as a collider ('damned if you do, damned if you don't'; Cinelli, Forney, et al., 2024; Tomova, Silverwood, Tennant, et al., 2026; Woolf et al., 2023). Whether bias would be reduced is an empirical question and depends on the relative strength of the paths in question; judgements about this benefit from domain expertise. Regardless, adjustment sets will only be valid in so far as the assumptions encoded in the DAG (e.g., the set of variables, causal arrows, and their direction) are valid, too. Though some assumptions in a DAG may be testable empirically (i.e., implied \[conditional\] independencies), ultimately not all can be -- e.g., there is no statistical way to identify the correct direction of an arrow between two adjacent variables, measured at the same moment in time.

VanderWeele (2019) offers principles for selecting confounders when knowledge of underlying causal structures is incomplete or uncertain. Specifically, he recommends, with two caveats, conditioning upon any pre-exposure covariate that is a cause of the exposure or the outcome or both. This 'disjunctive cause criterion' avoids issues that can arise if simply controlling for any pre-treatment variable (i.e., M-bias) or insisting confounders must be common causes of both exposure and outcome (which can miss variables that are valid controls); see [Figure 5.2](#figure-5-2) below.

::: {#figure-5-2}

![**Figure 5.2:** DAGs showing bias that can arise when (a) controlling for any pre-treatment variable or (b) controlling for a variable only if it is available and is a common cause of both exposure and outcome. In (a) and (b) variables U are not observed. In (a), conditioning upon C opens a bias path from X to Y via C (X ← U~2~→ C ← U~1~ → Y; i.e., M-bias). In (b), **not** conditioning upon C keeps the biasing path X ← C ← U → Y open, though it could be closed.](images/image19.png){width="100%"}

:::

VanderWeele's first caveat to this rule is that analysts should not control for any instrumental variable ([Section 5.9](05-09-instrumental-variables.qmd)) -- that is, a variable which is only related to the outcome via its effect on the exposure -- as this can generate 'Z-bias' where the bias from an unconditioned common cause of exposure and outcome is amplified by adjustment for an instrument (Ding et al., 2017). This is because controlling for the instrument removes a source of variation in the exposure that was unbiased, meaning a greater proportion of the variation that is left will represent bias or measurement error.[^15] VanderWeele's second caveat is that analysts should also consider conditioning on 'proxy confounders' -- variables that explain sufficient variation in true confounders, such that they can be used instead of them, for example when the confounders themselves are not available or are poorly measured. These proxy confounders can be thought of as imperfect measurements of the true confounders. However, a drawback of including these is that there may also exist an unobserved common cause of the proxy confounder and the outcome, which could then create M-bias if the proxy confounder is conditioned upon. This would be the case if C were considered a proxy confounder for U~2~ in [Figure 5.2a](#figure-5-2) above.

VanderWeele (2019) also discusses issues that can arise when covariates and exposures are measured simultaneously as it is possible that covariates are in fact mediators rather than confounders -- for instance, conditioning upon cognitive ability when trying to estimate the causal effect of educational attainment as this is a consequence of education, as well as a cause (Ritchie & Tucker-Drob, 2018; Strenze, 2007). A key benefit of CLS's cohorts is that multiple sweeps of data are available which include repeated measurement, so it is usually possible to find measurements for confounders from prior to the measurement of the exposure (as well as to find measurements of the exposure prior to the outcome), thereby respecting temporality. Additionally, it may also be possible to control for lagged measurements of exposures and/or outcomes (VanderWeele et al., 2020), which can again reduce bias, particularly where time-invariant confounders exist or there are confounders that have effects on exposure and outcome at multiple time points. Note, controlling for earlier exposures more specifically links the study estimate (exposure to treatment at a specific time point) to a specific intervention and to the randomised controlled trial design; we discuss this further in [Section 5.11](05-11-target-trial-emulation.qmd). However, one issue is that the time between adjacent sweeps can be quite long (e.g., a nine-year gap between the Age 33 year and 42 year NCDS sweeps), so control may be imperfect when this strategy is used.

Less abstractly, VanderWeele et al. (2020) provide a list of variables they suggest should be considered for inclusion as covariates in regression models, given these represent confounders of many different associations in the health and social sciences.[^16] Ideally these should be measured prior to exposure and outcome, or otherwise with consideration to the possibilities these mediate rather than confound associations (see [Table 5.1](#table-5-1)). Most or all of these variables are available in each of CLS's cohorts.

::: {#table-5-1}

+-----------------------------------+-----------------------------------+
| Domain                            | Covariate                         |
+===================================+===================================+
| Demographic                       | Race                              |
|                                   |                                   |
|                                   | Age                               |
|                                   |                                   |
|                                   | Gender                            |
|                                   |                                   |
|                                   | Marital Status                    |
+-----------------------------------+-----------------------------------+
| Economic, Social and Political    | Income                            |
|                                   |                                   |
|                                   | Education                         |
|                                   |                                   |
|                                   | Employment                        |
|                                   |                                   |
|                                   | Social integration                |
|                                   |                                   |
|                                   | Neighbourhood                     |
|                                   |                                   |
|                                   | Religious service attendance      |
|                                   |                                   |
|                                   | Political affiliation             |
+-----------------------------------+-----------------------------------+
| Health                            | Self-rated health                 |
|                                   |                                   |
|                                   | Number of health conditions       |
|                                   |                                   |
|                                   | Exercise                          |
|                                   |                                   |
|                                   | Smoking                           |
|                                   |                                   |
|                                   | Alcohol consumption               |
|                                   |                                   |
|                                   | Depression                        |
+-----------------------------------+-----------------------------------+
| Psychological                     | Happiness                         |
|                                   |                                   |
|                                   | Loneliness                        |
|                                   |                                   |
|                                   | Parental warmth                   |
|                                   |                                   |
|                                   | Purpose/Meaning                   |
|                                   |                                   |
|                                   | Big five personality              |
+-----------------------------------+-----------------------------------+

: **Table 5.1:** List of confounders to include in regression models recommended by VanderWeele et al. (2020).

:::

## 5.1.2 Applications {#applications}

There are thousands of papers using CLS data that have used the statistical adjustment approach. A particularly rigorous example of statistical control is Purba et al. (2025), who use data from MCS to assess the effect of time spent on social media on cigarette and e-cigarette use. The authors based their (pre-registered) analysis upon a DAG developed from subject knowledge, existing evidence, and input from a policy advisory group, from which they identified a minimally sufficient adjustment set for their analysis. A further virtue, though not related to reducing bias via regression adjustment, is that the authors also elected to use a more reliable time-diary-based measure of social media use rather than other available measures, reducing measurement error.

## 5.1.3 Opportunities {#opportunities}

The regression adjustment approach is straightforward to implement and particularly suited to CLS's cohort data given the amount and variety of data available on participants, including their individual characteristics and the characteristics of their backgrounds, families and localities in which they live. Control can be made for many common and important confounders, such as sex, ethnicity, psychological traits, and lifetime socioeconomic position. While not all confounders may be available, nor all confounders known, the ability to incorporate additional plausible confounders may still improve upon existing work; bias may not be fully ameliorated but at least reduced. The statistical adjustment approach may also be beneficial when treated as a data point within a broader literature -- where remaining bias is unrelated to biases hampering other studies, particularly those using different study designs, consistency of results across studies ("triangulation") makes a causal interpretation more plausible (Lawlor et al., 2016). Additionally, as will be discussed further in [Section 5.20](05-20-quantitative-bias-analysis.qmd) on Quantitative Bias Analysis, information on important confounders can be used to calibrate expectations about whether remaining confounders are sufficient to explain observed associations.

[^14]: Control for some variables does not reduce bias, but by reducing residual variation, increases statistical power and the precision of estimates.

[^15]: This is also known as 'bias amplification'. Bias amplification can occur even if the confounder is a weak cause of the outcome because, again, once conditioned upon, the residual variation in the exposure may be more confounded than before. Similar logic also applies to sibship studies and other fixed effects designs as discussed in [Sections 5.5](05-05-longitudinal-fixed-effects.qmd) and [5.14](05-14-family-designs.qmd).

[^16]: In [Section 8.2](08-appendix.qmd#why-does-correlation-often-not-equal-causation) (Appendix), we also offer some general theoretical perspectives on confounding processes.
