# 5.7 Study-Initiated Experiments {#study-initiated-experiments}

## 5.7.1 Method {#method}

Several of CLS's cohorts have embedded randomised experiments to test the effect of different survey methodologies on participation rates or measurement. We discuss these experiments here as we believe they are underutilised presently. That said, the material is somewhat out of keeping with the rest of this document as it is not focused on making causal inferences with observational data. This section can therefore be safely skipped if it is not of interest. Note, experiments have their own methodological considerations which interested readers will need to explore if opting to analyse the data.

Many of the experiments in CLS's cohorts have only been implemented in small pilot studies and used to inform ongoing data collection, but some have been implemented among a plurality of cohort members. Almost all have appeared in recent sweeps as the studies have become more complex and as survey technologies have developed. Below is a brief overview of experiments in CLS's cohorts that we are aware of. Further details can be found in academic publications (see next subsection) or sweep-specific technical reports.

::: {#table-5-4}

  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  **Experiment**                                                     **Description**
  ------------------------------------------------------------------ ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  NCDS Age 55y (Sweep 9) Mixed-Mode Survey Experiment                Cohort members with a known UK telephone number (n = 10,558) were randomised to telephone-only (n = 1,499) or a web-then-telephone sequential mixed-mode design (n = 9,059).

  BCS70 Age 42y (Sweep 9) Targeted Interviewer Experiment            A set of cohort members who had refused prior surveys (n = 1,009) were randomly allocated to 'high performer' interviewers known to achieve high response rates or to other interviewers.

  Next Steps Age 25y (Sweep 8) Early-Bird Web Incentive Experiment   Participants in a soft launch sample (n = 2,215) were given £10 to complete the survey which, for half the sample, increased to £20 if the survey was completed within three weeks of invite and via web questionnaire.

  Next Steps Age 25y (Sweep 8) Progress Bar Experiment               Participants responding via web were randomised to see a progress bar or not while completing the questionnaire, though an error in coding meant no participants early in fieldwork saw the progress bar. The experiment was originally intended to be run only during the soft launch but continued when there was no clear evidence of effects on completion rates; such results-driven decisions can increase the risk of false positives (Simmons et al., 2011).

  Next Steps Age 32y (Sweep 9) Differential Incentive Experiment     Participants in a soft launch sample (n = 3,206) were given a tapered incentive, which for some participants was dependent on their response at the Age 25y sweep. In one trial arm, Age 25y non-respondents were offered £35 to complete the Age 32y survey (£25 after the first three weeks) while respondents were offered £25 (£15 after the first three weeks). In the other arm, a single tapered incentive was used (£30, dropping to £20 after the first three weeks). Offering a greater incentive to non-respondents did not boost participation rates, so the single tapered incentive was used post-soft launch.

  Next Steps Age 32y (Sweep 9) Interview Length Experiment           Non-respondents from a soft launch sample (n = 1,337) were randomised to be invited to complete either a short or long version of a mop-up web questionnaire. As the short version was more successful at boosting response, it was used for (post-soft launch) non-responding cohort members.

  MCS Age 9m (Sweep 1) Health Records Experiment                     In the sweep dress rehearsal, parents of cohort members were randomised to be asked to give consent for either (a) the interviewer to copy information from the cohort member's Personal Child Health Record (Red Book) or (b) for routinely collected health data to be linked to survey responses.

  MCS Age 7y (Sweep 4) Refusal Experiment                            Refusals at this sweep were randomised to one of four groups in a 2x2 design where (a) cohort members' families were sent or not sent a leaflet encouraging a response and (b) all refusing families were reissued or only those judged to be soft or circumstantial refusals were reissued.

  MCS Ages 7y-11y (Sweeps 4-5) Between-Sweep Mailout Experiment      In 2010, cohort families (n = 15,653) were sent letters requesting contact information. Families were randomised to receive letters that used formal or informal and simpler language, the latter also being signed by the cohort maintenance officer, rather than the study Principal Investigator.

  MCS Age 11y (Sweep 5) Interviewer Pay Experiment                   For cohort families in the first wave of fieldwork, interviewers were randomised to receive a bonus fee for successful interview or not.

  MCS Age 23y (Sweep 8) Mixed Mode Survey Experiment                 Cohort members in the soft launch sample were randomised to face-to-face interview-only or a web-then-face-to-face sequential mixed-mode design.

  MCS COVID-19 Wave 3 Survey Incentive Experiment                    Cohort members were randomised to receive a £10 incentive for successful completion of the survey or no financial incentive whatsoever.
  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

: **Table 5.4:** Experiments in CLS's Cohort Studies.

:::

An important feature of these experiments is that the interventions implemented could have effects on both response rates and measurement. For instance, offering a web questionnaire in a sequential mixed-mode design can incentivise more cohort members to respond (Goodman et al., 2022), but it may also affect data quality if, for instance, lack of interviewer presence in the web mode leads to more hurried interview completion. Given that measurements are only taken from cohort members who choose to participate, simple comparisons of observations across experimental arms may be biased due to implicitly conditioning on participation, a collider variable (Figure 5.8).

::: {#figure-5-8}

![**Figure 5.8:** DAG representing an RCT of a survey mode experiment (X → M) where mode (M) influences measurement (M → Y\*) and (assigned) mode (X) influences response rates (X → S). Unbiasedly estimating the mode measurement effect (M → Y\*) is not possible with the observed data due to measurements only being observed for individuals who participated (M ← X → S ← Y → Y\*). See Section 2.2 for further discussion of mode effects.](images/image25.png){width="42%"}

:::

The differential non-response this implies should be accounted for in statistical analysis. Potentially suitable methods include multiple imputation (Section 5.4) and/or quantitative bias analysis (Section 5.20). Bias from differential non-response may be detected by examining the distribution of baseline covariates in each experimental arm or using *negative controls* (variables unlikely to be impacted by the experimental treatment; Section 5.15) as alternate outcome variables. In practice, absolute differences in response rates may be small, limiting the size of the bias arising from selection.

## 5.7.2 Applications {#applications}

Several studies have used data from experiments in Table 5.4. Goodman et al. (2022) used data from the NCDS Age 55y mixed-mode experiment in which eligible cohort members were randomised to telephone-only or sequential mixed-mode (web-then-telephone) survey designs, in order to estimate effects of survey mode (telephone interview vs. web questionnaire) upon item and sweep non-response rates and measured responses (e.g., on socioeconomic status, health behaviours, and physical and mental health). Sweep response rates were higher for cohort members in the sequential mixed-mode arm, and there were differences across arms in reported values for several socially valent characteristics such as mental health and alcohol consumption (the web survey was entirely anonymous, unlike the telephone survey). Given the (small) difference in response rates by mode, missing values for non-respondents were imputed via multiple imputation under the Missing at Random assumption. As 'treated' participants were randomised to the web-then-telephone sequential mixed-mode design, rather than to web specifically, treatment group was used as an instrumental variable (Section 5.9) to obtain a 'complier average causal effect' (CACE) -- here, the average causal effect of web participation (relative to telephone response) among those who 'complied', i.e., responded via web instead of telephone when offered. Among other things, this analysis assumes that assignment to mixed-mode itself did not influence measured responses among those who instead responded via telephone.

Calderwood (2014) examined the effectiveness of a redesigned letter sent to MCS participants between waves to minimise loss to follow-up. She found that cohort families sent the redesigned letter were more likely to return the completed forms early, including among non-English-speaking families and families with parents who had no qualifications, subpopulations for whom effects were expected to be greatest. However, longer-term effects on returning of forms were more muted. Booth et al. (2024) investigated the effect of a monetary incentive given to MCS participants to complete a COVID-19 survey -- the incentive was associated with both increased response rates and improved data quality. As data quality could only be ascertained from respondents, statistical adjustment was used to account for selection resulting from differences in response rates by treatment arm.

## 5.7.3 Opportunities {#opportunities}

Existing studies that have exploited experiments embedded within the cohorts have focused on short-term outcomes -- e.g., response rates or measurement at the sweep in which the experiment took place. As further sweeps become available it will be possible to examine long-term outcomes -- for instance on attrition from the cohorts or the measurement of change across time (e.g., ageing and other trajectories). It is possible that incentives to participate have only short-term effects on retention if marginal participants drop out at subsequent sweeps. Alternatively, the offering of incentives in just one sweep could reduce long-term response, if the removal of financial incentives reduces intrinsic motivation (cf. Gneezy & Rustichini, 2000). Existing studies assessing effects of survey design on measurement have also focused on univariate descriptive statistics, but this is only one type of analysis performed with cohort data. Bias in sample means and proportions may not translate into material levels of bias in, e.g., associational analyses, which could be tested in the experimental data.

Studies that have investigated the effects of survey design on measurement and data quality have used statistical control (Booth et al., 2024) or multiple imputation (Goodman et al., 2022) to account for differential non-response. Quantitative Bias Analysis (Section 5.20) could instead be used to estimate effects under various plausible models of selection, though differences in response rates across treatment arms are typically small and selection effects may not be large enough to make substantive differences to results.

It is sometimes the case that variables capturing treatment arm within the experiment are not available in the standard datasets on the UK Data Service and require bespoke data access instead. It is also sometimes the case that data on the UK Data Service are only available for participants at a given sweep, though non-respondents may have been part of the experiment, too. As noted, non-response can lead to bias in analyses of experiments, so data from non-respondents may be required. This is the case for the NCDS Age 55y mixed-mode experiment, at least. Data enquiries can be sent to the [CLS Data team](mailto:clsdata@ucl.ac.uk).
