# 5.4 Missing Data Methods {#missing-data-methods}

## 5.4.1 Method {#method}

In [Section 2.2.4](02-problem.qmd#selection-bias), we discussed how large-scale intensive and longitudinal data collections, characteristic of CLS's cohorts, can contain a sizeable amount of missing data through unit, sweep, and item non-response. Where non-response is not random, missingness can lead to selection bias, impacting internal (and even external) validity (Type 1 and Type 2 selection bias; Lu et al., 2024). For instance, if individuals with poorer mental health are more likely to drop out from a cohort, associations between factors that cause mental ill-health and measurements of mental health may be attenuated in available (complete case) data.

There are two main methods for addressing missingness: inverse probability weighting (IPW) and multiple imputation (MI). IPW in this setting involves two steps. First, the probability of response is calculated or estimated, typically with a regression model using data available on participant characteristics for both respondents and non-respondents (in longitudinal data, this would be data collected prior to an individual attriting). Second, the inverse of this probability is taken and used to weight (non-missing) observations in substantive analyses. By taking the inverse, individuals with lower probability of response are given greater weight -- in effect, they are used to represent more individuals whose data are missing. For instance, an individual with only a 10% predicted probability of response will be weighted ten times as highly as someone certain to respond as the former is used to reflect both themselves and nine other individuals with the same (10%) probability of response predicted to have [not]{.underline} in fact responded.

MI is typically performed using chained equations: in this procedure, missing data are imputed using a series of regression models where the statistical relationships between observed values are used to predict values that are missing. For instance, in longitudinal data where some participants drop out, BMI collected during childhood could be used to predict adulthood BMI by applying the association detected in individuals for whom BMI was observed on both occasions. These imputed values are then used to predict and impute missing data in other variables. As predictions are unlikely to be perfect, multiple imputed datasets are created to reflect imputation uncertainty. Substantive analyses are then performed in each imputed dataset and results pooled accounting for the variation both within and between imputations -- typically, pooling is done by applying 'Rubin's Rules' (Rubin, 1987), though bootstrapping is also possible (Bartlett & Hughes, 2020; Schomaker & Heumann, 2018). Note, MI (and IPW for non-response) are not methods for estimating causal effects in themselves; rather, they address a source of bias in onwards analysis.

In MI, imputation and substantive models should be 'congenial' (van Buuren, 2018); that is, the imputation model should be no more restrictive than the substantive model, accommodating every variable and functional form the substantive model contains -- i.e., outcome, exposure, covariates, and interactions or nonlinear terms. Otherwise, excluded terms are implicitly set to zero in the imputation models and are not directly reflected in imputed values, attenuating associations in downstream analyses.[^20]

MI and IPW rely on assumptions about the mechanism by which data became missing. These mechanisms can be classified into Missing Completely at Random (MCAR), Missing at Random (MAR) and Missing Not at Random (MNAR). To illustrate each, we take the example of using partially observed data to obtain an unbiased estimate of average (mean) income:

- MCAR: Missingness is unrelated to observed or unobserved values.

  - Example: Income data for a random subset of participants are lost due to hard disk failure.

- MAR: Missingness is unrelated to unobserved values, conditional on observed data.

  - Example: Participants in jobs that involve frequent travel are more likely to miss a survey interview, and these jobs may pay more on average. However, among those in such jobs, who is away -- and so whose data are missing -- is unrelated to income.

- MNAR: Missingness is related to unobserved values, even conditional on observed data.

  - Example I: Participants whose income derives from illicit sources (and who may have higher income, on average) decline to answer questions on income, so whether income is reported is related to income itself, even among participants who otherwise look alike on everything observed (e.g., education level).

  - Example II: Due to social desirability concerns, people with low income refuse to answer questions on income.

Note, in MNAR Example I, missingness was due to an unobserved variable, rather than income itself, whereas in Example II, it is income itself that is the cause of missingness. However, both are still MNAR processes, though if we had data on whether a participant derived income from illicit sources, the former example would be MAR.

MCAR, MAR and MNAR processes all reduce statistical power because each leads to a loss of information. However, they have different consequences for bias ([Figure 5.5](#figure-5-5)). MCAR processes do not generate bias. MAR processes bias complete-case analyses, unless the variables related to missingness are conditioned upon in the substantive model or MI or IPW is used with imputation or response models including those variables appropriately. MNAR processes also generate bias, and neither MI nor IPW can address this. However, this is partly a question of degree: in longitudinal data, the plausibility of the MAR assumption can be increased using lagged measurements and other rich information from over the life course (e.g., data on early-life cognitive ability, socioeconomic background, prior measures of income, etc.; Mostafa et al., 2021; Silverwood, Narayanan, et al., 2024); the extent of violation of the MAR assumption can at least be reduced, if not fully ameliorated. Admin linkages -- which can continue even if the participant stops responding to the main survey -- can also help here (Rajah et al., 2023). In [Section 5.20](05-20-quantitative-bias-analysis.qmd), we describe a variant of MI -- Pattern Mixture Modelling -- that can account for MNAR processes.

::: {#figure-5-5}

![**Figure 5.5:** Simulations displaying MCAR, MAR and MNAR processes in a variable, income. Left panels show all data points (blue points), regardless of whether they are observed or not. Right panels show observed data points (pink dots) surviving the missing data process (missing data are shown in light grey). Red lines show average (mean) income in relevant data. We use the observed data to attempt to obtain an unbiased estimate of income that would be obtained if all data points were available. In row (a), data are MCAR -- missingness unrelated to the value of income -- and mean income in the observed data (pink dots, right panel) is an unbiased estimate of mean income. In row (b), data are MAR -- missingness due to type of work, with different types of work paying different wages. The unconditional estimate of income is biased, but conditioning on type of work removes bias. In MI, predicting income from observed type of work would yield an unbiased estimate of a person's income and the resulting imputed data would yield an unbiased unconditional estimate of average income. In row (c), data are MNAR -- people with high incomes less likely to report income. Even conditioning upon a predictor associated with high income (e.g., education level), estimates of average income with observed data are biased, though less so than when not conditioning upon this variable.](images/image22.png){width="75%"}

:::

An advantage of MI over IPW for handling missingness is that, by retaining partially observed cases rather than discarding them, MI uses more of the available data and can therefore yield more precise estimates. Nonetheless, higher missingness entails lower statistical power and potentially greater sensitivity to modelling choices in either method. In IPW, low probabilities of response can generate large weights for some observations, which inflates the variance of estimates and increases dependence on the response model being correctly specified. In MI, greater missingness increases both the contribution of imputed values to estimates in substantive models and variation between imputed datasets as imputation models are less precisely estimated. Predictive accuracy can be increased by including 'auxiliary' variables into imputation or response models -- additional variables that are predictive of missing values, but which do not appear in substantive models.

MI and IPW are not mutually exclusive and can be used alongside each other. For instance, it can be useful to use IPW to account for sweep non-response, and within a responding sample, use MI to address item missingness (see, for example, L. Wright, Davies, et al., 2024). It is also possible to use MI to impute missing values in variables to be used to create IPW weights. There are methods for combining IPW and MI in ways that are 'doubly robust'; see Seaman & Vansteelandt (2018) for more details. IPW can also be performed combining weights for selection (i.e., response) and for treatment (IPTW, [Section 5.3](05-03-inverse-probability-of-treatment-weighting.qmd)).

Note, the potential outcomes framework conceptualises causal inference as an inherent missing data problem (Parra et al., 2021); counterfactuals are not observed and are therefore unknown. Some newer methods approach estimating causal effects as a missing data issue (e.g., Matrix Completion; Athey et al., 2021); given these methods are more advanced and niche we do not discuss these further here.

## 5.4.2 Applications {#applications}

Wright et al. (2024) use a combination of IPW and MI to estimate the association between a polygenic score (a summary measure of genetic predisposition to a trait) and observed BMI over the life course in four different cohorts (including the NCDS, BCS70 and MCS). As genetic data were only collected in later sweeps of each cohort (44y, 46y, and 14y for the NCDS, BCS70 and MCS, respectively), there was a high amount of missing data, including for BMI at later ages. The authors therefore used IPW to weight observations in the genotyped sample. MI was then used to impute remaining item missingness; earlier observations of BMI were used to impute later values of BMI and several auxiliary variables predictive of missingness (Mostafa et al., 2021) were also included in imputation models. Code used in the study is available here: <https://osf.io/nxusz>.

## 5.4.3 Opportunities {#opportunities}

There are many opportunities to apply IPW and MI in CLS data. The longitudinal nature of data collection means there is generally a lot of information available with which to create non-response weights or to incorporate into imputation models. This includes earlier measurements of variables that may predict non-response (e.g., measures of mental health earlier in life \[including in adulthood\]). Several papers show that this information can increase the plausibility of the MAR assumption, as evidenced by ability to recover initial characteristics in imputed data (Katsoulis et al., 2024; Mostafa et al., 2021). These papers also give useful information on which factors predict non-response that can be incorporated into analysts' own models. CLS have additionally produced an accessible and extensive user guide on Handling Missing Data, which readers may find helpful (Silverwood, Narayanan, et al., 2024).

[^20]: Congeniality is sometimes instead referred to as compatibility, though compatibility has another definition in MI that is distinct (van Buuren, 2018).
