# 5.16 Cross-Context Analysis {#cross-context-analysis}

## 5.16.1 Method {#method}

In [Section 5.15](05-15-negative-control-outcomes-and-exposures.qmd), we saw that one way to make a theory elaborate is to enumerate which variables an exposure should have a causal effect upon (and which it should not) or which variables an outcome should be causally affected by (and which it should not), given the set of predictions a theory can make. Another way to make a theory elaborate is to draw out the settings or individuals a hypothesised causal effect should exist in or in which the effect would otherwise be stronger or weaker than usual. A competing theory may be able to explain the presence of an association between X and Y in general, but not specific patterns of association between these different cases. Alternatively, a causal effect may be similar in different settings, but (hypothesised) confounding structures may change, so consistency of association across these settings is evidence compatible with the causal theory being true. Cross-context analysis encapsulates this logic by performing analyses in different (subsets of) data or populations (Eggers et al., 2024; Gage et al., 2016; Piccininni & Stensrud, 2024).

There are three types of comparison that are particularly relevant for CLS's cohort studies. First, time -- a causal effect may be anticipated in some periods, cohorts, or stages in the life course, but not others. Second, space -- a causal effect may be anticipated in some geographies, but not others, or the confounding structure may be anticipated in some, but fundamentally different in others. Third, population subgroups -- there may be certain sections of the population for whom a causal effect would not be anticipated. These are best explained by way of examples.

**Time**

- Cognitive ability is hypothesised to have a beneficial effect on health due to greater knowledge and better decision making among those with higher cognitive ability (Gottfredson, 2004). Knowledge about diseases -- and how to prevent them -- varies across time as scientific discoveries are made and technologies are introduced (Clouston et al., 2016). Given this, if cognitive ability causes health, we should expect inequalities in health according to cognitive ability to grow after facts about a disease are first discovered and to decline as technologies are introduced that reduce the difficulty of avoiding or managing a disease.

- In the UK, maternal smoking during pregnancy has become less prevalent but more strongly associated with socioeconomic adversity over time. If associations between maternal smoking and offspring outcomes are merely driven by confounding through socioeconomic position, we would therefore expect stronger associations in more recent cohorts (Sellers et al., 2020).

**Space**

- Between 1999 and 2010, the UK Government implemented a well-funded strategy to halve teenage pregnancies in England (Hadley, 2017). Teenage pregnancies did fall over this period (Wellings et al., 2016) but may have done so absent the strategy. Was the Teenage Pregnancy Strategy successful? At the very least, we would expect pregnancy rates to fall faster than in other countries which did not implement such strategies, such as Scotland and Wales (Baxter et al., 2021; Craig et al., 2016).

- The 2013 Removal of the Spare Room Subsidy (the so-called 'Bedroom Tax') reduced benefits for working-age individuals in social housing with an unoccupied bedroom. This reduction in entitlements for individuals already more likely to be on low incomes may be expected to reduce mental and physical health (cf. Reeves et al., 2016). However, a curious feature of the policy's implementation is that, in Scotland, the government compensated any reduced benefits with Discretionary Housing Payments, meaning the bedroom tax did not affect incomes for residents in that country. We should therefore not expect any association between being subject to the bedroom tax and mental health in Scotland but should expect to see one in England and Wales.

- The social patterning of breastfeeding varies across the world. For instance, in the UK, socially advantaged mothers are more likely to breastfeed, but this is not the case in Brazil. If the association between breastfeeding and child development is simply a product of socioeconomic confounding, we would expect positive association in the former, and little association in the latter (Brion et al., 2011).

**Population Subgroups**

- As discussed in [Section 5.9](05-09-instrumental-variables.qmd), certain variants of the ALDH2 gene are related to better cardiovascular health. This is hypothesised to be due to the effect of ALDH2 on reducing alcohol consumption by determining the comfort with which one metabolises alcohol. In East Asian cultures, women typically drink little, regardless of which ALDH2 variant they carry, while men are more likely to drink and for this to be related to ALDH2. If ALDH2 has a causal effect only via alcohol consumption, we should therefore expect associations with cardiovascular disease in East Asian men but not women (L. Chen et al., 2008).

- Unexpected events ([Section 5.8](05-08-natural-experiments.qmd)) should only have effects among those who are aware of them. For instance, the release of the Royal College of Physicians' (1962) report on smoking and health was a watershed moment in public appreciation of the harms of smoking, but if access to information is sufficient to alter the decision to smoke, then smoking among TV owners or newspaper readers -- likely more aware of the RCP report -- should have declined the most (James, 2024).

- Cholera being transmitted via infected water, rather than miasmic air, predicts that people who live near the Broad Street pump, but do not take its water, will be less likely to succumb to the disease, and that those who live far away, but still have its water delivered, will become infected ([Section 3.3](03-approaches.qmd#elaborate-theories)).

The examples where the causal effect is expected to differ share a common feature that an essential mechanism transmitting the effect is missing, or is otherwise weaker, in one setting than another. For instance, for the bedroom tax, in Scotland, the essential ingredient -- lower income -- was not present. Readers may notice the similarity between the cross-context design and the negative control outcome design -- rather than choose different variables for analysis, different sections of the data are used for which, e.g., causal effects should not exist. Cross-context designs where there is an absence of a causal effect in the comparator population but biasing processes are otherwise the same have been termed negative control population designs (Piccininni & Stensrud, 2024).

Like the negative control design, convincing cross-context analyses require knowledge of the subject area. However, here the barrier for entry may be lower, and the arguments easier to make. For instance, the ALDH2 example largely requires identifying a group with very low alcohol consumption regardless of the ALDH2 variant they carry. Also, like the negative control design, the cross-context design can still be useful when the strength of a causal mechanism varies across settings, rather than the mechanism being absent or blocked entirely. The elaboration of the theory is predicting an overall pattern of results. In their discussion of cross-context designs, Gage et al. (2016) describe a test of the hypothesis that cannabis has a causal effect on psychosis due to its tetrahydrocannabinol (THC) content: a corollary is that as levels of THC in cannabis have increased, associations between cannabis use and psychosis should have similarly increased, if this is the causal mechanism.

Where the cross-context design is motivated by an argument that the causal effect of the exposure of interest will vary across populations, plausibility relies on the extent to which bias processes are similar, akin to the assumption of U-comparability in the negative control outcome and exposure designs ([Section 5.15](05-15-negative-control-outcomes-and-exposures.qmd)). Additionally, where it is the biasing processes that are hypothesised to vary across populations, an assumption is that the causal effect should be similar in each population, but effects may be heterogeneous and could themselves lead to cross-context differences in associations.

Cross-context designs are extensively used in the genetics literature in the study of gene-environment interaction (GxE; Pereira et al., 2022). For instance, studies have examined the association between polygenic scores (PGS) and attained education as access to education has expanded (Herd et al., 2019; Morris et al., 2026), or between PGS and body mass index before and amidst the obesity epidemic (Conley et al., 2016; L. Wright, Davies, et al., 2024) or in other groups for whom genetic effects should be stronger (e.g., among those genetically predisposed to obesity and living near fast food outlets; de Roo et al., 2024). Again, adding a cross-contextual element supports causal interpretations by testing for a predicted pattern of associations. However, a drawback of GxE studies is that the environment may be 'endogenous' (*determined in the system*; e.g., people may choose where to live based on their genetic predispositions). Further, for complex traits, the associations between PGS and phenotypes may reflect pleiotropic effects (also see Westerman & Sofer, 2024 for discussion of issues in GxE studies). Note, birth year -- and the cohort effects it implies -- more plausibly represents exogenous environments, as genetic changes occur at a relatively slow rate. A drawback however is the lack of specificity in which aspects of the environment have changed (e.g., aspects of the obesogenic environment in general).

## 5.16.2 Applications {#applications}

Sellers et al. (2020) compare associations between maternal smoking in pregnancy and offspring development (birthweight, conduct problems and cognitive ability) in the NCDS and MCS -- as discussed, social patterning of maternal smoking was stronger in the more recent cohort. Associations between maternal smoking and birthweight were similar in each cohort, whereas associations were stronger in the MCS for other outcomes assessed, consistent with material bias from confounding. However, causal effects becoming larger in more recent cohorts is also compatible with the results.

Wright et al. (2024) examine the association between a PGS for BMI and phenotypic BMI across life in the NSHD, NCDS, BCS70, and MCS, which collectively span a period before and during the obesity epidemic -- the NSHD grew up during post-war rationing, while childhood obesity rates reached 20% in the MCS. They find stronger associations in more recent cohorts, particularly comparing the MCS with earlier generations, consistent with theory that the PGS reflect genes that have effects on adiposity via modifiable behaviours. However, this is evidenced only indirectly using birth year as a proxy for exposure to the 'obesogenic environment' -- it is unclear which aspects of the environment are operative (if any).

## 5.16.3 Opportunities {#opportunities}

Opportunities for cross-context analysis arise from the temporal and geographic expanse represented in CLS's cohorts. For instance, education systems have historically differed in England, Scotland and Wales, e.g., on rules on minimum school leaving ages, which (over some time frames) entail that individuals born earlier in a school year in England are able to leave school at a younger age than if they went to school in Scotland (Del Bono & Galindo-Rueda, 2007). Geographic range can also be extended by harmonising with studies from other countries where, e.g., different confounding structures for exposures and outcomes of interest may be present.

There are numerous opportunities for GxE in the cohorts, including comparing genetic effects across cohorts, given the generational differences they represent (Morris et al., 2026; L. Wright, Davies, et al., 2024). Opportunities also exist linking genetic data with geographic data (e.g., to identify differences according to pertinent features of the local environment) and with other survey data, given the extensive phenotypic data available (e.g., association between genetic risk and depression among victims of crime), notwithstanding potential endogeneity of these latter environments. Again, harmonisation with other international data could also expand possibilities for GxE cross-context analysis.
