# 5.10 Regression Discontinuity Designs {#regression-discontinuity-designs}

## 5.10.1 Method {#method}

Instrumental variable designs use variation in a third variable (the instrument) as a source or marker of exogenous variation in an exposure. Sometimes there are variables that have an effect on an exposure and vary over a wide range. While overall these variables may be associated with confounding factors, narrow parts of their variation can lead to large differences in the likelihood of exposure. Within this narrow range, variation is therefore strongly related to the exposure, but may be only weakly related -- if at all -- to the confounding factors.

Take democratic elections -- does becoming a Member of Parliament (MP) increase one's salary after the end of one's parliamentary career (Eggers & Hainmueller, 2009)? We can't simply compare people who win elections with those that lose them because rational political parties field their most promising candidates in safer seats and voters give their support to candidates they perceive as more able. People who win large majorities differ from those who lose handily in ways that could allow them to obtain higher wages absent becoming an MP. But winners take all in a first-past-the-post system, whether the majority is one or twenty thousand. People who lose by a small amount are likely similar, on average, to those who win by a small amount. Within a small margin, random factors can be decisive ([Figure 5.11](#figure-5-11)).[^32]

::: {#figure-5-11}

![**Figure 5.11:** DAG representing the Regression Discontinuity Design (RDD). In the RDD, there is a running variable R that influences exposure X. However, across the total span of the running variable (Panel A), this variable is itself a cause of the outcome Y or is correlated with other causes (U) of the outcome Y (Panel A). Limiting to a narrow range in which the running variable (Panel B) has a substantial effect on determining exposure X (e.g., at a cut-off where R determines eligibility for X), variation within the running variable is not sufficient to itself cause differences in the outcome or be associated with other causes (U) of the outcome. DAGs adapted from Cunningham (2021).](images/image28.png){width="84%"}

:::

As its name suggests, the Regression Discontinuity Design (RDD) takes advantage of small perturbations around discontinuities such as this. RDD comes in two flavours: sharp and fuzzy ([Figure 5.12](#figure-5-12)). In sharp RDD, exposure is zero on one side of the discontinuity and complete on the other. The first-past-the-post election system represents a sharp discontinuity; one is voted in, or one isn't. In fuzzy RDD, probabilities of exposure are intermediate, but around the discontinuity, the likelihood of exposure changes substantially. Age-based eligibility criteria for vaccination represent a fuzzy discontinuity; some people below the threshold may be eligible for vaccination for other reasons, while those above the threshold may opt against vaccination. But ageing a matter of days can still generate large jumps in vaccination rates and by itself would not notably affect outcomes of interest (Basta & Halloran, 2019).

::: {#figure-5-12}

![**Figure 5.12:** DAG representing sharp and fuzzy regression discontinuity designs (RDD). In the RDD, there is a running variable (x-axis) that influences exposure and at a cut-off there is a jump in the likelihood of being treated. In sharp RDD, no one below the cut-off is exposed and no one above the cut-off is unexposed. In fuzzy RDD, some people below cut-off are exposed and some people above cut-off are unexposed. However, there is a discontinuous jump in the probability of exposure around the cut-off, such that the probability of exposure is markedly higher for those just above the cut-off than those just below it.](images/image29.png){width="100%"}

:::

Discontinuities are common wherever there is some form of rationing or where definitive criteria are used to make eligibility transparent or implementation more straightforward. This is a feature of most bureaucracies and administrative systems, including clinical settings where treatment protocols are used. Discontinuities graft sharp changes onto otherwise continuous characteristics. While a person may be identified as requiring medical attention based on strict criteria, underlying risks change more gradually; hospitals may use a cut-off for low birth weight of 2.5 kg but weighing 2.51 kg is little better than 2.49 kg. Discontinuities also arise through cleavages in time -- a policy is enacted whereas before it was not. People born on August 31^st^ are the youngest in their school year, while people born on September 1^st^ are the oldest. People born August 31^st^ 1957 were able to leave school at age fifteen, if they so wished, but people born a day later had to wait until age sixteen thanks to the passing of an Act of Parliament, which raised the minimum school leaving age.

In RDD parlance, the variable determining exposure is referred to as the 'running variable' (Cunningham, 2021).[^33] The basic identification strategy of RDD is to estimate the difference in the outcome around the discontinuity (for instance, vote share and wealth; [Figure 5.13](#figure-5-13)), because the units of analysis are, in theory, exchangeable at the time the exposure is assigned. This can be achieved using parametric or non-parametric methods.

::: {#figure-5-13}

![**Figure 5.13:** The association between relative vote share received by Conservative candidates for UK Parliament and their wealth at death. Candidates receiving positive relative vote shares were elected to Parliament. The discontinuity at zero, and the (flat) continuous relationship between vote share and wealth either side is evidence that being a Member of Parliament increased wealth at death among these candidates. Figure taken from Eggers & Hainmueller (2009).](images/image30.png){width="51%"}

:::

In a simple parametric set-up, the relationship between the running variable and the outcome is modelled with continuous terms, and a binary variable for whether the running variable is above the discontinuity is also included in the regression (see [Equation 5.1](#equation-5-1)). The continuous terms capture the association between the running variable and the outcome that would appear absent the variable influencing exposure. The binary term captures the effect of the exposure on the outcome at the cut-off.

::: {#equation-5-1}

$$y_{i} = \beta_{0} + \beta_{1} \cdot x_{i} + \beta_{2} \cdot D\left( x_{i} \geq X \right) + \epsilon_{i} \tag{5.1}$$

:::

  ----------------------------------------------------------------------------------------------------------------------------------

where *i* indexes individuals, $x_{i}$ represents the level of the running variable for person *i*, and $D\left( x_{i} \geq X \right)$ is a binary variable equal to 1 where $x_{i}$ is at or above the discontinuity cut-off point ($X$).

The parametric design uses data from a wide range of the running variable. It relies on modelling the association between the running variable and the outcome appropriately -- incorrectly modelled non-linearities may yield a spurious non-zero coefficient for the binary discontinuity term. In the non-parametric set-up, only data from around the discontinuity are used, with weighting possibly used to place greater emphasis on observations particularly close to the cut-off. The non-parametric approach is more data-intensive as it requires sufficiently large samples close to the discontinuity but has the advantage that it does not rely on appropriately modelling the correct functional form. The sample size requirement can be relaxed by increasing the width around the discontinuity from which observations are used, but this comes at the cost of reducing the plausibility that confounding factors -- including the running variable itself -- are the cause of associations with the outcome variable.

In fuzzy RDD, the running variable is associated with exposure above and below the discontinuity, and being above the cut-off is effectively an 'encouragement'. Instrumental variable methods (Section 5.9) are therefore used to rescale the effect by the cut-off's influence on probability of exposure. The causal effects estimated in sharp and fuzzy RDD are local to the cut-off, with the added proviso that in fuzzy RDD this is the causal effect among those who 'comply' with the encouragement -- i.e., were exposed due to just sitting above the cut-off (as such, fuzzy RDD requires homogeneity or monotonicity assumptions discussed in Section 5.9). These estimands can reflect relevant research and policy quantities if the causal effect arising from the imposition of the cut-off is of research interest.

A major strength of the RDD approach is that some of its assumptions can be falsified (though not verified). Several tests present themselves to the budding RDD analyst. First, similar to RCTs, balance in baseline (observed) covariates around the cut-off can be examined. Second, models can be repeated using placebo cut-offs. These cut-offs should not be related to jumps in the probability of treatment and so any association would be evidence that the model is misidentified or its assumptions are violated. For instance, using an imaginary decision rule for elections where the 'winning' candidate wins if they receive 20% more votes than their closest rival, or imagining the school leaving age was raised in 1971 or 1973 instead of 1972.

RDD is not without its limitations, however. First, as intimated, the general form between exposure and outcome needs to be appropriately modelled; mismodelling can lead to discontinuities appearing which aren't there in practice, or vice versa (Gelman & Imbens, 2019; Huntington-Klein, 2022). A key issue with sharp RDD is that there is no 'common support' -- i.e., treated and untreated individuals do not overlap in their value of the running variable. Counterfactual values therefore have to be extrapolated, rather than directly drawn from observed data from those in the comparator group.

A second limitation is that the same threshold may be used in multiple systems, analogous to violations of the exclusion restriction in the IV design (Section 5.9). For instance, in the UK, turning eighteen allows one to buy alcohol legally but also to gamble and buy cigarettes, too, each of which could affect health outcomes. Similarly, being the oldest in one's school year may increase academic confidence, but also physical maturity and social confidence. Each might impact educational attainment.

A third limitation of RDD is that, as regression discontinuities are most frequently found in administrative systems, the 'treatments' one can examine are limited by those implemented by these systems. These treatments may be relatively narrow (Bann et al., 2024). For instance, just meeting eligibility criteria for more generous welfare payments may be plausibly exogenous, but the total effect of these payments on income or wealth may be smaller, shorter-lived, and easier to compensate for than changes in income observed more generally and which are of greater interest (e.g., in social epidemiology top and bottom quintiles of income are often compared).

Finally, and most subtly, individuals, or the people acting on their behalf, may be aware of cut-offs and their implications and may act to ensure they are eligible for the treatment -- or ineligible, if the treatment is undesirable. For example, some individuals who are close to being classified as long-term unemployed might accept a job offer more readily in light of looming cuts to welfare cheques(Card et al., 2007). Businesses that would be subject to increased regulation if they grow might opt against hiring an extra employee (Garicano et al., 2016). In these cases, there may be confounding even close to the cut-off; checking the distribution of covariates and density of observations either side can help assess this. Another subtle issue is misreporting or other fraudulent behaviour to meet eligibility criteria.[^34] In this case, there is potentially non-differential or non-independent measurement error in the running variable.

## 5.10.2 Applications {#applications}

Several studies have applied RDD to CLS's cohorts. One popular object of study in the RDD literature is the 1972 Raising of the School Leaving Age (ROSLA, discussed above). In fact, the UK (or rather its constituent countries) has undergone several ROSLAs, including in 1947 and more recently in 2013 and 2015, with the raising of the minimum 'participation age' in education or training. As discussed in Section 5.8.2, though there is little variation in birth dates among CLS cohort members, there is plenty among their family members, including their parents. Sabates & Duckworth (2010) exploit the 1947 ROSLA and use data from the NCDS to assess the effect of increased maternal education upon cohort members' developmental outcomes, finding positive effects on maths ability but no effects on reading or behaviour. One drawback of this approach is that studying parental effects within a birth cohort necessarily conditions upon fertility and the parent's age at birth. It is possible that both are influenced by parental education.

Another RDD often used in the educational literature is test scores as these are widely used to determine entry into specific institutions (e.g., minimum A-Level grades for acceptance into top universities or degree requirements for entry into competitive graduate schemes).[^35] In the UK, entry into selective grammar schools is largely based on results on the 'eleven-plus', a test similar to an IQ test. Pastore & Jones (2023) use data from cognitive tests at age 11 years in the NCDS to proxy for eleven-plus scores to assess the effect of attending grammar school on several educational, labour market, and health outcomes. However, an issue is that, as they only use a proxy measure and (unobserved) qualifying eleven-plus scores for grammar school varied across England and Wales, they have to estimate the threshold determining grammar school entry from the NCDS data themselves. They do however successfully perform several 'negative control' tests (Section 5.15), which support a causal interpretation (e.g., no association between grammar school attendance at the discontinuity and cognitive ability scores at age 7 years).

## 5.10.3 Opportunities {#opportunities}

We have noted that discontinuities most frequently arise when an individual interacts with a (government) service. Specific criteria are frequently used to determine eligibility for services or duties (e.g., for income support) and hard geographical boundaries determine the bodies under whose purview one sits -- for instance, residents of Bassetlaw in Nottinghamshire are eligible for three rounds of IVF, whereas their neighbours in surrounding districts (including across the same street, in some cases) are only eligible for one (Patel & Sissons, 2024). Befitting this, geographic and admin data linkages have the potential to be particularly useful for performing RDD in CLS's cohorts. For instance, educational admin data linkages may enable examination of the effects of educational access or attainment on various outcomes -- universities offer places based on letter grades, though the underlying exam scores are continuous. An additional advantage of geographic (or other) variation is that some policies may be only rolled out in specific areas or groups over time. In this case, temporal variation could be used to identify causal effects with unaffected groups used for comparison -- for instance, eligibility for the latest increase in the education participation age depends on birth date but has only been implemented in England and not Scotland or Wales. An issue with performing RDD in the cohorts is that sample sizes may be relatively limited around a cut-off, and so parametric methods -- or pooling data across cohorts and with other data sources -- may be necessary.

[^32]: In the 1997 General Election, Conservative MP for Torbay, Rupert Allason, lost his seat by twelve votes. A week before, he failed to tip a waitress, leading fourteen waiters who had intended to vote Tory to cast their votes for the Liberal Democrat candidate instead (Ronson, 2001).

[^33]: The running variable is also referred to as the 'assignment' variable.

[^34]: In stellar work, Saul Newman (2024, 2025) catalogues evidence that cases of extreme old ages are more likely pension fraud.

[^35]: In fact, the original RDD analysis used this design (Thistlethwaite & Campbell, 2017, Reprint)
