# 5.14 Family Designs {#family-designs}

## 5.14.1 Method {#method}

In [Section 5.5](05-05-longitudinal-fixed-effects.qmd), we discussed the longitudinal fixed effect design which exploits repeated measurement of the same individuals to control for time-invariant confounders by design rather than through explicit statistical control. Family designs similarly exploit features of the data-generating process to control for broad classes of confounders. There are several family designs that can be used with CLS's cohort data, including designs that precede the molecular genetics revolution and those that use genetic data directly.

Multiple CLS studies have data on siblings, either from a small number of multiparous births or from data collections on a larger number of cohort members' siblings; for instance, Sweeps 2 and 3 of the MCS included a questionnaire for older siblings. Like longitudinal fixed effects, the sibling comparison design exploits variation in exposure within siblings, this time to account for factors that are common between them (Sjölander et al., 2022). This includes aspects of family background (e.g., parenting styles, family socioeconomic position) and shared genetics (50% on average for dizygotic twins or full siblings; 100% for monozygotic twins).

The usefulness of the sibling design depends on the extent to which confounding factors are in fact shared. The behaviour genetics literature suggests the contribution of shared environments to traits and other outcomes is relatively weak and declines in predictive power as individuals age (Davey Smith, 2011; Plomin, 2018; Plomin & Daniels, 1987). Importantly, this literature also shows that children elicit responses from their environment, including the parenting they receive (see, e.g., Selzam et al., 2018; Wertz et al., 2019) -- in other words, less of the family environment may be 'shared' than initially expected. The range of influences accounted for by the sibling design plausibly decreases as the age gap between siblings becomes greater, given differences in childhood environment will be larger and as common events will be experienced at different developmental stages. Again, as with longitudinal designs that exploit within-person variation, the sibling design in fact only captures common environments that make siblings more similar to each other than to other people -- to the extent that a common exposure has a heterogeneous effect (e.g., because its effects interact with other exposures, such as prior unique developmental experiences) it will not be fully controlled for by design in this set-up.

Moreover, in some circumstances, the sibling design can in fact increase bias, relative to a standard observational design. This is partly due to problems which affect fixed effects designs more broadly (see [Section 5.5](05-05-longitudinal-fixed-effects.qmd)): where there is measurement error, a greater component of within-sibling variation in the measured factor will be noise, and where a relatively strong confounder causes the variation within siblings, exploiting just within-sibling variation can increase bias, analogous to the issue of Z-bias discussed in [Section 5.1](05-01-control-via-regression-adjustment.qmd). Further, some issues are (arguably) unique to the sibling design, including 'carryover' effects (Sjölander et al., 2016), where one sibling influences another, and the existence of shared mediators (Sjölander et al., 2022), which are absorbed into the fixed effect along with shared confounders -- financial resources could be shared within families, for example. As sibling designs only exploit siblings who are discordant on exposure, they can also suffer from power issues and low generalisability to the general population, which includes singletons and families with siblings who are not discordant on exposure.

Another family-based method that can be used with CLS data is the adoption design. The NCDS and BCS70 were born during periods when adoption was relatively common (Rushton et al., 2020) and contain data from \~ 300 adoptees in total, who can be combined, including with adoptees identified in other studies, to increase total sample sizes. As discussed in Appendix [Section 8.2](08-appendix.qmd#why-does-correlation-often-not-equal-causation), a major and consistent finding in the behaviour genetics literature is that almost all human traits are heritable: parents and their (biological) offspring resemble each other at least in part because they share the same genes. The adoption design exploits the fact that children and their adoptive parents are not expected to be genetically related. Therefore, associations between adoptive parental traits and family environments and children's outcomes should not be explained by direct genetic transmission. However, it is still possible for children to elicit specific parenting behaviours and other environmental responses (evocative gene-environment correlation), a form of reverse causality. Moreover, adoption placements can be selective, including where children are adopted by relatives. It is necessary to confirm non-familial adoption as otherwise genetic relatedness would still be present, albeit to a lesser extent than with one's natural parents.

The adoption and sibling designs use facts of genetic inheritance indirectly, but the advent of molecular genetics has led to the development of designs that use measured genetic variation. Biological parents and offspring in the MCS were genotyped in Sweep 6 (age 14 years) of the survey, yielding data from more than 2,700 sets of genetic 'trios' (mother-father-offspring) and \~ 8,500 (overlapping) sets of 'duos' (mother-offspring or father-offspring pairs). An increasingly popular design is the genetic nurture design (Bates et al., 2018; Kong et al., 2018). This exploits the fortuitous feature of Mendelian inheritance that offspring inherit a random half of their parents' DNA. With genetic data from parents and offspring, parental genetic data can be decomposed into variants that were inherited by the offspring and variants that were not. Any causal effect of the 'non-transmitted' genetic variants upon offspring can only be via the environment -- e.g., through the impact on parental behaviour (so-called genetic nurture). Any association cannot reflect direct genetic transmission, meaning -- quite remarkably -- that genes can be used to study the environment, even if one isn't interested in genetics *per se*. Conversely, the effect of transmitted genes on offspring's outcomes is a combination of genetic nurture and direct genetic effects, and so, analysed alongside non-transmitted variants, transmitted variants can be used to determine the impact of direct genetic effects.

Genetic nurture analyses proceed in one of two ways. With access to raw genetic data, polygenic scores (summary measures of genetic liability to a trait capturing the effect of many genes; Choi et al., 2020) can be constructed for non-transmitted alleles and transmitted alleles, separately, and used in analyses (Kong et al., 2018). Alternatively, with existing polygenic scores (PGS) constructed from all alleles, transmitted and non-transmitted (as available on the UK Data Service), researchers can condition on child PGS and use parental PGS to identify indirect genetic effects (Bates et al., 2018). In both cases, the parental PGS can be used as instrumental variables for a trait of interest in Mendelian Randomisation (MR) analyses. See [Figure 5.17](#figure-5-17) for DAGs reflecting these designs. Note, it is not necessary that the parent's (exposure) and child's (outcome) trait are the same -- see, for example, Hughes et al. (2024), who use genetic trio data to assess the effect of parental education on child's mental health.

::: {#figure-5-17}

![**Figure 5.17:** Genetic nurture designs that utilise genetic trio data. In observational data, parental traits and offspring traits are correlated but this may be due to direct genetic transmission, rather than an environmental effect of parental traits/behaviours upon their children. Molecular genetic data can be exploited to account for this. (a) Polygenic scores (PGS) are derived from parents’ and children’s genetic data to determine which alleles from each parent have been transmitted to their child and which haven’t to construct PGS of transmitted and non-transmitted alleles (Kong et al., 2018). Non-transmitted PGS can only have a causal effect via the ‘environment’ (e.g., due to parental traits) and so (under specific conditions – e.g., exclusion restriction) can be used as instruments for parental traits. (b) Conditioning upon child’s PGS closes the direct genetic transmission path, leaving the indirect ‘genetic nurture’ path between parental PGS and children’s traits (Bates et al., 2018). Again, parental PGS can be used as instruments for their own traits (under appropriate conditions).](images/image34.png){width="100%"}

:::

As Mendelian Randomisation is a form of IV, under treatment effect heterogeneity (and meeting the monotonicity assumption), the estimand in this analysis would be a Complier Average Causal Effect (CACE; [Section 5.9](05-09-instrumental-variables.qmd)). The exact interpretation of who compliers are may be difficult or impossible to ascertain and have consequences for generalisability.

Another issue with the genetic nurture design is that genetic nurture effects can be biased by population-level phenomena such as assortative mating and population stratification. But the design does allow one to determine direct genetic effects accounting for these phenomena. As with other Mendelian Randomisation analyses ([Section 5.9](05-09-instrumental-variables.qmd)), this design can be biased in the presence of horizontal pleiotropy, a particular problem when looking at complex traits or when using PGS rather than single well-understood genetic variants, for both indirect and direct genetic effects. Nevertheless, accounting for direct genetic transmission may be an improvement on what has gone before. Genetic nurture studies are also power hungry -- current PGS typically only explain a small amount of variation in their relevant traits -- so combining MCS with other data sources containing genotyped families (e.g., Born in Bradford, the Avon Longitudinal Study of Parents and Children \[ALSPAC\], and the Norwegian Mother, Father and Child Cohort Study \[MoBa\]) may be necessary.

## 5.14.2 Applications {#applications}

Adoption and genetic nurture designs have each been used in CLS's cohorts. Dearden et al. (1997) use data from the NCDS to calculate father-son correlations in educational attainment, comparing these correlations in natural and adoptive families to assess whether intergenerational stability is genetic, though due to small sample sizes, estimates are imprecise. Sacerdote (2002) performs a similar analysis with the same data, showing associations between adoptive families' SES and adopted children's reading test scores, likelihood of university attendance, and marriage.

Wright et al. (2025) use trio data from MCS to examine genetic nurture of BMI, finding that, although there is widespread observational evidence that parental BMI is related to offspring BMI, when accounting for direct genetic transmission, there is only evidence that mother's BMI is related to offspring BMI. However, BMI is a complex phenotype, influenced by multiple traits and behaviours, and there is a substantial possibility for horizontal pleiotropy to explain maternal results. Nevertheless, the study shows that associations between fathers' and children's adiposity may be explained by direct genetic transmission, rather than father's behaviour or related environments. Tanksley et al. (2025) use a similar set-up but focus on unbiased estimation of the direct genetic effect of an externalising PGS upon phenotypic externalising behaviour (as measured by the Strengths and Difficulties Questionnaire) -- associations between the child's PGS and the SDQ scores are similar whether parental PGS are included in regression models or not, suggesting the variants captured in the PGS have a causal effect on the child's behaviour.

## 5.14.3 Opportunities {#opportunities}

The MCS sibling questionnaires are presently underutilised and contain several items also asked of cohort members, enabling sibling analysis. The MCS genetic trio and duo data are also underutilised. Rectifying this is straightforward: ready-made PGS for a wide array of traits are available via Special Licence Access on the UK Data Service; see the [CLS Genetics website](https://cls-genetics.github.io/docs/PRS.html) for more details.
