# 5.13 Causal Mediation {#causal-mediation}

::: {.callout-tip appearance=\"simple\" icon=false}
**Note:** This section builds on the concepts of joint exposure effects and exposure-confounder feedback (intermediate confounding). Readers unfamiliar with these concepts are strongly encouraged to read [Section 5.12](05-12-g-methods-for-time-varying-exposures.qmd) on G-methods for Time-Varying Exposures first.
:::

## 5.13.1 Method {#method}

In the previous sections, we have considered settings united by a common motivation: to understand what would happen to some (population-average) outcome if the exposure were changed, whether at a single time point or across multiple time points. Such questions concern a particular end result of interest under specified (hypothetical) interventions on the exposure and are typically agnostic about the processes set in motion by those interventions. For example, one may learn that, in some target population, prescribing one type of medication reduces the five-year risk of developing heart disease by 20%, compared to an alternative prescription. This may be sufficient to conclude that prescribing the medication is beneficial over the alternative in preventing heart disease, but it does not explain how that benefit is produced. For instance, the medication could be more effective because patients are more likely to take it than the alternative, or because it acts on different physiological pathways involved in heart disease, or because of some combination of these and other pathways. Questions about intermediate pathways linking the exposure to the outcome have motivated the development of mediation analysis.

Besides being of inherent scientific interest, understanding the mechanisms by which a causal effect is produced can provide several real-world benefits. First, there may be no known way to intervene on the exposure itself in the real world, or such interventions may be costly, impractical, or otherwise undesirable. Downstream processes may be more feasible to intervene on and provide alternate levers for producing the desired causal effects. For instance, policymakers may not have latitude to fully prevent adverse childhood experiences (primary prevention), but do have more scope to implement interventions to avert some of their negative psychological sequelae [secondary prevention\; e.g., talking therapies\; @ref21075]. Second, understanding intermediate processes may help refine interventions. Rather than treating an intervention as a black box, researchers may wish to know which components, behaviours, or biological changes are most important for producing the outcome of interest. For example, if obtaining a degree increases wages simply by signalling human capital, rather than increasing it, a policy goal of maximising university attendance might be withdrawn. Third, identifying intermediate pathways can help inform tailoring: different pathways may be more relevant in different populations, settings, or stages of life. For instance, if the effect of job loss on mental health operates via financial strain, resources could be focused on those without savings or other sources of income.

In general, mediation analysis has often been understood as an attempt to answer such questions by decomposing the total effect of an exposure on an outcome into direct and indirect components. In the simplest setting, an exposure X is thought to affect an outcome Y, at least partly through an intermediate variable M, referred to as the mediator. The indirect effect is then understood as the part of the effect of X on Y that operates through M, while the direct effect is understood as the part that operates through paths that do not involve M.

To make this discussion more concrete, we return to the example introduced in [Section 5.12](05-12-g-methods-for-time-varying-exposures.qmd), with some changes. Suppose we are interested in the effect of high versus low depressive symptoms at age 16 (X), on HbA1c at age 30 (Y), a biomarker of glycaemic control. We suspect that depressive symptoms may also influence health behaviours, including smoking, and smoking may in turn affect HbA1c. We may therefore be interested in whether the effect of depressive symptoms on HbA1c operates, at least in part, through smoking frequency (M), measured at age 24. As in the previous section, we set aside consistency issues for simplicity, assuming that both "high" and "low" depressive symptoms and smoking frequency are sufficiently well-defined.

Although the motivation for mediation analysis may seem clear at first glance, translating a general interest in "understanding mechanisms" or the notion of "direct" and "indirect" paths into well-defined causal effects is challenging. Traditional approaches to mediation developed from path analysis [@refgBdfcUY6_JnUu1ZVx], an early framework in which hypothesised relationships between variables are represented through a system of equations (this was later generalised within structural equation modelling, SEM). These approaches to mediation define effects through statistical models and make no reference to formal causal frameworks. While a full description of traditional mediation frameworks is beyond the scope of this work, we provide a brief illustration of the simplest approach, where the three effects are defined through linear regression coefficients [@ref464; @refgBdfcUY6_isvLjaZi]:

1.  **Total effect:** The first step is to regress the outcome on the exposure and a baseline set of covariates C~1~, C~2~, ..., C~n~. In our example, this is done by simply running a linear regression model with HbA1c as the outcome, depressive symptoms as the exposure, and including some baseline covariates, giving $Y = \alpha_{0} + \alpha_{1}X + \alpha_{2}C_{1} + \ ...\  + \ \alpha_{n + 1}C_{n} + \varepsilon_{1}$. The coefficient for the exposure $\alpha_{1}$ represents the total effect, which, in our example, gives the total effect of depressive symptoms on HbA1c.

2.  **Direct effect:** The outcome model is refitted with the mediator (smoking frequency) also included: $Y = \beta_{0} + \beta_{1}X\  + \ \beta_{2}M\  + \beta_{3}C_{1} + \ ...\  + \ \beta_{n + 2}C_{n} + \varepsilon_{2}$. The exposure coefficient $\beta_{1}$ estimates the direct effect of the exposure on the outcome. The idea underpinning this step is that by 'controlling' for M, we hold it constant, so the regression coefficient for the exposure gives the X--Y association that is independent of M.

3.  **Indirect effect:** The mediator is regressed on the exposure and covariates: $M = \gamma_{0} + \gamma_{1}X\  + \gamma_{2}C_{1}\  + \ ... + \ \gamma_{n + 1}\ C_{n} + \varepsilon_{3}$. Following the path-tracing rule, the effect along a path is obtained by multiplying the coefficients that make up that path. Therefore, the indirect effect can be defined as $\gamma_{1}{\cdot \beta}_{2}$ (because $\gamma_{1}$ represents the X--M path and $\beta_{2}$ represents the M--Y path).

We have outlined the simplest regression-based approach to mediation, but many extensions have been developed, including mediation in traditional SEM, longitudinal mediation models, multilevel mediation, and others [see @refgBdfcUY6_pnEuvp9T, for an overview]. However, greater modelling complexity does not solve the central problem: these frameworks do not specify what these quantities represent outside the statistical models in which they are defined. It is therefore unclear what precise causal questions they answer and under what conditions a causal interpretation is justified.

Work using counterfactual frameworks shows the quantities only correspond to certain mediational causal effects under restrictive conditions. For example, regression-based definitions rely on a simple linear structure, and the usual decomposition breaks down in the presence of exposure-mediator interaction. Intermediate confounding (partly due to problems discussed in [Section 5.12](05-12-g-methods-for-time-varying-exposures.qmd)) and collider bias ([Section 2.2.4](02-problem.qmd#selection-bias)) can also create issues. Formal causal frameworks are therefore needed both to define the causal estimands and to clarify the conditions under which they coincide with these regression-based definitions [@refgBdfcUY6_WXKrNfmS; @refgBdfcUY6_R7VUgAt3].

Despite what the term might suggest, causal mediation analysis is not a single analytical method. Instead, it can be understood as an umbrella term for analyses that explicitly target direct and/or indirect effects defined through counterfactual frameworks. Because many formulations of these effects exist, we briefly outline some of the most widely used options and discuss their assumptions, focusing primarily on issues of confounding.

We begin with an illustrative causal diagram in [Figure 5.16](#figure-5-16). In this diagram, X influences Y both through M and through other, unspecified pathways that do not involve M. For pedagogical clarity, we depict three distinct sets of confounders that may be relevant depending on the causal effect of interest: C~1~ for the exposure--outcome relationship, C~2~ for the exposure--mediator relationship, and C~3~ for the mediator--outcome relationship. Notice that C~3~ is influenced by X, making it a set of intermediate confounders. This separation is a simplification, as the same variable may confound more than one of these relationships; that is, many pre-exposure confounders may influence X, M, and Y, and causal relationships also exist among the confounders themselves.

::: {#figure-5-16}

![**Figure 5.16:** Illustrative DAG for causal mediation analysis, comprising exposure X, mediator M, and outcome Y. Depending on the causal effect of interest, three sources of confounding may need to be considered: confounding of the exposure--outcome relationship by C1, the exposure--mediator relationship by C2, and the mediator--outcome relationship by C3. The DAG is simplified for educational purposes. In applied settings, the same baseline variable may confound more than one of these relationships, as some confounders may influence X, M, and Y, and causal relationships may also exist among the confounders.](images/image33.png){width="50%"}

:::

As in traditional approaches, we begin by defining the total effect. The total effect captures the net effect of the exposure on the outcome, without separating the pathways through which this effect occurs. In the previous sections of this guide, we have already encountered such a quantity: the average treatment effect. In the context of mediation analysis, the average treatment effect is usually referred to as the total average causal effect, or just total effect (TE). For a binary exposure, this is the difference in mean potential outcome had everyone been exposed compared to no one having been exposed:

$$TE = ATE = E\left\left[ Y^{X = 1} \right\right] - E\left\left[ Y^{X = 0} \right\right]$$

In our example, this would be the difference in mean HbA1c had everyone experienced high depressive symptom levels, compared to everyone experiencing low depressive symptoms. We have already encountered the assumptions required for identifying this effect from data. Specifically: (conditional) exchangeability (i.e., by accounting for all common causes of the X--Y relationship), (conditional) positivity, consistency, and no interference.

Several attempts have been made at defining the direct effect. Intuitively, to conceptualise the effect "not through M", one might imagine changing the exposure while preventing any corresponding change in the mediator. The controlled direct effect (CDE) formalises this idea through joint hypothetical interventions on the exposure and mediator, where the exposure is changed while the mediator is held fixed at a specified value [@refgBdfcUY6_ap40KqKf; @refgBdfcUY6_4U4YiTkh].

For example, one might compare mean HbA1c if everyone experienced high rather than low depressive symptoms at age 16, while preventing everyone from smoking at age 24 in both scenarios (thus setting everyone's smoking frequency to 0). Because smoking frequency is fixed at the same value under both exposure scenarios, any difference in mean HbA1c cannot operate through depression-induced changes in smoking frequency. More generally, the mediator need not be set to 0. A CDE can be defined at any fixed mediator value *M = m*:

$$CDE(m) = E\left\left[ Y^{X = 1,M = m} \right\right] - E\left\left[ Y^{X = 0,\ M = m} \right\right]$$

In this equation, $E\left\left[ Y^{X = 1,M = m} \right\right]$ denotes the mean potential outcome had everyone been exposed and had their mediator set to value *m.* This is compared with $E\left\left[ Y^{X = 0,\ M = m} \right\right]$, the mean potential outcome had no one been exposed while also having their mediator set to the same value *m*. The CDE can also be viewed as a special case of the joint exposure regime effects described in the previous section, with the mediator treated as a second exposure occurring after X.

To identify the CDE, we require the assumptions needed to identify the effect of the joint intervention on X and M. This includes all the assumptions invoked for the TE, but also additional assumptions concerning the mediator intervention. In particular, one must account for confounders of the mediator-outcome relationship (C~3~) as well as confounders of the exposure-outcome relationship (C~1~). Much like the effects of exposure regimes, the estimation of CDEs is more complex in the presence of exposure-confounder feedback (i.e., when some members of C~3~ are influenced by X and are therefore intermediate confounders). In that case, the CDE can still be identified if these confounders are measured and accounted for, but g-methods are typically required for its estimation. In addition to assumptions about confounding, identification requires sequential versions of positivity, consistency, and no interference, which are detailed elsewhere [@refgBdfcUY6_NqCJeKbi].

While CDEs are appealing, a conceptual challenge is that researchers must select the value at which the mediator will be fixed. This matters in the presence of exposure-mediator interaction on the chosen effect measure scale. For example, suppose depression has a more detrimental effect on HbA1c among smokers, perhaps because depressive symptoms activate inflammatory pathways that amplify the metabolic consequences of smoking. The CDE would then differ according to the smoking frequency at which M is fixed. It may also not be obvious which value is most scientifically or practically relevant. A further consideration is that the CDE has no corresponding indirect effect, and therefore does not attempt to decompose the TE [@refgBdfcUY6_R7VUgAt3]. Nevertheless, CDEs can answer policy-relevant questions when fixing the mediator at the chosen value corresponds to a feasible intervention, such as whether intervening on X would provide any additional benefit once M had already been fixed through a separate intervention [see the example in @refgBdfcUY6_ip5S6lpc].

Another related approach to conceptualising the direct effect is the natural direct effect [NDE, @refgBdfcUY6_ap40KqKf; @refgBdfcUY6_4U4YiTkh]. Earlier, we described the general idea behind a direct effect as a thought experiment in which the exposure is changed while any resulting change in the mediator is prevented. The NDE follows this intuition more literally: rather than setting everyone's M to the same arbitrary value, it sets each person's M to the value it would have naturally taken under non-exposure (or under another comparison exposure level for non-binary exposures).

In our example, this means comparing mean HbA1c under two hypothetical scenarios. In the first, everyone experiences high depressive symptoms at age 16, but each person's smoking frequency at age 24 is set to the value it would have taken had they instead experienced low depressive symptoms. In the second, everyone experiences low depressive symptoms at age 16, and each person's smoking frequency is set to that same person-specific value, namely the value it would naturally have taken under low depressive symptoms. More generally, we write:

$NDE = E\left\left[ Y^{X = 1,M = M^{0}} \right\right] - E\left\left[ Y^{X = 0,\ M = M^{0}} \right\right]$

where M^0^ denotes the mediator value under non-exposure. The first term $E\left\left[ Y^{X = 1,M = M^{0}} \right\right]$ is the mean potential outcome had each person been exposed while having their mediator set to its person-specific value under non-exposure. The second term $E\left\left[ Y^{X = 0,\ M = M^{0}} \right\right]$ is the mean potential outcome under non-exposure, with the mediator set to that same person-specific value. Since M^0^ is precisely the value the mediator would naturally take under X = 0, this second term reduces to the mean potential outcome under non-exposure, $E\left[ Y^{X = 0}\right]$.

Importantly, the NDE has an indirect counterpart, the natural indirect effect (NIE). To understand the intuition behind the NIE, it is helpful to revisit the fundamental logic of mediation: the exposure shifts the mediator, and this exposure-induced shift in the mediator then affects the outcome. The NIE attempts to quantify the effect of this shift on the outcome. It starts from a scenario in which everyone is exposed, and then asks how the mean outcome would change if each person's mediator were shifted from the value it would have taken under non-exposure to the value it would have taken under exposure:

$$NIE = E\left\left[ Y^{X = 1,M = M^{1}} \right\right] - E\left\left[ Y^{X = 1,\ M = M^{0}} \right\right]$$

Here, $E\left\left[ Y^{X = 1,M = M^{1}} \right\right]$ is the mean potential outcome under exposure and mediator set to its corresponding value under exposure, and $E\left\left[ Y^{X = 1,\ M = M^{0}} \right\right]$ is the mean potential outcome under exposure while the mediator is set to its value under non-exposure. In our example, this would be the effect of changing each person's smoking frequency from the value it would have taken under low depressive symptoms to the value it would have taken under high depressive symptoms, while keeping depressive symptoms themselves high in both scenarios.

The NDE and NIE align with some of the intuition underpinning traditional mediation analysis. This is reflected in their mathematical properties; for example, they decompose the TE, so that $TE = NDE + NIE$ for effects on the difference scale. Importantly, the NDE and NIE are best considered thought experiments, as some of the hypothetical interventions they represent could not realistically be enacted in the real world.

$$NDE + NIE = E\left\left[ Y^{X = 1,M = M^{0}} \right\right] - E\left\left[ Y^{X = 0,\ M = M^{0}} \right\right] + E\left\left[ Y^{X = 1,M = M^{1}} \right\right] - E\left\left[ Y^{X = 1,\ M = M^{0}} \right\right] = E\left\left[ Y^{X = 1,M = M^{1}} \right\right] - E\left\left[ Y^{X = 0,\ M = M^{0}} \right\right] = E\left\left[ Y^{X = 1} \right\right] - E\left\left[ Y^{X = 0} \right\right] = TE$$

While some properties of the NDE and NIE may seem conceptually appealing, identification of these effects rests on strong assumptions that are implausible in many applied settings. Both the NDE and NIE involve what are referred to as cross-world counterfactuals -- quantities that combine exposure and mediator values from different hypothetical scenarios that cannot be observed together for all individuals. For example, the NDE contains $E\left\left[ Y^{X = 1,M = M^{0}} \right\right]$, where each person's exposure is set to 1, but their mediator is set to the value it would have taken had their exposure been 0. This quantity cannot be observed for any individual whose level of the mediator differs according to the exposure, because we cannot simultaneously observe that person under both exposure and non-exposure. Identifying natural effects therefore requires extrapolating from observed data to these cross-world quantities. This relies on the assumption of cross-world independence. The general formulation of this assumption is beyond the scope of this guide, but in practice, the main implication of this assumption is a requirement of no intermediate confounding: natural effects cannot generally be identified when any mediator-outcome confounder is affected by the exposure.[^43] The violation of this assumption is represented by an arrow from X to C~3~ in [Figure 5.16](#figure-5-16). Even if all intermediate confounders are known and measured, natural effects are generally not identified, and thus they also cannot be estimated, even if g-methods are used.

Apart from the absence of intermediate confounding, identifying natural effects requires accounting for confounders of the exposure--outcome relationship (C~1~), and the mediator--outcome relationship (C~3~), much like identifying the CDE. In addition, one must also account for confounders of the exposure--mediator relationship, C~2~. This is because the NDE and NIE require the conditional distribution of mediator values under exposure and non-exposure (i.e., reflecting the causal effect of the exposure on the mediator) to be recoverable from the observed data. Finally, identifying natural effects also requires extended versions of positivity, consistency, and no interference, which are detailed elsewhere [@refgBdfcUY6_NqCJeKbi].

In applied research, the assumption of no intermediate confounding required for the standard identification of natural effects is often difficult to justify.[^44] Therefore, in many settings, other formulations of the direct and indirect effect that do not make this assumption are more relevant. A popular approach is provided by (randomised) interventional analogues of natural effects, including the interventional direct and indirect effect [IDE, IIE\; @refgBdfcUY6_su7m1iE1; @refgBdfcUY6_TGzKF3iJ]. We provide only a brief introduction to these effects, but readers interested in further intuition and examples are referred to Nguyen et al. [-@refgBdfcUY6_ip5S6lpc].

The interventional analogues follow a similar logic to their natural counterparts but differ in an important way. Intuitively, the NDE and NIE involve personalised hypothetical interventions on the mediator: each person's mediator is set to the value it would naturally have taken *for them* under a particular exposure scenario. Interventional effects instead involve changing the distribution of the mediator, without requiring each person to receive their own person-specific value under that exposure level.

To define these effects, let $G_{x|C}$ be a random draw from the mediator distribution that would arise under exposure level $X = x$ in strata $C = c$. Then, for the binary exposure, we define:

$$IDE = \ E\left[ Y^{X = 1,M = G_{0|C}}\right] - E\left[ Y^{X = 0,M = G_{0|C}}\right]$$

$$IIE = E\left[ Y^{X = 1,M = G_{1|C}}\right] - E\left[ Y^{X = 1,M = G_{0|C}}\right]$$

To illustrate, much like the NIE, the IIE starts from a scenario in which everyone is exposed. It then asks how the mean potential outcome would change if the mediator distribution shifted from that under non-exposure to the distribution that would arise under exposure, within strata of relevant covariates. The IDE instead keeps the mediator distribution at that which would arise under non-exposure (within strata of C) and compares the mean potential outcome when everyone's exposure is changed from 0 to 1.

Under the assumption of cross-world independence, natural effects equal their interventional analogues. When intermediate confounding is present, IDE and IIE can still be identified, as they do not require cross-world independence, but they will no longer coincide with natural effects and no longer decompose the TE.[^45] Additionally, all other assumptions listed for natural effects are still required, and intermediate confounders must be measured and properly accounted for. It is also worth noting that interventional effects answer their own causal questions [@refgBdfcUY6_JczgRvwF; @refgBdfcUY6_tOHRxI4S], and this should be reflected when selecting the target effect and interpreting the findings. Although they may sometimes serve as approximations to natural effects, this correspondence does not hold in general, so using them as proxies should be explicitly justified [see @refgBdfcUY6_uEFnvTbc] or at least noted as a limitation.

Apart from interventional analogues of natural effects, other estimands have also been developed. While discussing all alternatives is beyond the scope of this guide, we note separable effects as an option gaining popularity especially in medical research [@refgBdfcUY6_fqnTXg4u]. These effects may be relevant when one can plausibly separate the exposure, or treatment, into two distinct components that act along different causal pathways: one component that may affect Y only through M, and another component that may only affect Y through pathways not involving M. This assumption may be more plausible for some exposures or treatments that act through relatively well-understood and distinct biological mechanisms [for example, see @refgBdfcUY6_cq0rAZAq].

Another response is to reformulate the question more fundamentally. Natural effects have been criticised not only because of the assumptions they require, but also because they rely on nested counterfactual quantities that do not correspond directly to interventions that could be enacted in a single real-world setting [@refgBdfcUY6_dQLXgHCa]. Related concerns can arise for interventional analogues of natural effects, as the implied intervention on the mediator distribution is challenging to connect to a concrete action. From this perspective, such effects may serve as conceptual tools, but they may not always be the most appropriate targets for actionable input. Researchers may instead focus on causal effects corresponding to more explicitly defined interventions on the exposure, the mediator, or both. CDEs provide one example of such effects, but other joint interventions can also be studied, as outlined in [Section 5.12](05-12-g-methods-for-time-varying-exposures.qmd) [for example, see @refgBdfcUY6_xwb8Ap0v]. Alternatively, other interventional direct and indirect effects may be formulated to correspond explicitly to a hypothetical target trial of specified mediator interventions.

We have covered several options for effects one may focus on when conducting causal mediation analysis and discussed some of their challenges. Importantly, researchers need not choose a single causal effect. If several effects answer substantively meaningful questions, they may be reported alongside one another, provided that their interpretation and identifying assumptions are clearly distinguished. For example, researchers may be interested in the thought experiments represented by natural effects or their interventional analogues, but may also estimate the effects of specified interventions on the exposure, mediator, or both that could plausibly be implemented in practice, thereby providing more directly actionable evidence.

Depending on the target causal effect, different statistical methods may be used for estimation. Although several algorithms and software implementations are available, the choice is more limited in practice when intermediate confounding is present. In these settings, g-methods are typically required. For example, CDEs, IDE, and IIE may be estimated using g-computation, for example with gformula in Stata [@refgBdfcUY6_CT1dSYk3] or CMAverse in R [@refgBdfcUY6_GHMKYCCO]. A causally informed SEM approach has also been proposed for some settings with intermediate confounding, under additional parametric assumptions [@refgBdfcUY6_WXKrNfmS], although g-methods typically offer greater flexibility and are more commonly used in this context.

Research questions may also involve multiple mediators of interest, and extensions are available for such settings [for example @refgBdfcUY6_fENWhzQ7; @refgBdfcUY6_UEAHVudx]. However, broadening the question to distinguish effects involving additional mediators adds further requirements to an already demanding set of assumptions.

Much like analyses of time-varying exposure effects, causal mediation analyses can place substantial demands on the time resolution available in the data and related assumptions. Researchers must carefully consider the temporal ordering of the exposure, mediator, outcome, and any relevant confounders, as well as whether the assumptions required for the chosen causal effect are plausible. Even if only a single mediator is studied, we encourage users to start by asking whether (some form of) causal mediation analysis provides answers that match their substantive questions better than alternatives. If it does, they should then consider whether the available data can support the required assumptions, and whether the research team has sufficient expertise to implement the analysis accurately and interpret the findings appropriately. In some cases, it may be preferable to reformulate the research question around less demanding causal effects, especially when the assumptions required to identify those effects are more defensible.

## 5.13.2 Applications {#applications}

Ning et al. [-@ref21075] perform a particularly impressive study of the effect of early-life adversity upon adolescent mental health using data from MCS. Testing the predictions of a theoretical model, the Dimensional Model of Adversity and Psychopathology (DMAP), the authors estimate indirect effects of two aspects of adversity (deprivation and threat) via cognitive ability and emotional dysregulation, which, according to the DMAP, they are differentially expected to affect. Though they find limited evidence that either dimension of adversity has a net non-zero effect on adolescent mental health, the authors find evidence in support of the DMAP, with deprivation having a stronger indirect effect upon mental health via cognitive ability than via emotional dysregulation, and threat having a stronger indirect effect via emotional dysregulation than via cognitive ability.

The study has several strengths. The authors follow a pre-registered analysis plan, with deviations noted and justified. They also clearly state their estimands and the assumptions under which a causal interpretation can be made. They develop a DAG paying particular attention to the relationships between variables -- for instance, they separate exposure-mediator-outcome and mediator-outcome confounders, and they treat threat as an intermediate confounder of the deprivation pathway. Because natural effects are not identified in the presence of intermediate confounding (see above), they accordingly target the interventional indirect effect for deprivation, estimated using the g-formula, while targeting the natural indirect effect for threat, where no such confounder arises. Finally, they use a child-reported, rather than parent-reported, measure of adolescent mental health, given concerns with the accuracy of the latter; they note this decision may have meant they observe no net (total) effect of adversity upon the outcome.

Hope et al. [-@ref21076] use MCS data to assess the effect of hypothetical interventions to reduce social inequalities in childhood mental health problems (MHP). Though it may not immediately appear so, this can be treated as a mediation question. Using marginal structural models, the authors first estimate the controlled direct effect of income upon childhood MHP with parenting practices treated as a mediating factor and fixed at observed levels. They then simulate the effect of interventions that improve parenting practices by re-estimating the CDE at predicted values for the mediator; the intervention may thus narrow inequalities by reducing differences in this mediator between groups. A key strength of their study is that the hypothetical interventions they evaluate vary in their effectiveness, uptake, and targeting (e.g., offered to families on means-tested benefits only), with these parameters selected based upon reviews of the literature (e.g., meta-analyses of the effectiveness of parenting interventions) and expert discussions (e.g., on plausible targeting strategies). A limitation is that they do not account for potential reverse causality between (early) child mental health problems and parenting behaviour.

Pinto Pereira et al. [-@ref21062] -- discussed in [Section 5.12.2](05-12-g-methods-for-time-varying-exposures.qmd#applications) -- assess mediation of the effect of early- and mid-adulthood obesity upon mid-life physical function using data from the NCDS and the NSHD. Using the parametric g-formula to estimate IDE and IIE for different treatment regimes (never obese, persistent obesity, and obesity beginning at particular ages), they find little of the total effect is mediated via physical activity. However, as the authors note, an issue is their dichotomous measure of physical activity, which may have little discriminant validity, thus biasing estimates of the indirect effect towards the null.

## 5.13.3 Opportunities {#opportunities}

The attributes of CLS's cohorts discussed in [Section 5.12.3](05-12-g-methods-for-time-varying-exposures.qmd#opportunities) also make the data well suited for causal mediation analyses. Specifically, the availability of multiple data collections and the breadth of data collected overall mean that temporal ordering can be established and there are variables for many important mediators and time-varying confounders. Data collection from birth and the repeated measurement of the same characteristic mean measures for many baseline confounders are also available (e.g., pre-exposure measures of mediators).

- 

[^43]: The requirement of no intermediate confounding is the main practical implication of cross-world independence. However, cross-world independence is a broader assumption and is not identical to the requirement of no intermediate confounding. For technical details, see Andrews & Didelez [-@refgBdfcUY6_p6SijbvQ].

[^44]: In some cases, cross-world independence may be replaced with additional parametric assumptions instead [@refgBdfcUY6_PTngU6qp], although these alternative assumptions may be equally implausible in many applied settings. Alternatively, one may forego point identification and instead estimate bounds or run a sensitivity analysis to obtain a model-based range of plausible effects [@refgBdfcUY6_IcaL14jz; @refgBdfcUY6_fENWhzQ7]. These approaches can be more demanding to implement and interpret compared to approaches relying on point identification, and they remain uncommon in applied research.

[^45]: Specifically, as $E\left\left[ Y^{X = x,M = G_{x|C}} \right\right] \neq E\left\left[ Y^{X = x} \right\right]$
