# 5.11 Target Trial Emulation {#target-trial-emulation}

## 5.11.1 Method {#method}

So far, we have mainly discussed the benefit of the randomised controlled trial (RCT) design as its use of randomisation to achieve exchangeability. But RCTs have additional features that are beneficial for causal inference [@ref241]. Specifically, they encourage the individuals involved in designing the RCT to ask well-defined causal questions by specifying study design and analysis plans that realise these questions as *estimands* (quantities one wishes to estimate); as discussed in [Section 2.1](02-problem.qmd#correlation-causation-what-next), clearly stating the estimand one wishes to estimate is a key component of any good causal research.

RCT study designs detail the eligibility criteria for the study participants, the treatment strategies that will be compared, the method of treatment assignment, the outcomes of interest, the start and end of follow-up, the causal contrast of interest, and the analysis plan. These components, when combined (and written well), enumerate the population, exposures and outcomes of interest for which a causal comparison is to be made. For instance, an RCT of COVID-19 vaccination on mortality may include individuals if they have not had a vaccine or COVID-19 infection so far, compare two dosages of active vaccine vs. placebo, assigned randomly, with mortality rates determined five years post-randomisation. Comparing survival rates in vaccination vs. placebo groups would provide an intention-to-treat estimate of the effect of the vaccine on mortality assuming no differential loss to follow-up.

Not every failure of observational studies arises due to problems with the underlying process that generated the data (e.g., confounding, measurement, and response biases). Some are "self-inflicted" due to decisions that are made by the data analyst in the design of their study [@ref243]. Notable among these are decisions relating to eligibility, treatment assignment, and the definition used to begin follow-up time ('time zero'). Where these do not coincide, there is the potential for one of two related but distinct forms of selection bias: immortal time bias and prevalent (or 'healthy') user bias [@ref243].

Immortal time bias occurs when treatment assignment is determined *after* the start of follow-up (*time zero*). Most commonly, this occurs whenever the treatment is defined in relation to a minimum amount of time, e.g., if participants taking anticoagulants only count as 'treated' when they have been taking the medication for at least 5 days. Anyone who dies between the start of treatment and the designated time required to achieve 'treated' status will not be eligible for classification as 'treated', making this time 'immortal' as no deaths (or other outcomes of interest) can occur in this group during this time. In contrast, the 'untreated' group does not require a minimum amount of time to count as 'untreated' and all events occurring during this period are counted as normal. Since the 'treated' group has already survived a minimum required period that does not apply to the 'untreated' group, any apparent benefit of treatment may be overestimated as an artefact of this immortal time.

Prevalent user bias (also known as 'depletion of susceptibles') arises when treatment assignment occurs *before* the start of follow-up. Most commonly, this occurs in observational settings where comparisons are made between 'exposed' ('treated') and 'unexposed' ('untreated') individuals (e.g., those with and without heart disease). In this setting, the 'treated' must remain 'treated' long enough to make it into the sample at the start of follow-up. Any events occurring due to treatment before the start of follow-up would be missed and undercounted in the 'treated' group. For instance, when studying the effect of unemployment on depression, those whose mental health deteriorates soon after job loss may make greater effort to find a job quickly or may leave the labour force entirely. The individuals observed as unemployed at the start of follow-up (rather than the start of unemployment), then, would be disproportionately made up of those who are unaffected by unemployment's deleterious effects ([Figure 5.14](#figure-5-14)).

::: {#figure-5-14}

![**Figure 5.14:** Causal DAG representing prevalent user bias in an observational study where treatment assignment is determined prior to follow-up time (time zero; T=0). In the DAG, exposure is measured at time-zero, but exposure can be initiated before this point (X~T=-t~). Remaining exposed (R~T=0~), which is implicitly conditioned upon in the study design, may be related to confounders as well as mediators on the path between X~T=-t~ and Y.](images/image31.png){width="31%"}

:::

The more harmful the exposure is and the longer the time between exposure initiation and start of follow-up, the more likely it is for those susceptible to the outcome to be depleted from the treated group sample. Prevalent user bias is a particular challenge with cohort data because of the length of time between data collections -- participants may be more likely to experience a harmful exposure and then experience the outcome, or drop out of the study, before their exposure status is collected at the next wave. Note, prevalent user bias can affect both internal and external validity as (regarding internal validity) remaining exposed is a potential collider variable ([Figure 5.14](#figure-5-14)) and (regarding external validity) treatment effects may vary depending on 'susceptibility'.

These self-imposed analytical mistakes have generated several notable failures in observational research. For instance, Hernán et al. [-@ref244] show that the supposedly protective effect of hormone replacement therapy on coronary heart disease, identified in observational studies but not RCTs (which found the opposite), disappears when prevalent user bias is avoided. It is thought that those most susceptible to death after HRT initiation will have been depleted from the sample before the start of follow-up, meaning the protective effect seen in many observational studies is due to prevalent user bias. Dickerman et al. [-@ref242] show the protective effect of statins on lower cancer rates arises due to a combination of immortal time bias and prevalent user bias. First, existing studies compared long-term statin users with non-users, where long-term users were defined as those with at least 4 years of statin use. Those who go on to be classified as long-term users must have therefore survived during this period without developing cancer (introducing immortal time bias). In addition, existing studies also included those already on statins before the start of follow-up, which may have led to depletion of susceptibles (introducing prevalent user bias).

The target trial emulation (TTE) framework [@ref1247] specifically attempts to avoid such design biases by emulating the features of an RCT.[^36] In particular, TTE involves specifying the protocol for a hypothetical ('target') trial, including eligibility criteria, treatment assignment procedures, follow-up, outcome, estimand, and analysis plan.[^37] This protocol is then used to design a second protocol, detailing the design of the observational study which will be used to emulate the hypothetical target trial [@ref241]. This mapping is iterative and based on what is possible with the data -- it does not recreate an ideal RCT that one may wish had been run, and some features of an RCT, such as treatment allocation blinding and explicit randomisation, will not be possible to emulate (i.e., the target trial may often be a 'pragmatic trial'). Preparing data for a target trial emulation can involve significant data wrangling (e.g., restricting to an eligible sample). For instance, to assess the effect of job loss on mental health, data may be restricted to those in continuous employment before exposure 'assignment'.

The TTE does not map to a single statistical method -- instead it is a framework for designing studies and defining estimands. As such it can be used alongside -- or rather, specify the use of -- any of the methods (e.g., regression adjustment), study designs (e.g., Regression Discontinuity Designs), and falsification tests (e.g., negative controls) discussed elsewhere in this document. Just like an RCT, TTE can be used to estimate a range of estimands. In an RCT, the intention-to-treat effect estimates the effect of being *assigned* to a treatment, regardless of adherence. Typically, the observational analogue of the ITT is the effect of *initiating* a treatment, regardless of adherence during follow-up. In an RCT, there may also be a range of estimands of interest which involve being assigned to treatment *and* adhering to it for the duration of follow-up (traditionally referred to as 'per protocol' effects). However, just like an RCT, there is no single 'per protocol' effect and the exact adherence strategy and therefore estimand must be pre-specified in advance. This requires appropriately accounting for post-treatment confounding and selection, including any time-varying confounding. This is discussed further in [Section 5.12](05-12-g-methods-for-time-varying-exposures.qmd).

TTE is popular in pharmacoepidemiology and with large-scale health record data, but it is increasingly used in other fields, including social epidemiology and criminology [see, e.g., @ref20819; @ref20821]. It has also been applied in cohort data, including the CLS cohorts (see below). Cohort data have the advantage that variables are measured repeatedly which can make it possible to restrict eligibility to individuals without exposure prior to time zero, though as mentioned previously, the time gap between data collections can cause issues. Repeated measurement also allows for a nested trial design, where individuals are entered into multiple successive 'trials' until they become exposed.

A final benefit of the RCT design that is naturally encouraged by the TTE framework is specifying a well-defined intervention that can, hypothetically, be assigned experimentally. In observational studies, it is often unclear what the equivalent intervention may be, and hence the interpretation of the causal effect one is actually estimating [@ref826]. For instance, a researcher may wish to estimate the effect of body mass index (BMI) on stroke. However, it is not straightforward to 'assign' a certain BMI, even in a trial. Instead, different levels of BMI can be achieved via numerous interventions (e.g., diet, exercise, Ozempic, amputating a limb). The same change in the exposure (e.g., transitioning from BMI of 30 to BMI of 25) can therefore be achieved through different means, each of which may have distinct effects on the outcome (stroke), making the estimand (the causal effect being estimated) unclear. Since the effect will be a mixture of different possible interventions, it has limited practical utility and limited transportability. This problem is much more easily avoided when we attempt to conceptualise the exposure as a hypothetical intervention as it explicitly encourages us to think about well-defined causal contrasts with clearer interpretations.

## 5.11.2 Applications {#applications}

Vagni [-@ref21099] uses data from BCS70 to estimate the causal effect of becoming a mother upon social class (the 'Motherhood Class Penalty'). The author uses an explicit TTE framework to define the exposure, outcome, eligibility criteria, time zero, and the estimand of interest. Comparator women (women who remain childless at age 46) are identified by matching upon Mahalanobis distance with a novel use of sequence analysis [@ref2800] to identify pairs of treated and untreated individuals with similar pre-motherhood class trajectories. The author finds that motherhood has a large effect on class mobility, with mothers facing long-term lower likelihood of attaining or remaining in professional occupations following childbirth. Strengths of the study include: the clear and transparent statement of the study design, estimands, and assumptions; the use of external data (Annual Population Survey and British Household Panel Survey) to assess potential bias from attrition; and the use of data visualisations to display the results and provide compelling evidence estimates are causal (e.g., showing estimated differences in occupational class are confined to the post- and peri-childbirth period).

## 5.11.3 Opportunities {#opportunities}

The TTE approach is relatively underutilised in CLS cohort data, despite the cohorts having several features making the approach tractable (as noted above), including longitudinal assessment to determine eligibility and to implement nested trial designs to increase statistical power.

[^36]: TTE is sometimes referred to as the pseudo-trial design.

[^37]: Note, as the allocation procedure in observational data is not randomisation, the target trial protocol sets out the steps designed to estimate the target estimand (e.g., regression adjustment or use of an IV).
