# 5.15 Negative Control Outcomes and Exposures {#negative-control-outcomes-and-exposures}

## 5.15.1 Method {#method}

In [Section 3.3](03-approaches.qmd#elaborate-theories), we discussed making theories "elaborate" as a way to support causal inference. A broad concern in observational research is that an exposure, X, may be associated with an outcome, Y, due to an unobserved -- or poorly measured -- confounding factor, U. That the exposure and outcome are materially confounded by U is a competing theory to the possibility that the exposure has a causal effect on the outcome.

Competing theories should be treated seriously; one way of treating a competing theory seriously is to ask what predictions it makes about the world. A given confounding process may imply a larger set of associations than simply a spurious one between X and Y. For instance, the confounding factor may generate an association between X and a larger set of outcomes, or between Y and a larger set of exposures. But these associations may not be predicted by the central theory that X causes Y, and there may be no plausible reason the alternate exposure would cause Y or X would cause the alternate outcome.

::: {#figure-5-18}

![**Figure 5.18:** Negative control outcome and negative control exposure design. (a) We are interested in the causal effect of X upon Y, but anticipate there may be confounding via a common (unmeasured) cause U. Any association between X and Y could reflect this confounding pathway. (b) U may also be a common cause of another 'negative control outcome' (Y~NC~) which we have good reason to expect X would not have a causal effect on. Any association between X and Y~NC~ would therefore reflect the confounding by U. (c) U may additionally be a common cause of another 'negative control exposure' (X~NC~) which we have good reason to expect does not have a causal effect on the outcome of interest, Y. Conditional on the exposure of interest (X), any association between X~NC~ and Y would therefore reflect the confounding by U. Note, in practice, some confounders may be measured, and these would be conditioned upon in the negative control analysis.](images/image35.png){width="100%"}

:::

The negative control exposure and outcome designs encapsulate this logic (Lipsitch et al., 2010).[^46] In the negative control *outcome* design ([Figure 5.18b](#figure-5-18)), a 'placebo' outcome, Y~NC~, is identified which should only have an association with X through a confounding factor U that is thought to bias the association between X and Y. If an association is observed between X and Y~NC~, this may indicate the main study analysis is biased by U.[^47] To take an example, let's say we are interested in the effect of breastfeeding on child cognitive development (Lawlor et al., 2016). Breastfeeding is strongly socially patterned in the UK, with more socioeconomically advantaged parents more likely to breastfeed; an association between breastfeeding and child cognitive development could therefore be expected due to higher socioeconomic position (SEP) of parents or even direct heritability of cognitive ability. But SEP is difficult to measure accurately, so residual confounding may persist even if measured SEP is controlled for. Home invasion by mice during childhood is also socioeconomically patterned, but we would not expect it to be influenced by breastfeeding. Home invasion by mice is therefore a plausible negative control outcome because any association with breastfeeding should be spurious rather than causal. What's more, it would be spurious for similar reasons that a link between breastfeeding and child cognitive development could be spurious.

The negative control *exposure* design is similar ([Figure 5.18c](#figure-5-18)), but in this case a 'placebo' exposure, X~NC~, is identified that should not have a causal effect on the outcome but would be likely confounded by the same factors as X, the exposure of interest. An example of a negative control exposure design is using paternal smoking to assess whether maternal smoking during pregnancy has a causal effect upon child health, in cases where the smoking is hypothesised to have an effect by influencing the intrauterine environment. As mothers' but not fathers' behaviour has a direct effect on the intrauterine environment, one would expect to see specific associations between mother's smoking and child health. On the other hand, as both mother's and father's smoking are patterned socioeconomically, a countervailing theory that associations are driven by confounding through SEP would also predict an association between father's smoking and child health. Thus, if paternal smoking is related to offspring outcomes (conditional on maternal smoking), it would suggest an association between maternal smoking and child outcomes is also biased (Brion et al., 2007).[^48]

Negative control designs are sometimes referred to as placebo, specification or falsification tests (Eggers et al., 2024). The success of the negative control outcome and exposure design depends on the negative control sharing the same confounders as the true exposure or outcome of interest -- referred to as 'U-comparability' (Lipsitch et al., 2010). Since it refers to unobserved confounders, the assumption of U-comparability is untestable. In practice, the proposed negative control(s) may only share part of the confounding structure. In the absence of full U-comparability, an observed association with the negative control will not necessarily indicate residual confounding in the X--Y association, and a null association with the negative control will not necessarily indicate absence of residual confounding. Nevertheless, the negative control design may still provide useful information on the presence or absence of bias on major confounders -- e.g., on SEP, as in the examples above.

It is not just the presence of the confounders, but similarity in the strength of their relationship with the true and negative control exposures or outcomes that is important. For instance, given the additional possible health risks of smoking during pregnancy, one may expect greater selection into smoking among mothers, compared with fathers. For this reason, a negative control test may represent only a weak test of the competing theory. Showing an association between the negative control and true exposures or outcome would suggest the true exposure-outcome association is biased, but the reverse may not be true: not finding an association with the negative control is not necessarily dispositive evidence that the true exposure-outcome association is unbiased.

In practice, it may be difficult to identify negative controls that have no causal association with the true outcome or exposure, whatsoever. For example, it is possible that father's smoking influences the intrauterine environment, albeit indirectly via the mother inhaling smoke second-hand. In this case, the pattern and overall size of associations would be informative, rather than only observing a null association for the negative control: given father's effects on the intrauterine environment should be weaker than mother's, we would expect child health to (a) have a weaker association with father's smoking than mother's smoking and (b) for the absolute size of the association with father's smoking to be small. Otherwise, strong confounding bias is likely to be present.[^49]

The negative control method can therefore involve a degree of uncertainty for the analyst and require some persuading of the reader. Operating under this uncertainty requires discipline and transparency as it can be tempting to spend "researcher degrees of freedom" (Simmons et al., 2011) in light of inconvenient results -- one should not jettison a negative control analysis after seeing the results, if the results motivate one to think 'maybe the confounding structures are not quite the same' or 'perhaps there is a causal relation the association represents'.

Nevertheless, there are general strategies for identifying plausible negative controls. These focus on finding situations where a hypothesised *active ingredient* linking exposure and outcome is missing or an essential mediating pathway is not present (Lipsitch et al., 2010; X. Shi et al., 2020) or, less restrictively, is weaker. The *parental comparison design* (Davey Smith, 2008; Richmond et al., 2014) used in the smoking example above follows this logic, and is frequently used in settings where maternal exposures are expected to operate via the intrauterine environment given fathers do not influence this directly. In pharmacoepidemiology, negative control outcomes can be relatively straightforward to identify as treatments may be expected to have causal effects on only a limited set of health outcomes. For instance, flu vaccination, which would plausibly reduce hospitalisation rates due to respiratory problems, should not lower rates of hospitalisation due to injury or trauma (L. A. Jackson et al., 2006).

Another strategy is to take measurements from periods where the exposure should not have an effect on outcomes -- for instance, flu vaccination should not have an effect on hospitalisation prior to, or after, flu season, when vaccination might actually cause illness to be avoided (L. A. Jackson et al., 2006). Using outcome measurements prior to exposure or exposure measurements post outcome can also represent expressions of this idea -- for instance, a future measurement of environmental pollution when looking at hospital admissions for asthma (Flanders et al., 2011). Height, which has been repeatedly used as a negative control outcome in the health and social sciences (Cohen-Cole & Fletcher, 2008; L. Wright, 2020; L. Wright et al., 2021), can have this property as it is largely set from late adolescence. It is also very highly heritable, so large associations with environmental factors (within a population) are likely spurious. Cohen-Cole & Fletcher (2008) show that in addition to obesity 'spreading' between friends in social networks (Christakis & Fowler, 2007), so do height, acne and headaches.

Negative control tests are routinely used in some particular study designs. For instance, as discussed in [Section 5.10](05-10-regression-discontinuity-designs.qmd), sharp RDD studies typically exploit a placebo test, where arbitrary cut-offs in the running variables are chosen that are known to have no bearing on treatment, but could still be related to unmodelled confounders. Sanderson et al. (2021) discuss using phenotypes determined prior to outcome and exposure as negative controls in MR studies, e.g., tanning ability and hair colour.

So far, we have described negative control designs for detecting bias from unobserved confounding. But negative controls can also be used to detect selection and measurement biases (Arnold et al., 2016); regardless of the source of bias, the purpose of the negative control exposure and outcomes is to identify variables that have similar (hypothesised) biasing structures to the main association of interest. For instance, recall biases can generate spurious associations between exposure and outcome if the accuracy of recall of exposure is related to the outcome (e.g., disease cases more likely to remember a childhood ailment). Yet, recall bias may also apply to negative control exposures that have no plausible causal effect on outcomes. Zaadstra et al. (2008) examine recall bias in a study of multiple sclerosis (MS) using negative control exposures for broken limbs, concussion, and tonsillectomy, each of which is not expected to have a causal effect upon MS. Returning to genetics studies, sex is a particularly useful negative control when using polygenic scores as these are typically calculated from autosomal (i.e., non-sex-specific) chromosomes; any association with observed sex must therefore be due to selection bias.

Negative controls can be used not just for bias detection, but also bias correction or reduction (X. Shi et al., 2020; Yang et al., 2024). Again, strength of association between negative controls and true outcomes and exposures can be revealing. For instance, VanderWeele (2011) notes that although height, acne and headaches are correlated within friendship groups (Cohen-Cole & Fletcher, 2008), the size of this correlation is lower than that for obesity, and so greater confounding would be required to explain the obesity spreading hypothesis.

## 5.15.2 Applications {#applications}

Libuy et al. (2024) use MCS data to assess the effect of changing proximity to fast food restaurants on weight gain. Given fast food restaurants are spatially patterned, they use proximity to several other types of commercial establishment (e.g., employment and career agencies) as negative control exposures, arguing that time-varying changes in these might reflect unobserved confounding processes, such as gentrification. However, the plausibility of the assumption behind the negative control analysis is not explored and other types of commercial establishment not examined could feasibly more closely share confounding structures with fast food restaurants (e.g., betting shops). Hamer & Batty (2020) used data from BCS70 to investigate the association between infection requiring hospital admission and later diabetes risk, using non-infectious reasons for admission as a negative control exposure. This has a more plausible common confounding structure (e.g., health consciousness).

Tabor et al. (2025) use data from MCS and BCS70 alongside data from other cohorts to examine the effect of sexual minority status on asthma. Their theory suggests effects should only occur in adulthood so they use childhood asthma as a negative control outcome, an application of the idea that measures prior to plausible causal effects occurring can be used as negative controls. Wright et al. (2021) use data from Next Steps to assess the effect of youth unemployment on later mental health, using height and patience as negative control outcomes. A question in both papers is whether confounding structures are sufficiently similar to the focal associations of interest.

## 5.15.3 Opportunities {#opportunities}

Given data collection from parents and children, including on characteristics prior to the cohort members' births, there are ample opportunities to employ the parent comparison design in CLS cohorts. The cohorts have each collected data on a wide variety of factors and traits, which may be useful more generally (e.g., height, suncream use, etc.). Data linkages also increase the possibility for negative control designs, including links with health record data, enabling assessment of multiple health outcomes, which can serve as negative control outcomes. A variety of data on health outcomes is also collected in standard survey data collections. Longitudinal measurements add further possibilities as there is ample pre-exposure measurement of many variables. Finally, there is also an opportunity for research-enabling activity reviewing plausible negative controls and determining their possible use in CLS data.

[^46]: Another negative control design -- negative control *populations* (Piccininni & Stensrud, 2024) -- is discussed further is [Section 5.16](05-16-cross-context-analysis.qmd).

[^47]: Sanderson et al. (2021) note the negative control outcome renames Austin Bradford Hill's (1965) 'specificity of association' criteria for assessing causation. The flip-side of specificity is coherence among outcomes (Rosenbaum, 2019) -- some variables can be used as "positive controls" to determine that statistical models perform as expected (Gutierrez et al., 2025).

[^48]: Conditioning on maternal smoking is required as the X~NC~-Y is additionally confounded by the path X~NC~ ← U → X → Y if a causal effect of X upon Y exists.

[^49]: The utility of examining patterns of association ("pattern matching") was discussed in [Section 3.3](03-approaches.qmd#elaborate-theories), where we noted how associations between measures of socioeconomic position (SEP) and health should follow a particular pattern of association if explained by cognitive ability, a hypothesised confounder of that relationship.
