# 5.17 Biases of Known Direction {#biases-of-known-direction}

## 5.17.1 Method {#method}

Though it would be optimal and most useful to identify a precise and unbiased causal estimate, sometimes only determining the overall direction of a causal effect or that it exceeds a minimum effect size is sufficient or still insightful. A valid test of a theory may be that X increases Y, however large or small (though it is of course usually better to know that X is an important causal factor of Y), and one may only need to know that a causal effect exceeds some defined quantity to make a good decision -- for instance, knowing that an intervention will yield higher benefits than the alternative. Health economists have a useful concept, 'value of information', which denotes the higher expected utility one would obtain if able to make decisions on more accurate data (Tuffaha et al., 2014); if decisions are unlikely to change following further data collection, then the information collection does not have much value instrumentally. Analogously, in some circumstances, one may be satisfied with a biased estimate of a causal effect if removing the bias would not yield further valuable information.

While the precise extent of a bias may not be known, its direction may be guessed at with high certainty, and this can be used to draw causal inferences even where biases are present and acknowledged (Rosenbaum, 1989, 2020). For instance, an observed positive association will only get larger if a confounding factor positively related to X but negatively to Y (or vice versa) were controlled for. Readers will be aware of this type of reasoning -- it appears frequently in discussion sections of papers where authors note the possibility of a source of bias but discard its importance as it implies the observed association is a conservative (under)estimate of a true causal effect. One oft-repeated case of this is independent, non-differential (i.e., classical) measurement error in the exposure variable which, in expectation, should bias an association towards the null, proportionate to the size of the measurement error (i.e., regression dilution).

Biases of known direction need not only enter at the interpretation stage of a study -- they can also motivate study design. One example of this is to choose a setting in which confounding structures run opposite to a hypothesised causal effect -- for instance, in many developing countries, obesity is related to higher socioeconomic status (Dinsa et al., 2012), so observational estimates of the causal effect of obesity upon health conditions are likely biased towards the null. Another possibility is the judicious choice of a comparator group that provides a greater hurdle for a causal effect to surmount. For instance, in a study examining the effect of banning individuals with prior convictions from purchasing guns (and discussed in Rosenbaum, 2020), Wright et al. (1999) compare rates of violent crime among those affected by the law against individuals who had previously been arrested for a crime but found not guilty; one may expect that, if both were able to purchase guns, those who have been convicted of crimes would have a greater likelihood of committing further crimes than those only previously suspected of criminality.

Exploiting biases of known direction can be especially compelling when it is possible to obtain two or more estimates biased in opposite ways, in which case these estimates can provide an upper and lower bound to "bracket" the true causal effect. The main way this can be achieved is through the use of multiple comparator groups (Rosenbaum, 1987). For instance, in the difference-in-difference design ([Section 5.6](05-06-difference-in-differences.qmd)), such a bracketing analysis would work by identifying comparator groups who violate the parallel trends assumption, one anticipated to have stronger time trends than the treatment group and one to have weaker time trends than the treatment group (Ye et al., 2024).[^50] Hasegawa et al. (2019) bracket the effect on homicide of the repeal of a Missouri state law requiring a background check for gun purchases using two groups of comparator states that had either higher or lower homicide rates than Missouri prior to the repeal of the law.

Exploiting biases of known direction is not without its problems, however. Most obviously, in many cases it may not yield any useful information because it would suggest an estimate is anti-conservative (i.e., if anything an association is biased away from the null). Examples of this abound -- for instance, in studies of the effect of socioeconomic position on health, both causal and confounding (health-related selection) anticipate poorer health in more socioeconomically deprived groups. Additionally, it may not be straightforward to identify comparator groups biased in opposite directions (and thus obtain a bracket for the causal effect), or the resulting bracket may be too wide to be useful.

In other cases, only one bias may be known but others not, and it may not make sense to emphasise the one known factor. This is particularly the case where biases interact, yielding unclear direction of bias on aggregate. For instance, bias from classical measurement error is not necessarily towards the null where there is unobserved confounding (Smith & Phillips, 1996).[^51] Given incentives within academia to overclaim evidence for a proposition, it is possible for motivated reasoning to lead authors to focus attention on those known biases that lend support, rather than those that don't (Fox et al., 2021).

## 5.17.2 Applications {#applications}

Ermisch & Pevalin (2005) use data from the BCS70 to assess the effect of teenage parenthood upon partnership status and partner quality at age 30y. They use multiple comparison groups, including women who did not have a teenage birth and -- using miscarriage as an IV -- women whose teenage pregnancy ended in miscarriage. Though not reported so explicitly, using miscarriage as an IV could bias towards a "benign view" of teen motherhood (Ashcraft et al., 2013) as miscarriage can occur due to factors related to poorer outcomes in general (e.g., smoking and alcohol consumption), whereas teen mothers tend to have worse outcomes than other women more generally, even if they hadn't had a child. Provided no other biases are present, the OLS and IV estimates therefore arguably bracket the true causal effect.

## 5.17.3 Opportunities {#opportunities}

Whether the method can be applied in CLS's cohorts depends on the specific research question as the direction of known biases depends on information that is *not* captured in the data collection. Assessing this requires domain-specific knowledge. A key benefit of CLS's cohorts is the depth of data collection and the sample size which means multiple comparator groups can be defined.

[^50]: Ye et al. (2024) provide formal estimation procedures for difference-in-difference bracketing analyses.

[^51]: It is also worth noting that for classical measurement error the phenomena of attenuation towards the null is true in expectation but may not be true in a given circumstances, so the bias of 'known effect' is actually unknown (Fox et al., 2021).
