# 5.19 Reasons for Effects {#reasons-for-effects}

## 5.19.1 Method {#method}

Theories that predict a causal effect of an exposure on an outcome typically invoke a set of mechanisms linking the two. One way of making a theory elaborate is to consider intermediate effects. For instance, the theory that cognitive ability improves health by influencing health-related decision making assumes that (a) cognitive ability influences health-related decision making and that (b) decision making influences health. While it may be difficult to directly empirically assess the causal effects of cognitive ability upon health, in general, these 'reasons for effects' provide extra targets for empirical study [@ref75; @ref454]. A causal theory may fail at the first step, if no link between intermediate factors can be shown. For instance, one may discard a hypothesis that blood alcohol limits reduce car fatalities by disincentivising drink-driving, if these limits have no observed effects on drivers' drinking behaviour.

One advantage of subjecting reasons to empirical scrutiny is that certain links in a causal chain may be more amenable to causal effect estimation or to more persuasive testing than others. For instance, in their sociological study of diabetes patients, Lutfey & Freese [-@ref5112] provide compelling evidence of the difficulties individuals with lower cognitive resources have in managing the illness. From there, if one is interested in the effect of cognitive ability upon diabetes survival, one needs to establish that poor disease management negatively affects prognoses, which some might consider self-evident. Consider also papers that repeatedly show that youth unemployment is related to poorer mental health later in life [see @ref591, for a review]. This association is hypothesised to partly reflect youth unemployment having a deleterious long-term effect on labour market outcomes -- i.e., individuals who were previously unemployed may have poorer mental health later because they are more likely to earn low wages at the point of measurement of mental health. One would therefore expect youth unemployment to negatively affect labour market prospects. This can be tested experimentally, albeit in a somewhat artificial way, with correspondence studies -- a type of field experiment in which curricula vitae (CVs) are sent to real-world employers and interview offers recorded. These CVs are manipulated and sent randomly to determine the effect of applicant attributes on job prospects. For instance, CVs may vary in whether an individual has experienced an episode of unemployment [@ref3120]. Thus, while the main estimate of interest may be biased, one can still have good, empirically well-supported reasons for thinking a causal effect exists. Indeed, because of their expense, RCTs frequently use surrogate outcomes -- outcomes preceding the true outcome of interest (e.g., blood pressure in an RCT of a drug designed to reduce cardiovascular disease mortality) -- on the logic that established 'reasons for effects' will translate into clinical outcomes.

Reasons for effects are conceptually similar to Bradford Hill's [-@ref1509] 'criterion' of "biologic plausibility" and form further pieces of evidence to assess whether an association of interest is causal. To be clear, here the object of inquiry is independent assessment of the effect of the exposure upon intermediate outcomes, or intermediate outcomes upon final outcomes or even other intermediate outcomes, in the causal chain, rather than performing a mediation analysis.

There are four issues with solely relying on 'reasons for effects'. First, there may be several mechanisms of action -- cognitive ability is proposed to influence health not just through decision making, but also by affecting socioeconomic position [@ref1391]. Discounting one mechanism does not mean causal effects may not be transmitted through other pathways [@ref74], including pathways that have not yet been thought of. Second, mechanisms may counteract, producing an unknown aggregate effect -- this indeterminacy may in fact be motivation for assessing total causal effects empirically in the first place. Third (and related), assessing reasons for effects does not straightforwardly translate into determining effect sizes. Rather, it most straightforwardly informs qualitative judgements about a causal effect being present or not, limiting its usefulness, especially given effects may need to be of a certain minimum size to be practically important.

Fourth, the populations used to estimate effects at each step along a causal chain may vary and results may not generalise across these. It is possible that the overall chain may be broken for the target population of interest. For instance, one may observe a causal effect of youth unemployment on short-term employment prospects and a later effect of contemporaneous income on obesity at age 50 years, but by age 50 years, any labour market disadvantage arising from an episode of youth unemployment may be compensated for (e.g., through faster within-firm job promotions once a job is found).

## 5.19.2 Applications {#applications}

Decades of research has shown that socioeconomic and psychosocial adversities are related to poorer health outcomes [@ref1506]. Major theories conceptualise adversities as stressors that, experienced chronically, alter and cause "wear and tear" of multiple systems within the body's regulatory systems [cardiovascular, metabolic, immune, etc.\; @ref2305] and lead to a state of chronic inflammation. Wear and tear is operationalised as measures of "allostatic load", which combine measures of biomarkers across multiple systems, while chronic inflammation is most commonly indexed by elevated levels of C-reactive protein (CRP). Several studies have used data from the biomedical sweep of the NCDS to examine associations between socioeconomic [@ref71] and psychosocial [e.g., adverse childhood experiences\; @ref73; @ref72] adversity and allostatic load or CRP, in an effort to provide mechanistic understanding of the association between these adversities and clinical health outcomes. While these studies show such associations, issues are that (1) chronic stress is only one pathway and (2) the same factors that may confound the association between adversity and health plausibly also confound the association between adversity and allostatic load and CRP. Counterclaims would make the same set of predictions; biases are replicated [@ref69].

## 5.19.3 Opportunities {#opportunities}

Given the rich data collection reflected in CLS's cohorts, data related to causal mechanisms may be available (e.g., on biomarkers, health behaviours, and so on).
