# 5.20 Quantitative Bias Analysis {#quantitative-bias-analysis}

## 5.20.1 Method {#method}

> There is a quantitative question. Cigarette smokers have a ninefold greater risk of developing lung cancer than nonsmokers, while over-two-pack-a-day smokers have at least a 60-fold greater risk. Any characteristic proposed as a measure of the postulated cause common to both smoking status and lung-cancer risk must therefore be at least ninefold more prevalent among cigarette smokers than among nonsmokers and at least 60-fold more prevalent among two-pack-a-day smokers. No such characteristic has yet been produced despite diligent search.
>
> Cornfield et al. [-@ref513]

In [Section 5.17](05-17-biases-of-known-direction.qmd), we discussed approaches to exploiting biases of known direction to support causal inference. These approaches incorporate information on bias qualitatively -- e.g., to identify appropriate groups for study, contexts to draw data from, or to ascertain in which direction an estimate is likely to be biased. A drawback with this approach is that it does not allow the analyst to determine by how much an estimate is likely to be biased or what an unbiased estimate would plausibly look like. It is also not useful in situations where bias runs in the same direction as the anticipated causal effect or where the causal effect is hard to predict *a priori* -- in these cases, a given estimate would be compatible with a null or opposite signed effect.

As the name suggests, quantitative bias analysis (QBA) instead incorporates or produces quantitative information on bias. QBA methods allow analysts to produce bias-corrected estimates or to ascertain the size of bias necessary to overturn a substantive result. This makes better use of the information the analyst may have -- for instance, analysts may be able to make reasonable assumptions about the size of bias, as well as its direction. By providing data on the likely material effect of bias, QBA can support better decision making, enable more plausible comparisons of alternatives, and inform the direction of research resources to areas where the expected consequences of reducing uncertainty in a biasing factor would be greatest. QBA can also focus disagreement [@ref581]: instead of unproductive debates over whether an estimate is or is not biased, discussion can centre on whether bias is plausibly sufficiently strong in practice or whether it has been appropriately operationalised by the analyst performing the QBA.

The term QBA denotes a broad aim rather than a single method. An arsenal of QBA methods exists, though not all are advertised under this name -- sensitivity analysis is a popular alternate term [@ref450; @ref454; @ref2243], though this is also sometimes unhelpfully used synonymously with 'robustness checks' -- additional analyses performed to check incidental analytical decisions (e.g., the coding of variables) do not influence results. There are QBA methods for measurement error, selection bias, and confounding; some can be combined to deal with each within a single analysis [@ref581]. QBA methods vary in their complexity, spanning *post hoc* deterministic methods applied to summary data (e.g., regression coefficients) to simulation-based stochastic methods that adjust record-level data repeatedly using random draws from hypothesised distributions for biasing factors.

Methods also vary in what they produce. Some methods -- like the E-Value [@ref2243] -- produce bounds on the size of bias required to entirely explain an observed association; larger bounds mean stronger -- potentially implausibly strong -- bias is required to explain an association absent a causal effect. Other methods -- like Pattern Mixture Modelling [@ref1002; @ref443; @ref445] -- can produce a bias-corrected estimate reflecting the researcher's best guess at what the causal effect is, given assumptions put into the QBA model. These methods can also be used for *tipping-point* type analyses to assess whether only a large degree of bias could explain an association [@ref68]. Given the large number of QBA methods, what follows is a selective review.

### 5.20.1.1 Methods using Summary-Level Data {#methods-using-summary-level-data}

As discussed in [Section 1](01-introduction.qmd), observational studies formed a major source of the evidence in the discovery of the harmful effect of smoking on lung cancer. One reason observational evidence was compelling was the size of the association between smoking and lung cancer observed. In one of the earliest quantitative bias analyses, Cornfield et al. [-@ref513] derived lower bounds on the associations a single binary confounder must have with a binary exposure and binary outcome to fully explain an observed association between the two. Specifically, they show that the exposure-outcome association must be equal to or exceeded by both the confounder-outcome and confounder-exposure associations, rules now referred to as the 'Cornfield conditions'.

One corollary of their formulation is that the closer the confounder-outcome association is in size to the exposure-outcome association, the stronger the confounder-exposure association must be (and vice versa). This trade-off between confounder-exposure and confounder-outcome associations necessary to explain an exposure-outcome relationship follows a simple equation and can be plotted as contours as in [Figure 5.19](#figure-5-19) -- see the figure caption for further details.

::: {#figure-5-19}

![**Figure 5.19:** Graphical representation of the 'Cornfield Conditions' [@ref513] for a binary exposure (X), outcome (Y) and confounder (Z). For a given risk ratio (RR = 2) between exposure and outcome (i.e., P(Y = 1 \| X = 1)/P(Y = 1 \| X = 0)) and probability Z = 1 given X = 1 (green, orange, and pink lines), the graph shows the combination of association between confounder and exposure (RR\[XZ\], x-axis) and confounder and outcome (RR\[ZY\], y-axis) required to fully explain the association. If the confounder-exposure association is weaker (e.g., RR(XZ) ↓ or P(Z = 1 \| X = 1) ↓), then the confounder-outcome association must be stronger to explain the same result.](images/image36.png){width="100%"}

:::

The Cornfield conditions formalise several intuitions, including:

1.  Stronger exposure-outcome associations require a greater degree of confounding to explain results

2.  Confounders must have at least as large a causal effect on the outcome as the observed exposure-outcome association

3.  The strength of effect of the confounder on the outcome must be greater if the effect of the confounder on the exposure becomes weaker (and vice versa).

Using their bounds, Cornfield et al. [-@ref513] offered an unanswerable test to sceptics of the link between smoking and cancer (among whom counted Ronald Fisher): no plausible confounding factors existed that could explain the very large association between the two.

The Cornfield conditions further formalise the intuition that there must be strong imbalance in absolute terms in the prevalence of the confounder between levels of the exposure; otherwise the confounder must have a particularly strong impact on the outcome to compensate (compare the pink, orange and green lines for a given RR(XZ) in [Figure 5.19](#figure-5-19)). To give an applied example, parental problematic drug use may be a confounder in the association between parental SES and childhood development, but it is (thankfully) a rare occurrence, so is unlikely to explain much of the association between the two.

The E-Value [@ref2243], a widely used QBA method, builds upon the Cornfield conditions by making two assumptions: first, that the exposure-confounder and confounder-outcome effects are equal, and second, that the prevalence of the confounder among exposed is 100%. The E-Value is represented as a point at the intersection of the pink (P(Z = 1 \| X = 1) = 1) and blue (RR(XZ) = RR(ZY)) lines in [Figure 5.19](#figure-5-19). As Fox et al. [-@ref581] and others [e.g., @ref59] note, however, the assumption of complete prevalence of the confounder among the exposed is generally implausible and conservative. Fox et al. [-@ref581] thus introduce the 'G-Value', which generalises the E-Value to situations where prevalence of the confounder is lower -- [Figure 5.19](#figure-5-19) also displays the G-Value(0.25) (intersection of green and blue lines) where the prevalence of the confounder among treated is 25%. As can be seen, the G-Value is larger than a given E-Value; the confounder has to have a stronger effect on the outcome because it is now less prevalent among the exposed group.

Though both the E-Value and G-Value allow bounds to be represented in a single scalar value, the price of this is the assumption that confounder-exposure and confounder-outcome associations are equal. This is not likely to be plausible in practice. It is instead preferable to posit values of each separately and to determine the consequences of this for bias, as enabled by drawing contours as in [Figure 5.19](#figure-5-19). The utility of the Cornfield conditions and the E-Value and G-Value is that they can be used as a basis for rigorous argument about confounders, including providing a frame for reviews of existing evidence on plausible confounding variables. It is not sufficient to say a confounder exists -- it needs to have particular properties. However, this does not appear to be how E-Values and the like are used in practice. In their review of the use of E-Values, Blum et al. [-@ref60] report that few authors assessed whether confounding was likely to overturn results or even noted candidate confounders likely to be missing from analyses.

A further limitation of the E-Value concerns multiple confounders -- the E-Value relates to the combined effect of these, so several confounders that are individually too weak to explain away an association may jointly do so [@ref21100]. This joint strength can be particularly difficult to ascertain where individual unmeasured confounders are correlated. On the other hand, the degree of residual confounding depends on the confounders that have been controlled for -- some of these (e.g., age and sex) can be strongly related to unobserved confounders, and so partly operate as proxies for these variables [@ref21101]. Together, these issues mean the E-Value can give a too optimistic or too pessimistic view of sensitivity to confounding bias [@ref21102].

Though developed for settings with binary variables, the E-Value can be produced for continuous variables too, using heuristics for converting standardised beta coefficients to odds ratios [@ref67]. However, similar methods have been developed for settings with continuous outcomes, specifically. Omitted variable bias (OVB) follows a simple formula in linear regression settings: it is the product of the regression coefficient for the confounder had it been included in the regression model and the coefficient from a regression of the confounder on the exposure had it been performed.

> True Model: $Y = \beta_{0} + \beta_{1} \cdot X + \beta_{2} \cdot Z + \varepsilon$
>
> Estimated Model: $Y = \widehat{\beta_{0}} + \widehat{\beta_{1}} \cdot X + \widehat{\varepsilon}\ $
>
> Decomposition: ${\widehat{\beta_{1}} = \beta}_{1} + \beta_{2} \cdot \delta_{1}\ $ (True Effect + Omitted Variable Bias)
>
> Where $\delta_{1}$ is the solution to regression: $Z = \delta_{0} + \delta_{1} \cdot X + \mu$

Note, $\delta_{1}$ is the solution to the regression of Z upon X, despite this running counter to the direction of hypothesised causality (i.e., X is dependent on Z, rather than the other way round). However, this formulation makes intuitive sense: the observed association between X and Y is equal to the causal effect of X upon Y ($\beta_{1}$) plus the effect of Z upon Y multiplied by the association a one-unit difference in X has with Z. This formulation has another advantage: while Z may have a large effect on X, X may have only a weak association with Z if Z explains little of the variance in X overall. Again, absolute effect size is key for driving OVB.

The OVB formula, $\beta_{2} \cdot \delta_{1}\ $, can be visualised in a contour plot similar to the Cornfield conditions in [Figure 5.19](#figure-5-19). An issue, however, is that the standard OVB formulation depends on the scales used for the exposure and outcome and so identifying appropriate literature on confounder-exposure associations may be difficult. Additionally, the formula does not easily generalise to situations with multiple confounders. To address this, Cinelli & Hazlett [-@ref450] reparameterise OVB in terms of partial R^2^ (i.e., the residual variance in exposure and outcome a confounder explains after conditioning on covariates).[^53] With this formula, analysts can determine the required confounding associations to materially change an observed association between exposure and outcome (e.g., attenuate to the null), again assisted using contour plots.

Cinelli & Hazlett's [-@ref450] method is implemented in the sensemakr R package [@ref66]; see [Figure 5.20](#figure-5-20) for an example. The sensemakr package outputs additional information to contextualise analysts' consideration of whether unobserved confounders can plausibly explain results. This includes a 'robustness value' (for both the point estimate and lower confidence interval), which -- analogous to the E-Value -- specifies the minimum partial R^2^ that would be required to attenuate the observed association to the null, setting this equal for the partial R^2^ for both the confounder-exposure and confounder-outcome associations. It also includes information on the associations between *observed* confounders and exposure and outcome. For instance, in their working example on the effect of experiencing violence during the Darfur war on attitudes to peace (displayed in [Figure 5.20](#figure-5-20)), the authors benchmark the effect of the supposed confounder (whether the respondent lived in the *centre* of a village) against sex, showing that *centre* would need to have multiple times stronger association with outcome and treatment than sex to explain results ('\[1-3\]x female' sit below the red-dashed line of null association in [Figure 5.20](#figure-5-20)). This is helpful because, while not all confounders may be observed, major ones may be. Using the latter to calibrate expectations can therefore help interpretation of the QBA analysis.

::: {#figure-5-20}

![**Figure 5.20:** Contour plot of a Cinelli & Hazlett [-@ref450] type sensitivity analysis. Drawn from the Cinelli & Hazlett [-@ref450] running example examining the potential for confounding in the association between experiencing violence during the Darfur war and attitudes to peace. The authors hypothesise that this association is confounded by whether the survey respondent lived in the centre of the village (more likely to be victimised) or at the periphery, and use the variable ‘female’ to contextualise discussion of whether confounding would be sufficient to reduce the observed association (0.097) to the null. If the confounder were to have 3 times the strength of association with violence victimisation and peace attitudes as female does, this would still not be sufficient to reduce the point estimate to the null (3x female [0.03]). Cinelli & Hazlett [-@ref450] type sensitivity analyses can be performed with the sensemakr R package [@ref66], which also outputs ‘robustness value’ statistics.](images/image37.png){width="63%"}

:::

Oster [-@ref46] provides another formulation of bias from omitted variables that, like Cinelli & Hazlett [-@ref450], uses observable information from regressions including observed confounders, but also utilising information on the "stability" of coefficients when adding observed confounders to models. Oster's solution parameterises OVB as a function of four observable and two unobserved quantities: the model R^2^ from (a) a "short" regression of Y on X (denoted $\dot{R}$), (b) a regression of Y on X plus observed confounders ($\widetilde{R}$), and (c) a regression of Y on X plus observed and unobserved confounders, would it be possible to run this ($R_{MAX}$); coefficients for X in regressions (a) ($\dot{\beta}$) and (b) ($\widetilde{\beta}$); and a parameter, δ, capturing "proportional selection" -- the relative association unobserved confounders have with treatment relative to observed confounders (by necessity, this is also unobserved).

$$\beta^{*} \approx \widetilde{\beta} - \delta \cdot (\dot{\beta} - \widetilde{\beta}) \cdot \frac{R_{MAX} - \widetilde{R}}{\widetilde{R} - \dot{R}}$$

... where $\beta^{*}$ is the coefficient on X from a regression of Y upon X plus observed and unobserved confounders. δ captures imbalance in the unobserved confounders across exposure levels (though as a function of imbalance in the observed confounders) and $R_{MAX} - \widetilde{R}$ captures the impact of confounders on the outcome. All else being equal, greater proportional selection and larger effects of the confounders on the outcome will bias coefficients more.

Using this formula, one can reason about the combinations of $R_{MAX}$ and $\delta$ that would reduce $\beta^{*}$ to an important value (e.g., the null, $\beta^{*} = 0$) or to determine what plausible values of $R_{MAX}$ and $\delta$ would imply for $\beta^{*}$. A key development in Oster's [-@ref46] paper is that she identifies heuristics for $R_{MAX}$ and δ by applying her formula to the results of RCTs, among other analyses. Oster suggests values of $R_{MAX} = \min(1,\ 1.3 \cdot \widetilde{R})$ and δ = 1 as sensible bounds.

The Cinelli & Hazlett [-@ref450], Oster [-@ref46], E-Value, G-Value, and Cornfield Condition methods each exploit summary-level data and are referred to as 'simple sensitivity analysis' techniques. Each is generally used to evaluate bias from unobserved confounding, though can be extended to assess other types of bias, including selection bias or bias from violations of the assumptions of instrumental variables analysis [@ref67; @ref219]. Other QBA methods to obtain bounds that use summary-level data exist, including for (e.g.) bias from differential measurement error [@ref277]. We will not cover these methods further here [for more, see @ref581].

Another summary-level approach that has been used extensively to account for bias is regression calibration [@ref1402], though in this case the purpose is to provide a bias-corrected estimate. Regression calibration applies where there is regression dilution -- classical measurement error in the exposure, which would bias the estimate, most commonly towards the null. This attenuation is predictable: in linear regression, the observed association will be attenuated in proportion to the measurement's reliability (i.e., the correlation between two independent measurements of the same variable). The correction is therefore straightforward -- one can divide the estimated coefficient by assumed reliability -- though more complex ways of incorporating this information can be performed (e.g., by treating reliability as an uncertain estimated quantity with its own distribution). However, this approach will generate biased results when there are unobserved or mis-measured confounders [@ref65; @ref64] as the uncorrected estimate will be subject to other biases, rather than just the regression dilution.

### 5.20.1.2 Methods using Record-Level Data {#methods-using-record-level-data}

Another popular method that corrects for measurement error but instead uses record-level data is Simulation and Extrapolation [SIMEX\; @ref55]. In SIMEX, analyses are re-run *adding* random measurement error to (continuous) variables.[^54] Progressively increasing error and then drawing a line of best fit through estimates, before extrapolating back, allows one to predict a situation where no measurement error exists (see [Figure 5.21](#figure-5-21)). SIMEX can handle situations where it is confounders, rather than the exposure itself, that are subject to measurement error, but accurate extrapolation requires (a) correct assumptions about the reliability of the initial measurement (which determines how far a line of best fit should be drawn backwards to reflect a situation of no measurement error) and (b) use of an appropriate extrapolation function, which is an inherently uncertain choice.

::: {#figure-5-21}

![**Figure 5.21:** Results of an example SIMEX analysis. SIMEX consists of two steps. First, one reruns analyses, progressively adding random measurement error to the variable hypothesised to be subject to measurement error, in proportion to the amount of error anticipated in the raw variable already. Next, one estimates a line of best fit through the estimates obtained from Step 1 (blue line) and then extrapolates this line back to the point where no measurement error would exist to obtain the measurement-error corrected estimate (orange line for x-axis = 0).](images/image38.png){width="100%"}

:::

Systematic or differential measurement error can be corrected for via simulation using record-level data [@ref808; @ref807; @ref632]. For instance, to account for 'mode effects' (a type of measurement error where responses vary systematically by mode; [Section 2.2.5](02-problem.qmd#information-bias)) in a mixed-mode study in which participants are not randomised to mode, external information on mode effects can be used to simulate values had participants responded in a single mode. For example, experimental evidence may indicate that individuals report 0.2 SD *better* mental health when responding via telephone rather than web [@ref853; @ref58]. Subtracting 0.2 SD from observed mental health for those in the telephone mode would therefore provide (estimated) counterfactual values which can be used when fitting the substantive model of interest. This approach is very flexible -- it can handle multiplicative, or other non-additive, errors and differential measurement errors [@ref807], e.g., by incorporating different sized errors according to participant characteristics. The process can be repeated to explore sensitivity of the findings to different magnitudes of measurement error.

Another record-level simulation-based method is Pattern Mixture Modelling [PMM\; @ref1002; @ref443; @ref445]. PMM is used to correct for violations in the Missing at Random Assumption used in multiple imputation ([Section 5.4](05-04-missing-data-methods.qmd)) -- i.e., for selection bias. Post hoc adjustment is used to amend imputed values -- for instance, if one anticipates missing values to in fact be 0.3 SD lower than as imputed, imputed values can simply be corrected to reflect this and analyses otherwise run as usual (i.e., with estimates pooled with Rubin's Rules). As with simulation for non-random measurement error, the complexity of the PMM procedure can be increased -- for instance, by choosing more complex patterns of MNAR (e.g., larger violations in some groups than in others). Corrections to MNAR should be performed within the 'Gibbs sampler' -- i.e., within the imputation procedure, rather than once the imputed datasets have been created -- so that chained equations models reflect beliefs about MNAR. However, this can be hard to code [some limited functionality exists in the mice R package\; @ref443] and is more computationally demanding to run as it requires separate imputations for each MNAR assumption posited.

Simulation-based methods can incorporate assumptions on biases stochastically, rather than use single deterministic values -- for instance, by reflecting uncertainty as distributions and repeating the simulation using draws. Fox et al. [-@ref581] provide advice on turning beliefs about the size of biases into statistical distributions from which to draw. Often, it may be easier to rule *out* particular-sized biases, than rule biases *in* [for instance, mode effects are unlikely to exceed 0.5 SD, but may be within the range 0-0.2 SD\; @ref58]. In this case, simulations can be run in a tipping-point-like fashion, or large and implausible biases used to assess whether implausible levels of bias would be insufficient to change substantive conclusions.

Readers interested in QBA can see the textbook by Fox et al. [-@ref581], which includes recommendations for performing and reporting QBA [see also @ref1401]. However, note, as epidemiologists, the authors focus their exposition and examples on cases with binary exposures and outcomes. For comprehensive discussion of QBA for measurement error, specifically, see Keogh et al. [-@ref56] and Shaw et al. [-@ref57].

## 5.20.2 Applications {#applications}

Several papers have calculated E-Values as part of analyses of CLS data [see, e.g., @ref45; @ref43; @ref44; @ref42]. For example, Gondek et al. [-@ref45] use the E-Values to understand the potential consequences of bias in an analysis of early mental health and later problematic alcohol use using data from the NCDS and BCS70. Though the E-Values were small, they note a paucity of existing evidence on the strength of the confounders they hypothesise, making it difficult to evaluate plausibility. Nevertheless, this evidence may appear in future, so performing the QBA provides information that may still be of use to future readers.

Dräger et al. [-@ref47] perform an Oster [-@ref46] type QBA of the association between school absences and attainment at GCSE using data from the MCS. They show that many of their results are robust to an assumption about relative selection on observables and explanatory power of observables for their outcome. However, this assumption is not well justified and is only compared against a much more conservative assumption, which produces prima facie implausible results for some model specifications.

Bann et al. [-@ref1030] use PMM when assessing cross-cohort differences in the association between height and cognitive ability using data from NCDS, BCS70 and MCS, given different levels of non-response and missingness in each of these studies. They perform a tipping-point-style analysis to assess whether differences in missingness mechanisms would be required to explain results.

## 5.20.3 Opportunities {#opportunities}

As QBA methods are designed to be used to handle situations where data are missing (e.g., on confounders), they do not make demands upon existing data. Therefore, there is ample opportunity to use these in CLS's cohorts. That said, as data on many major confounders are available, Cinelli & Hazlett [-@ref450] type QBA may be especially compelling as these confounders can be used to calibrate assessments of unobserved confounding.

[^53]: As partial R^2^ are directly related to the (partial) correlation between two variables, the partial R^2^ is symmetric. (Note in the equation above, OVB is expressed in terms of a regression of the confounder upon the exposure, even though the assumption is that the confounder is the cause of the exposure.)

[^54]: Küchenhoff et al. [-@ref54] extend SIMEX to categorical data.
