# 6 Discussion {#discussion}

Causal inference is one of the central goals of quantitative health and social science, but also one of its most difficult to attain. The foregoing has shown that there may be ample opportunities for making causal inferences using CLS cohort data and multiple different methods and broad approaches to utilise when doing so.

Viewed individually, each of these methods stands or falls on the validity of their assumptions. Validity depends on the specific situation to which the methods are being applied and usually cannot be ascertained directly. Determining whether assumptions are valid -- or close enough to be valid as to still be useful -- requires knowledge of a specific research domain and an ability to synthesise evidence and construct arguments, especially when realising that one's readers need convincing, too [‘The first principle is that you must not fool yourself—and you are the easiest person to fool’\; @ref20781].[^55] Argumentation about whether assumptions are met is necessary regardless of whether model-based approaches (*is residual variation as-if random?*), design-based approaches (*does this IV meet the exclusion restriction?*), or Elaborate Theory approaches (*is the mechanism of action weaker in this setting, as hypothesised?*) are used.

Nevertheless, no single study is likely to be perfect. An RCT may accurately balance treated and controls, but available measures may be inadequate, diluting estimates, or the intervention may be too narrow to generalise directly to situations of interest, necessitating the application of theory to justify any generalisation, perhaps informed by other empirical results [@ref20790]. Viewed as one component of a wider literature, however, imperfect studies can still make a contribution. For instance, a study may reduce uncertainty about a hypothesis by testing the effect of a confounder not yet considered in other studies. More formally, one study may have biases unrelated to those in another study, possibly because it used a different study design (e.g., a quasi-experiment rather than statistical control). If these studies nevertheless converge upon the same result, this is stronger evidence of the reliability of the causal effect estimate [@ref20795; @ref3094]. Such "triangulation" can involve evidence of different characters that may even, at first glance, appear only tangentially related. Part of the evidence for the effect of smoking on cancer involved the results of prospective cohort studies [@ref20785], but it also included ecological studies of societal trends in lung cancer mortality, lung autopsies of smokers who died from other causes, and experimental evidence from animal models [@ref513]. Added more recently is evidence from individuals with particular genetic disorders, who provide indirect evidence for later steps in a hypothesised biological pathway, which smoking is thought to precipitate [@ref579].

Rosenbaum [-@ref579] following Haack [-@ref20788] likens such reasoning to completing a "causal crossword". Considered in isolation, each piece of evidence supporting a causal inference may be weak, but together lend mutual support, as two guesses intersecting with the same letter do for crossword players. Meditating on this and advice to "Make your theories elaborate", Rosenbaum [-@ref579, p. 209] concludes "If you took \[the advice to make your theories elaborate\] seriously, then you would ask of each new study what it contributes to the currently incomplete, partly penciled-in puzzle. You would welcome the completion of a new entry, even a small entry, compatible with the current tentative completion. You would also welcome a compelling new entry that challenged some current entries. You would welcome the suggestion that a particular entry is mistaken and constitutes a barrier to correct completion of the puzzle. A pencil and an eraser would be two tools of equal importance." As with a crossword, two entries may not intersect -- may be only tangentially related -- but still contribute to the completed whole.

Completing causal crosswords would require quantitative researchers to clearly state their goals and the quantity they are trying to learn with their statistical analysis [the estimand\; @ref240]. Several authors have offered powerful critiques of prevailing norms in non-experimental sciences against stating one's causal ambitions and to instead rely on imprecise euphemisms such as "association" and "relationship" [@ref19728; @ref2; @ref20803; @ref20774] -- euphemisms, we should say, we have been guilty of using in our own work -- and to also claim one is only interested in description or prediction, when in fact that would motivate different analytical choices to those chosen [@ref2; @ref20774]. Hiding one's aims makes productive disagreement more challenging and holds back cumulative scientific progress [@ref19728; @ref2]. It also enables suboptimal practices, such as controlling for mediators in statistical models [@ref20810] and formulating poorly conceptualised research questions where the intervention is not well-defined [@ref20803]. This taboo has led to the curious practice of researchers cautioning against causal interpretations in their studies while, at the same time, assuming causality when drawing policy and action recommendations from their work [@ref20831; @ref20791] -- a practice that has been referred to as "Schrödinger's inference" [@ref20830].

Authors critiquing current practices have offered several recommendations for the conduct and reporting of studies that aim to generate evidence for causal inference [@ref19728; @ref2; @ref20791; @ref20803; @ref20774]. For instance, Hernán [-@ref20803] argues causal language should be used throughout papers except in the results section, where the language of association should instead be used, reflecting the nature of statistical estimates, which only with discussion in methods and other sections can be provided with a causal interpretation. Others have produced "roadmaps" for designing causal inference studies -- checklists and processes going from defining a coherent research question and theoretical estimands to choice of appropriate statistical estimator, quantitative bias analyses and falsification tests, and judicious interpretation of results [@ref20823; @ref20797; @ref20799].

All of which is to say: beyond simply being a set of methods, causal inference requires an ability to ask good questions, to synthesise disparate lines of evidence to come to reasoned judgements, to be transparent about the plausibility of underlying assumptions, and to be honest about uncertainty. CLS data have many attributes that can support causal inference, but the data alone are not enough.

[^55]: Advice that is made harder by the human brain's capacity to treat results as obvious in hindsight, and to forget uncertainty that existed before [@ref20783; @ref20832].
