# 8 Appendix {#appendix}

## 8.1 Correlation ≠ Causation: A Short Empirical Review {#correlation-causation-a-short-empirical-review}

Nature is replete with examples of correlations between variables that clearly do not result from causal effects of one variable upon the other; see Vigen [-@ref468] for a humorous list. Associations identified in observational studies that persist even after adjusting for known confounding factors may be more plausible and anticipated by existing theories [or less rigorously, explainable post hoc\; @ref1870], but still be incorrect, regardless. We can be confident this is the case because RCTs regularly produce results that are discordant with those in standard observational studies. Moreover, observational studies can produce estimates of causal effects that are implausible *prima facie*, including cases where similar procedures (e.g., statistical adjustments for major hypothesised confounders) are followed that identify estimates that appear more plausible.

Given its widespread use of randomised controlled trials, much of the evidence on the discordance between observational studies and RCTs comes from the medical literature. The history of epidemiological research includes multiple examples of factors that, based on observational studies, were thought to cause, or protect from, disease, but have been subsequently shown in RCTs to act otherwise. This includes factors that, despite showing initial promise, have in RCTs produced only null results; for instance, Vitamin C was thought to reduce the risk of cardiovascular disease but large RCTs have shown no evidence of effect [@ref481]. More troublingly, factors that have appeared protective in observational studies have in RCTs transpired to have harmful effects, including cases where observational evidence had been used to inform medical recommendations and clinical practice. This includes HDL ("good") cholesterol and β-carotene. For instance, in observational studies, β-carotene was found to be related to lower risk of cancer, but in fact increases risk among smokers [@ref473]. Dispiriting results from RCTs have led prominent epidemiologists to wonder, tongue in cheek, whether it was "time to call it a day" on their field [@ref473].

High-profile examples comport with more general findings. Meta-analyses comparing observational associations with effects from RCTs in studies of therapeutic interventions [@ref482; @ref479; @ref505] or disease risk factors [@ref493] show small average differences between the two designs, but this masks substantial heterogeneity, including cases of statistically significant differences in effects, variations in effect size of double or more, and instances of reversal of sign [@ref497].[^56] Similar patterns have been found in economics [@ref488], while in education, (non-randomised) interventional studies have a mean effect size exceeding 0.4 SD, compared with an average effect size of just 0.06 SD in well-conducted RCTs [@ref485].[^57] Studies comparing observational and quasi-experimental estimates of the effects of educational attainment also show a variety of discordant effects [@ref487]. Though there is evidence that longitudinal or prospective cohort studies show smaller discrepancies with RCTs than other observational study designs, bias is observed in these types of study, too [@ref495; @ref488; @ref505].

A crucial feature of studies comparing RCTs with observational studies is that, in some, authors have noted the difficulty of predicting the size and direction of bias *a priori* and of finding statistical methods that reliably eliminate bias [@ref488; @ref497; @ref493]. While studies often differ in results, this would not matter so much if the size of this difference were predictable -- a clock that has yet to be set to daylight saving time can be corrected *post hoc*. Nevertheless, while at an aggregate level, bias may be difficult to predict, there are several research areas where bias is expected to operate in a single direction. As noted, observational studies of educational interventions typically overestimate effect sizes, and there are other fields where this is the case. Notably, social epidemiology studies investigating the effect of social status upon health can generally be presumed to find a stronger negative association between disadvantaged social status and health than reflects a causal effect of the former due to, among other things, health-related selection into social position. This presumption is supported by studies exploiting policy experiments that find comparatively small effect sizes of, e.g., income on health [@ref9; @ref11], as well as the persistence of health inequalities in relatively economically equal societies [@ref5418]. Observational studies assessing the effect of the family environment upon children may also be expected to be biased towards finding larger effects than is correct due to the heritability of human traits and direct genetic transmission within biological families [@ref2910; @ref472]; this point will be expanded upon in [Section 8.2](#why-does-correlation-often-not-equal-causation). In both social epidemiology and family research, bias is particularly concerning as observational studies are expected to give estimates that are anti-conservative -- i.e., larger than the true causal effect. An unbiased association could therefore be small or even null.

There are, however, sometimes substantively important reasons why results from observational studies and RCTs differ that do not reflect confounding bias in observational studies. This includes differences with *what* intervention is implemented, *how*, and to *whom* and what the target *estimand* is. Individuals tasked with providing an intervention in an RCT may be more motivated and well-trained than those so tasked when the intervention is rolled out as policy in the real world, meaning fidelity to protocols may decrease [@ref496]. RCTs by necessity also only deal with interventions that are ethically, financially and physically feasible to implement, which does not limit observational studies. Interventions in RCTs are thus typically more limited in scope than the corresponding comparisons made in observational studies and are often focused on quite specific groups of individuals [@ref9]. For instance, rather than examine a change in household income from bottom to top quintile among the general population, which a typical observational social epidemiology study would do, an RCT may instead investigate relatively small and short-term increases in welfare generosity on people, e.g., receiving sickness benefit.[^58] Nevertheless, it is still the case that observational studies can yield results that can only be plausibly explained by residual confounding or other biases -- for instance, after controlling for several confounders, smoking remains associated with suicidal ideation [heavy vs. non-smokers, OR = 3.33\; @ref2051] and hormone replacement therapy use remains related to lower risk of mortality from accidents [RR = 0.5\; @ref476]. These findings demonstrate the potential for substantial bias in observational studies, though as noted in [Section 5.11](05-11-target-trial-emulation.qmd), some of this bias can be "self-inflicted" and follow from the analyst's decisions, rather than irredeemable issues of internal validity (confounding, selection, and information biases) in the underlying data.

## 8.2 Why Does Correlation (Often) Not Equal Causation? {#why-does-correlation-often-not-equal-causation}

The prevalence of observational studies generating different results to RCTs raises the question of why correlation often does not equal causation [@ref470]. Several disciplinary perspectives are useful for understanding why confounding may arise in observational studies. Here we highlight two: economics and behaviour genetics.

The economics perspective highlights that individuals attempt to achieve their goals but differ in their preferences and the resources they have available (finances, cognitive skills, etc.). All actions have opportunity costs -- resources expended on one action cannot be expended elsewhere -- and individuals are in competition over finite resources. This competition usually resolves with the person who is willing to pay the most obtaining the resource -- e.g., the person who is willing to pay the most for the nice house in the nice area is the one who gets it. In many situations, this will lead to positively valent things becoming clustered -- the family who can afford to move within the catchment area of the high-achieving school could also afford to move to the low-crime neighbourhood as well as afford to insulate and heat their home and to follow the most healthful diet. In other situations, this will lead to attractive goods becoming anti-correlated as they are, to some extent, substitute goods -- for instance, time spent on one activity means less time for another. Both of these processes can lead to confounding in observational data.

Another corollary of the economics perspective is that the people least harmed by a negative situation, or who derive the greatest benefit from a positive one, are the people who are most likely to select into or remain in that situation -- for example, those whose disease prognosis is the worst may be most willing to accept the experimental treatment. (Prescribing based on prognosis is known as 'confounding by indication'.) Again, this can lead to confounding in observational data. Indeed, the very fact that, in observational data, two people differ on some exposure variable should give pause that they are otherwise comparable [@ref454].

The behaviour genetics perspective highlights genetic influences on human traits and the direct transmission of DNA from parents to their children in (biological) families. This is supported by decades of research using twin and other genetically informed family studies showing that almost all human traits are heritable [@ref685], including unsurprising traits like height, but also complex, social traits like education and even divorce. The behaviour genetics perspective predicts that parents' and children's traits will be correlated, regardless of any environmental effect parents may have; children with highly educated parents are more likely to attain higher education themselves partly because they have inherited education-promoting genes from their parents. For compelling descriptions of this view, see Robert Plomin's [-@ref2910] book *Blueprint* and Judith Rich Harris' [-@ref472] *The Nurture Assumption*.[^59]

The behaviour genetics perspective also highlights gene-environment correlation (rGE) as a potential source of confounding in observational studies. rGE describes the processes by which genes and environments become correlated and comes in three forms: passive, active, and evocative. *Passive rGE* describes the process discussed above -- children inherit genes from their parents as well as family environments, so these become correlated with no further intervention. This includes correlations between parents and their children for the same trait (e.g., education) but also correlations with other aspects of the family environment that are influenced by parental genes. For instance, parents with high reading ability may have more books in the home but will pass genes related to reading ability on to their children, whether their children read those books or not.

*Active rGE* describes the process by which people choose environments based on their genetically influenced proclivities -- a child with high reading ability may spend their pocket money on books. *Evocative rGE* describes the process by which the environment and people within it respond to a person partly based on their genetic endowment -- for instance, a child who is perceived to be struggling academically may elicit more support from teachers. In each of these cases, an observational study that assumed the direction of causality ran solely from the environmental factor to the child's trait would be in error.

One final genetics perspective relates to the relatively limited number of protein-coding genes in the human genome (approximately 20,000) compared with the incredible number of tasks a body carries out, and the wide and often continuous variation observed between individuals in their traits. Genome-wide association studies have demonstrated that most traits are polygenic (influenced by many genes each having small effects) and that genes are pleiotropic (implicated in many traits) [@ref469]. Correlations between traits can therefore arise because of the varied action of genes. This includes correlations between traits that otherwise would not have an obvious link. For instance, height and schizophrenia have genetic overlap [@ref3]. The observation that "everything correlates to some extent with everything else" has been called the "crud factor" in psychological and sociological research [@ref490].

[^56]: The cited studies are only a selection of those available. The blogger Gwern Branwen [-@ref506] maintains a larger list.

[^57]: To understand how dispiriting this is, imagine you took a random person who received the intervention and compared them with a random person who did not. With an effect size of 0.4 SD, the intervention recipient would have the better outcome 61.1% of the time. With an effect size of 0.06 SD, this would drop to 51.7%, little better than a coin toss (i.e., 50%).

[^58]: It should also be noted that there are meta-scientific reasons why results can differ between observational and interventional studies: specifically, p-hacking and publication bias. Though there is evidence of p-hacking and publication bias in RCTs [@ref471], funders of RCTs also often require pre-registration and publication of results [@ref485]. In observational studies, a null result may be more easily dismissed as reflecting bias in the observational data and filed away.

[^59]: Twin studies offer another reason to be sceptical that environmental exposures can have large causal effects -- specifically the small role the shared environment (non-genetic factors shared between siblings) has in explaining trait variation, a phenomena that has been referred to as the 'gloomy prospect' of behaviour genetics [@ref1237; @ref210]
