<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A guide to methods and research designs for causal inference with the Centre for Longitudinal Studies’ cohort data.">

<title>5.6 Difference in Differences – Causal Inference in the CLS Cohort Studies</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-07-study-initiated-experiments.html" rel="next">
<link href="./05-05-longitudinal-fixed-effects.html" rel="prev">
<link href="./images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-6be7f6e0362b36c773b9fb5cb1e95ee5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-methods.html">5 The Methods of Causal Inference</a></li><li class="breadcrumb-item"><a href="./05-06-difference-in-differences.html"><span class="chapter-title">5.6 Difference in Differences</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./images/cover.svg" alt="Cover: Causal Inference in the CLS Cohort Studies" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./images/cover.svg" alt="Cover: Causal Inference in the CLS Cohort Studies" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Causal Inference in the CLS Cohort Studies</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/CLS-Data/causal-inference-review" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this guide</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-problem.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The Problem of Causal Inference with Observational Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-approaches.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Three Approaches to Causal Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-attributes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Attributes of CLS’s Cohort Studies That Support Causal Inference</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5 The Methods of Causal Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-01-control-via-regression-adjustment.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.1 Control via Regression Adjustment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-02-matching.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.2 Matching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-03-inverse-probability-of-treatment-weighting.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.3 Inverse Probability of Treatment Weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-04-missing-data-methods.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.4 Missing Data Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-05-longitudinal-fixed-effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.5 (Longitudinal) Fixed Effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-06-difference-in-differences.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">5.6 Difference in Differences</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-07-study-initiated-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.7 Study-Initiated Experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-08-natural-experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.8 Natural Experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-09-instrumental-variables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.9 Instrumental Variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-10-regression-discontinuity-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.10 Regression Discontinuity Designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-11-target-trial-emulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.11 Target Trial Emulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-12-g-methods-for-time-varying-exposures.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.12 G-methods for Time-Varying Exposures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-13-causal-mediation.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.13 Causal Mediation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-14-family-designs.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.14 Family Designs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-15-negative-control-outcomes-and-exposures.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.15 Negative Control Outcomes and Exposures</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-16-cross-context-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.16 Cross-Context Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-17-biases-of-known-direction.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.17 Biases of Known Direction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-18-differential-effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.18 Differential Effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-19-reasons-for-effects.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.19 Reasons for Effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-20-quantitative-bias-analysis.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5.20 Quantitative Bias Analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-discussion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Discussion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-statements.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Statements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-appendix.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#method" id="toc-method" class="nav-link active" data-scroll-target="#method">5.6.1 Method</a></li>
  <li><a href="#applications" id="toc-applications" class="nav-link" data-scroll-target="#applications">5.6.2 Applications</a></li>
  <li><a href="#opportunities" id="toc-opportunities" class="nav-link" data-scroll-target="#opportunities">5.6.3 Opportunities</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/CLS-Data/causal-inference-review/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-methods.html">5 The Methods of Causal Inference</a></li><li class="breadcrumb-item"><a href="./05-06-difference-in-differences.html"><span class="chapter-title">5.6 Difference in Differences</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="difference-in-differences" class="quarto-section-identifier"><span class="chapter-title">5.6 Difference in Differences</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">5.6.1 Method</h2>
<p>In <a href="./03-approaches.html#elaborate-theories">Section 3.3</a>, we introduced some of the evidence that John Snow marshalled to demonstrate that cholera was transmitted via faecal-infected water rather than miasmas. This was not the only evidence he brought to bear. A further piece of evidence was his “Grand Experiment”, comparing cholera cases in households supplied by either of two London water companies, the Southwark-Vauxhall Company and the Lambeth Waterworks Company. Both companies drew water from the River Thames, but in 1852, Lambeth moved its intake pipes upstream of the main location where sewage was discharged <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">Cunningham, 2021</a>)</span>. Cholera cases in households supplied by the two companies in two years, before and after Lambeth relocated its pipes, are shown in Columns 2-3 of <a href="#table-5-2">Table 5.2</a>.</p>
<div id="table-5-2">
<table class="caption-top table">
<caption><strong>Table 5.2:</strong> John Snow’s ‘Grand Experiment’ comparing cholera incidence (per 100,000) in households supplied by two water companies across two years <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">Cunningham, 2021</a>)</span>.</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 28%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2" style="text-align: right;"><strong>Water Company</strong></th>
<th colspan="3" style="text-align: center;"><strong>Cholera Incidence</strong></th>
<th colspan="3" style="text-align: center;"><strong>Decomposition</strong></th>
</tr>
<tr class="even">
<th style="text-align: center;"><strong>1849</strong></th>
<th style="text-align: center;"><strong>1854</strong></th>
<th style="text-align: center;"><strong>Diff.</strong></th>
<th style="text-align: center;"><strong>t<sub>1</sub></strong></th>
<th style="text-align: center;"><strong>t<sub>2</sub></strong></th>
<th style="text-align: center;"><strong>Diff.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>Southwark-Vauxhall</strong></td>
<td style="text-align: center;"><strong>135</strong></td>
<td style="text-align: center;"><strong>147</strong></td>
<td style="text-align: center;">+12</td>
<td style="text-align: center;"><span class="math inline">\(u_{SV}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(u_{SV} + t_{SV}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(t_{SV}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Lambeth</strong></td>
<td style="text-align: center;"><strong>85</strong></td>
<td style="text-align: center;"><strong>19</strong></td>
<td style="text-align: center;"><em>-66</em></td>
<td style="text-align: center;"><span class="math inline">\(u_{L}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(u_{L} + d_{L} + t_{L}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d_{L} + t_{L}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><strong>Diff.</strong></td>
<td style="text-align: center;">-50</td>
<td style="text-align: center;"><em>-128</em></td>
<td style="text-align: center;"><strong>-78</strong></td>
<td style="text-align: center;"><span class="math inline">\(u_{L} - u_{SV}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(u_{L} + d_{L} + t_{L} - u_{SV} - t_{SV}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d_{L} + t_{L} - t_{SV}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Multiple comparisons are possible with these data to try to determine the causal effect of Lambeth Waterworks Company’s decision to move the pipe up the River Thames <span class="citation" data-cites="ref452">(and serendipitously reduce customers’ exposure to cholera-infected water; <a href="references.html#ref-ref452" role="doc-biblioref">Huntington-Klein, 2022</a>)</span>. One can treat Southwark-Vauxhall as a control group and use the data cross-sectionally, comparing rates in 1854 between the two companies (19 - 147 = -128). Alternatively, one can treat the data as an event study and make a simple before-and-after (pre-post) comparison, looking at incidence in Lambeth before and after it moved the pipes (19 - 85 = -66). However, these rely on a number of assumptions, which the decomposition in Columns 5-7 of <a href="#table-5-2">Table 5.2</a> clarifies. In those columns, the observed incidence is decomposed into a water company fixed effect (<span class="math inline">\(u_{WC}\)</span>) which contributes regardless of time period, a water-company time effect (trend; <span class="math inline">\(t_{WC}\)</span>) which contributes to the change between 1849 and 1854, regardless of whether the water company’s pipes were moved, and a treatment effect (<span class="math inline">\(d_{WC}\)</span>) which affects outcomes if ‘treated’ – i.e., the water pipes have been moved. <span class="math inline">\(d_{L}\)</span> – the treatment effect of moving the pipe for Lambeth-supplied households – is the quantity (causal effect) of interest.</p>
<p>Cross-sectionally, the observed difference between Lambeth and Southwark-Vauxhall in 1854 is a function of the treatment effect, but also the time effects and fixed effects (<span class="math inline">\(d_{L} + u_{L} + t_{L} - u_{SV} - t_{SV}\)</span>; Column 6, Row 3). Intertemporally, the observed difference is a function of the treatment effect and the time effect – i.e., it is confounded by time differences that would have occurred anyway (<span class="math inline">\(d_{L} + t_{L}\)</span>; Column 7, Row 2). A DAG representing Snow’s Grand Experiment is displayed in <a href="#figure-5-7">Figure 5.7</a>.</p>
<div id="figure-5-7">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/image24.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure 5.7: DAG representing John Snow’s Grand Experiment [adapted from @ref452]."><img src="images/image24.png" class="img-fluid figure-img" style="width:40.0%" alt="Figure 5.7: DAG representing John Snow’s Grand Experiment (adapted from Huntington-Klein, 2022)."></a></p>
<figcaption><strong>Figure 5.7:</strong> DAG representing John Snow’s Grand Experiment <span class="citation" data-cites="ref452">(adapted from <a href="references.html#ref-ref452" role="doc-biblioref">Huntington-Klein, 2022</a>)</span>.</figcaption>
</figure>
</div>
</div>
<p><a href="#table-5-2">Table 5.2</a> shows that a further comparison is possible: the difference in differences over time between treated (Lambeth) and untreated (Southwark-Vauxhall) units (-66 - 12 = -78). The decomposition shows that this is a function of the treatment effect and the difference in the time trends in Lambeth and Southwark-Vauxhall (<span class="math inline">\(d_{L} + t_{L} - t_{SV}\)</span>). This is the (2x2) Difference-in-Differences (DiD) estimator. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> It is unbiased where the time-trends in treated and untreated units are the same (i.e., <span class="math inline">\(t_{L} - t_{SV} = 0\)</span>); that is, the counterfactual time-trend is the same regardless of treatment assignment. Here, that means Lambeth’s cholera incidence in 1854 would have been 12 units higher than its 1849 level – 97 per 100,000 – had it not moved the pipe upriver. This is known as the ‘parallel trends assumption’.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>The quantity DiD recovers is the average treatment effect on the treated (ATT) – the effect among units that actually received treatment over the periods observed – rather than the average treatment effect (ATE) for the population as a whole (<a href="./02-problem.html#what-is-a-causal-effect-counterfactuals-and-the-potential-outcomes-framework">Section 2.2.1</a>). The purpose of the DiD estimate is to use within-variation in treated and control groups to condition on unit and time, simultaneously (i.e., blocking Pipe Location ← Time → Cholera and Pipe Location ← Water Company → Cholera in <a href="#figure-5-7">Figure 5.7</a>). The basic 2x2 DiD empirical set-up is:</p>
<p><span class="math display">\[Y_{it} = \beta_{0} + {\beta_{1} \cdot Treat}_{i} + {\beta_{2} \cdot Post}_{t} + {\beta_{3} \cdot Treat}_{i} \cdot {Post}_{t} + \varepsilon_{it}\]</span></p>
<p>Where <span class="math inline">\({Treat}_{i}\)</span> is an indicator for whether the observation is treated at any point and <span class="math inline">\({Post}_{t}\)</span> is an indicator for whether the observation falls in the period after the treated unit was treated. The coefficient <span class="math inline">\(\beta_{3}\)</span>, which is the unique difference post-treatment in the treated group, represents the causal effect of treatment (subject to the parallel trends assumption). In practice, a regression model may also include control variables that make the parallel trends assumption more plausible or could be paired with matching to identify plausible comparator observations.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>As the parallel trends assumption relates to counterfactual outcomes (how the outcome would have changed over time in the treated group, absent treatment), it cannot be verified <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">Cunningham, 2021</a>)</span>. However, in settings where more pre-treatment data are available, it is possible to perform two types of placebo test to at least explore the plausibility of the assumption. First, one can assess empirically whether trends were parallel in this pre-treatment period (e.g., one might assess whether changes across 1844-1849 were the same in Lambeth and Southwark-Vauxhall). Second, one can use placebo treatment dates to assess whether non-zero ‘treatment’ effects are observed (e.g., one could use data from 1839 and 1844 and pretend that the pipe was moved in 1844).</p>
<p>Though violations of either of these tests do not necessarily disprove the parallel trends assumption is correct (given the assumption relates to trends in the post-treatment period, specifically), they may provide some cause for concern. However, one should also consider the degree to which the assumption would need to be violated to overturn results <span class="citation" data-cites="ref21040">(i.e., taking a quantitative bias analysis approach; <a href="references.html#ref-ref21040" role="doc-biblioref">Rambachan &amp; Roth, 2023</a>)</span>. Further, including extra untreated comparator groups similarly violating the parallel trends assumptions can sometimes still identify causal effects. For instance, to estimate the effect of government provision of emergency birth control on teen pregnancy rates using local authority (LA) level data, Girma &amp; Paton <span class="citation" data-cites="ref21041">(<a href="references.html#ref-ref21041" role="doc-biblioref">2011</a>)</span> use pregnancy rates among older women as extra controls (difference-in-difference-in-differences) on the assumption that these share similar within-LA time trends to younger women.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> See Cunningham <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">2021</a>)</span> for a decomposition of the ‘triple-difference’ design.</p>
<p>Parallel trends can be violated for several reasons, in addition to treated and untreated groups evolving separately. One reason is changes in composition in the groups over time (e.g., if Southwark-supplied households moved to Lambeth-supplied houses). A specific issue in cohort data is where there is non-random attrition. Another issue is anticipatory effects, a type of reverse causality, where the promise of treatment in future affects pre-treatment outcomes (e.g., fear of future job loss could affect present wellbeing). Finally, the assumption of parallel trends is dependent on the scale of the outcome; it may, for instance, hold on the natural (linear) scale but not on the log (percentage) scale, or vice versa.</p>
<p>In cohort data, more than two time periods may be available. In this case, the set of time and unit fixed effects can be added to the regression model – including both time and unit fixed effects in a model is referred to as the two-way fixed effects (TWFE) estimator, and is an extension of the standard fixed effects estimator seen in <a href="./05-05-longitudinal-fixed-effects.html">Section 5.5</a>. Having data from more than two time periods can also enable one to assess treatment effect dynamics – i.e., how the differences between treated and untreated groups develop over time. For example, by adding further interaction terms between group and time dummies or modelling time trends in each group parametrically (e.g., with linear terms). This is useful where causal effects depend on length of exposure (e.g., long-term unemployment vs.&nbsp;short-term unemployment). Note, when using repeated data from the same observational units (i.e., cohort members), care must be taken to ensure standard errors reflect potential interdependencies (e.g., by using clustered standard errors).</p>
<p>In many settings, including in cohort data, the ‘event’ may occur at different times for different people (e.g., due to a policy being rolled out to different areas over time or people experiencing an event [e.g., unemployment] at different ages). This creates issues where treatment effects vary over time. To see this, imagine we have three groups: never treated, early treated, and late treated. With these data, there are four 2x2 DiD comparisons, which would be captured by a standard DiD estimator: early treated vs.&nbsp;never treated; late treated vs.&nbsp;never treated; early treated vs.&nbsp;late treated in the early post-treatment period; late treated vs.&nbsp;early treated in the late post-treatment period. <a href="#table-5-3">Table 5.3</a> decomposes the DiD estimator for the late treated vs.&nbsp;early treated comparison, which causes the issue. Now the difference in the differences is <span class="math inline">\(d_{L} + t_{L} - t_{E} - {\mathrm{\Delta}d}_{E}\)</span> (Column 4, Row 3; <span class="math inline">\({\mathrm{\Delta}d}_{E}\)</span> refers to the change in the treatment effect between pre- and post-late period for the early treated group). In other words, to represent an unbiased estimate of the treatment effect on the late treated (<span class="math inline">\(d_{L}\)</span>), it requires the parallel trends assumption as before (<span class="math inline">\(t_{L} - t_{E} = 0\)</span>), but also a constant treatment effect over time (i.e., <span class="math inline">\({\mathrm{\Delta}d}_{E} = 0\)</span>).</p>
<div id="table-5-3">
<table class="caption-top table">
<caption><strong>Table 5.3:</strong> Decomposition of the 2x2 DiD estimator comparing late treated vs.&nbsp;early treated groups when the treatment effect evolves over time.</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 35%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th rowspan="2" style="text-align: right;"><strong>Group</strong></th>
<th colspan="3" style="text-align: center;"><strong>Decomposition</strong></th>
</tr>
<tr class="even">
<th style="text-align: center;"><strong>Pre<sub>Late</sub></strong></th>
<th style="text-align: center;"><strong>Post<sub>Late</sub></strong></th>
<th style="text-align: center;"><strong>Diff.</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><strong>Early Treated</strong></td>
<td style="text-align: center;"><span class="math inline">\(u_{E} + d_{E}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(u_{E} + {d_{E} + {\mathrm{\Delta}d}_{E} + t}_{E}\)</span></td>
<td style="text-align: center;"><span class="math inline">\({{\mathrm{\Delta}d}_{E} + t}_{E}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;"><strong>Late Treated</strong></td>
<td style="text-align: center;"><span class="math inline">\(u_{L}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(u_{L} + d_{L} + t_{L}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(d_{L} + t_{L}\)</span></td>
</tr>
<tr class="odd">
<td colspan="3" style="text-align: right;"><strong>Difference in Differences:</strong></td>
<td style="text-align: center;"><span class="math inline">\(d_{L} + t_{L} - t_{E} - {\mathrm{\Delta}d}_{E}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>The TWFE estimator uses already-treated units as controls for later-treated units, generating bias. Estimators have been developed to avoid this – e.g., only using comparisons with never-treated or not-yet-treated groups; see textbooks from Cunningham <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">2021</a>)</span> and Huntington-Klein <span class="citation" data-cites="ref452">(<a href="references.html#ref-ref452" role="doc-biblioref">2022</a>)</span> for further details. Goodman-Bacon <span class="citation" data-cites="ref21034">(<a href="references.html#ref-ref21034" role="doc-biblioref">2021</a>)</span> shows that a DiD estimator that combines data from groups treated at different times is a weighted average of the separate 2x2 DiD comparisons that can be constructed. Weights depend on the group sizes but also on variation in treatment status, so are larger for groups treated near the middle of the observation window. This also means weights (and resulting estimates) can differ by changing the length of the observation window. The details of this are technical and beyond the scope of this document; see Cunningham <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">2021</a>)</span>, Huntington-Klein <span class="citation" data-cites="ref452">(<a href="references.html#ref-ref452" role="doc-biblioref">2022</a>)</span>, or Goodman-Bacon <span class="citation" data-cites="ref21034">(<a href="references.html#ref-ref21034" role="doc-biblioref">2021</a>)</span> for further details.</p>
</section>
<section id="applications" class="level2">
<h2 class="anchored" data-anchor-id="applications">5.6.2 Applications</h2>
<p>Li &amp; Avendano <span class="citation" data-cites="ref21050">(<a href="references.html#ref-ref21050" role="doc-biblioref">2023</a>)</span> use MCS data to assess the employment and mental health impacts of the Lone Parent Obligation (LPO), a welfare-to-work scheme that placed job-search requirements on lone parents on benefits that was introduced during MCS cohort members’ childhoods. The authors use a DiD design, comparing children in lone-mother and two-parent households before and after the rollout of the policy to MCS-aged households in 2012. They find that, relative to the change in outcomes in the two-parent group, the introduction of the LPO was associated with greater maternal employment but also greater maternal and cohort member psychological difficulties in lone-parent households. The authors also find some evidence in support of the parallel trends assumption when looking at pre-treatment trends. However, their analysis assumes that parallel trends would occur post-LPO, which in this case would be during the cohort members’ adolescence – it is possible there are unique difficulties at this age in lone-parent households, which would violate parallel trends. Further, there were policy changes other than the LPO over the period which may have disproportionately affected lone parents (e.g., benefit cap, move to universal credit, and so on).</p>
<p>An additional limitation with the study was that the treatment variable – lone-parent household – is in fact time-varying and could be biased by changing composition of this group, especially if the LPO influences partnership decisions. However, they observed similar results when restricting to households whose partnership status did not change. An additional analysis that was not explored by the authors but could have been informative would be to compare lone-parent households according to whether they were or were not in receipt of income support pre-LPO (and thus may vary in their exposure to the policy).</p>
<p>Avendano &amp; Panico <span class="citation" data-cites="ref646">(<a href="references.html#ref-ref646" role="doc-biblioref">2018</a>)</span> also use the Millennium Cohort Study for policy evaluation. Specifically, they estimate the wellbeing and health effects of a 2003 legislative change that encouraged, though did not mandate, employers to implement flexible working practices (e.g., part-time and school-term contracts). Using a DiD design, they compare a group likely unaffected by the law (working mothers whose employers in Sweep 1 – prior to the law’s implementation – already offered flexible working) with a group who could be (working mothers whose employers did not offer flexible working in Sweep 1). They find no consistent evidence of an effect of the policy on mothers’ health and wellbeing in Sweeps 2-4 (2003-08). As the pre-treatment period comprised only Sweep 1, the authors were not able to assess differences in pre-treatment trends.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Note, the estimand targeted in this study is the causal effect of the law upon mothers employed (at baseline) by firms yet to offer flexible working practices. While relevant for policy, such an effect would presumably mainly operate among the subset of women whose employers begin to offer flexible working practices. The estimand is therefore not the effect of the flexible working practices per se. Moreover, mothers expected to benefit most from flexible working practices could feasibly have chosen employers already offering these prior to the law’s enactment. The estimand therefore does not represent the effect of flexible working practices on those who choose such firms either. Both of these factors may explain the null results and have ramifications for the interpretation of the study.</p>
</section>
<section id="opportunities" class="level2">
<h2 class="anchored" data-anchor-id="opportunities">5.6.3 Opportunities</h2>
<p>Given the length and breadth of CLS’s cohorts, there are potentially many opportunities to use DiD designs with the data, both for policy evaluation and to assess the effect of events happening within cohort members’ (or their families’) lives (unemployment, divorce, etc.). This is also helped by the large, diverse samples that the cohorts comprise as this can make it possible to identify groups plausibly affected and unaffected by an exposure <span class="citation" data-cites="ref21050">(e.g., as with lone- vs.&nbsp;two-parent households in <a href="references.html#ref-ref21050" role="doc-biblioref">Li &amp; Avendano, 2023</a>)</span>.</p>
<p>The cross-sectional variation used in the Li &amp; Avendano <span class="citation" data-cites="ref21050">(<a href="references.html#ref-ref21050" role="doc-biblioref">2023</a>)</span> and Avendano &amp; Panico <span class="citation" data-cites="ref646">(<a href="references.html#ref-ref646" role="doc-biblioref">2018</a>)</span> analyses described above was exposure due to being a potential target of the policy. Other opportunities can arise from geographic variation. For instance, Hawkins et al. <span class="citation" data-cites="ref648">(<a href="references.html#ref-ref648" role="doc-biblioref">2011</a>)</span> use MCS data to compare smoking rates in Scotland and England before and after the introduction of anti-smoking legislation in Scotland.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> DiD designs can also arise from temporal variation in birth dates, though this is limited in CLS cohorts due to the recruitment criteria for members of some cohorts (e.g., NCDS cohort members were born in a single week of March 1958), but does not apply to cohort members’ families (e.g., parents). Temporal variation can also appear due to variation in interview dates (see <a href="./05-08-natural-experiments.html">Section 5.8</a>).</p>
<ul>
<li></li>
</ul>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list" style="display: none">

<div id="ref-ref646" class="csl-entry" role="listitem">
Avendano, M., &amp; Panico, L. (2018). Do flexible work policies improve parents’ health? A natural experiment based on the UK Millennium Cohort Study. <em>J Epidemiol Community Health</em>, <em>72</em>(3), 244–251. <a href="https://doi.org/10.1136/jech-2017-209847">https://doi.org/10.1136/jech-2017-209847</a>
</div>
<div id="ref-ref21035" class="csl-entry" role="listitem">
Caniglia, E. C., &amp; Murray, E. J. (2020). Difference-in-Difference in the Time of Cholera: a Gentle Introduction for Epidemiologists. <em>Current Epidemiology Reports</em>, <em>7</em>(4), 203–211. <a href="https://doi.org/10.1007/s40471-020-00245-2">https://doi.org/10.1007/s40471-020-00245-2</a>
</div>
<div id="ref-ref21036" class="csl-entry" role="listitem">
Coleman, T. (2019). <em>Causality in the Time of Cholera: John Snow As a Prototype for Causal Inference</em> (SSRN Scholarly Paper 3262234). Social Science Research Network. <a href="https://doi.org/10.2139/ssrn.3262234">https://doi.org/10.2139/ssrn.3262234</a>
</div>
<div id="ref-ref451" class="csl-entry" role="listitem">
Cunningham, S. (2021). <em>Causal inference: the mixtape</em>. Yale University Press. <a href="https://doi.org/10.2307/j.ctv1c29t27">https://doi.org/10.2307/j.ctv1c29t27</a>
</div>
<div id="ref-ref21069" class="csl-entry" role="listitem">
Ding, P., &amp; Li, F. (2019). A Bracketing Relationship between Difference-in-Differences and Lagged-Dependent-Variable Adjustment. <em>Political Analysis</em>, <em>27</em>(4), 605–615. <a href="https://doi.org/10.1017/pan.2019.25">https://doi.org/10.1017/pan.2019.25</a>
</div>
<div id="ref-ref21041" class="csl-entry" role="listitem">
Girma, S., &amp; Paton, D. (2011). The impact of emergency birth control on teen pregnancy and STIs. <em>Journal of Health Economics</em>, <em>30</em>(2), 373–380. <a href="https://doi.org/10.1016/j.jhealeco.2010.12.004">https://doi.org/10.1016/j.jhealeco.2010.12.004</a>
</div>
<div id="ref-ref21034" class="csl-entry" role="listitem">
Goodman-Bacon, A. (2021). Difference-in-differences with variation in treatment timing. <em>Journal of Econometrics, Themed Issue: Treatment Effect 1</em>, <em>225</em>(2), 254–277. <a href="https://doi.org/10.1016/j.jeconom.2021.03.014">https://doi.org/10.1016/j.jeconom.2021.03.014</a>
</div>
<div id="ref-ref648" class="csl-entry" role="listitem">
Hawkins, S. S., Cole, T. J., &amp; Law, C. (2011). Examining smoking behaviours among parents from the UK Millennium Cohort Study after the smoke-free legislation in Scotland. <em>Tobacco Control</em>, <em>20</em>(2), 112–118. <a href="https://doi.org/10.1136/tc.2010.037028">https://doi.org/10.1136/tc.2010.037028</a>
</div>
<div id="ref-ref452" class="csl-entry" role="listitem">
Huntington-Klein, N. (2022). <em>The Effect: An Introduction To Research Design And Causality</em> (1st ed.). CRC Press, Taylor &amp; Francis Group.
</div>
<div id="ref-ref21050" class="csl-entry" role="listitem">
Li, L., &amp; Avendano, M. (2023). Lone parents’ employment policy and adolescents’ socioemotional development: Quasi-experimental evidence from a UK reform. <em>Social Science &amp; Medicine</em>, <em>320</em>, 115754. <a href="https://doi.org/10.1016/j.socscimed.2023.115754">https://doi.org/10.1016/j.socscimed.2023.115754</a>
</div>
<div id="ref-ref21040" class="csl-entry" role="listitem">
Rambachan, A., &amp; Roth, J. (2023). A More Credible Approach to Parallel Trends. <em>Review of Economic Studies</em>, <em>90</em>(5), 2555–2591. <a href="https://doi.org/10.1093/restud/rdad018">https://doi.org/10.1093/restud/rdad018</a>
</div>
<div id="ref-ref21042" class="csl-entry" role="listitem">
Vagni, G., &amp; Breen, R. (2021). Earnings and Income Penalties for Motherhood: Estimates for British Women Using the Individual Synthetic Control Method. <em>European Sociological Review</em>, <em>37</em>(5), 834–848. <a href="https://doi.org/10.1093/esr/jcab014">https://doi.org/10.1093/esr/jcab014</a>
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Several authors have used Snow’s Grand Experiment to introduce Difference-in-Differences or placed in a DiD framework. See, for example, Caniglia &amp; Murray <span class="citation" data-cites="ref21035">(<a href="references.html#ref-ref21035" role="doc-biblioref">2020</a>)</span>, Coleman <span class="citation" data-cites="ref21036">(<a href="references.html#ref-ref21036" role="doc-biblioref">2019</a>)</span>, Cunningham <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">2021</a>)</span>, and Huntington-Klein <span class="citation" data-cites="ref452">(<a href="references.html#ref-ref452" role="doc-biblioref">2022</a>)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Even where the assumption is violated, the DiD estimator would be less biased than the simple fixed effects one (<a href="./05-05-longitudinal-fixed-effects.html">Section 5.5</a>) where the difference is time trends (<span class="math inline">\(t_{L} - t_{SV}\)</span>) is smaller than the time-trend in the treated unit itself (<span class="math inline">\(t_{L}\)</span>)<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Readers may also explore the Synthetic Control method, which weights untreated observations to create a synthetic control data unit such that pre-treatment trends in the outcome for treated and synthetic control are similar. See Cunningham <span class="citation" data-cites="ref451">(<a href="references.html#ref-ref451" role="doc-biblioref">2021</a>)</span> for further detail and Vagni &amp; Breen <span class="citation" data-cites="ref21042">(<a href="references.html#ref-ref21042" role="doc-biblioref">2021</a>)</span> for an application in cohort data.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The triple-difference design has overlap with the negative control outcome and negative control population designs discussed in <a href="./05-15-negative-control-outcomes-and-exposures.html">Sections 5.15</a> and <a href="./05-16-cross-context-analysis.html">5.16</a>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>A possible alternative (or addition) in this case, which the authors did not avail themselves of, would be to use negative control ‘placebo’ outcomes (see <a href="./05-15-negative-control-outcomes-and-exposures.html">Section 5.15</a>).<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Rather than a DiD setup, Hawkins et al. <span class="citation" data-cites="ref648">(<a href="references.html#ref-ref648" role="doc-biblioref">2011</a>)</span> condition upon lagged dependent variables. See Ding &amp; Li <span class="citation" data-cites="ref21069">(<a href="references.html#ref-ref21069" role="doc-biblioref">2019</a>)</span> for discussion of the correspondence between the DiD and lagged dependent variable estimators.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/cls-data\.github\.io\/causal-inference-review\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-05-longitudinal-fixed-effects.html" class="pagination-link" aria-label="5.5 (Longitudinal) Fixed Effects">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">5.5 (Longitudinal) Fixed Effects</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-07-study-initiated-experiments.html" class="pagination-link" aria-label="5.7 Study-Initiated Experiments">
        <span class="nav-page-text"><span class="chapter-title">5.7 Study-Initiated Experiments</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Wright, Tomova, Danka, Ploubidis &amp; Silverwood · Centre for Longitudinal Studies, UCL</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/CLS-Data/causal-inference-review/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>